import { AdmissionApplication } from "@/types";

export const initialAdmissions: AdmissionApplication[] = [
  {
    id: "adm-01",
    applicationNumber: "ADM-2026-101",
    applicantFirstName: "Aditya",
    applicantLastName: "Deshmukh",
    applicantFullName: "Aditya Deshmukh",
    dateOfBirth: "2011-05-14",
    gender: "Male",
    gradeApplied: "Class 9",
    branchId: "br-west-02",
    branchName: "Westside STEM & Innovation Academy",
    academicYear: "2026-2027",
    submissionDate: "2026-08-28T10:30:00.000Z",
    status: "UNDER_REVIEW",
    parentName: "Sachin Deshmukh",
    parentRelationship: "Father",
    parentEmail: "sachin.deshmukh@gmail.com",
    parentPhone: "+91 98901 88991",
    address: "740 Baner Road",
    city: "Pune",
    state: "Maharashtra",
    postalCode: "411045",
    previousSchool: "Vidya Valley School",
    previousGrade: "Class 8",
    previousGpa: "91.2%",
    entranceTestScore: 94,
    interviewDate: "2026-09-08T14:00:00.000Z",
    interviewFeedback: "Strong aptitude in algebra and science; district robotics participant.",
    documents: [
      { id: "doc-adm-01", name: "Birth_Certificate.pdf", required: true, submitted: true, verified: true },
      { id: "doc-adm-02", name: "Previous_Class8_Report_Card.pdf", required: true, submitted: true, verified: true },
      { id: "doc-adm-03", name: "Aadhaar_Card.pdf", required: true, submitted: true, verified: false },
      { id: "doc-adm-04", name: "Address_Proof.pdf", required: true, submitted: true, verified: true },
      { id: "doc-adm-05", name: "Transfer_Certificate.pdf", required: false, submitted: true, verified: false },
    ],
    notes: "Applied for advanced Science batch; NTSE aspirant.",
    aadhaarNumber: "345678901255",
    category: "General",
    religion: "Hindu",
    motherTongue: "Marathi",
    board: "CBSE",
    rteQuota: false,
    createdAt: "2026-08-28T10:30:00.000Z",
    updatedAt: "2026-09-01T15:00:00.000Z",
  },
  {
    id: "adm-02",
    applicationNumber: "ADM-2026-102",
    applicantFirstName: "Sanya",
    applicantLastName: "Kulkarni",
    applicantFullName: "Sanya Kulkarni",
    dateOfBirth: "2010-08-20",
    gender: "Female",
    gradeApplied: "Class 10",
    branchId: "br-apex-01",
    branchName: "Apex Global Campus",
    academicYear: "2026-2027",
    submissionDate: "2026-08-25T11:15:00.000Z",
    status: "APPROVED",
    parentName: "Milind Kulkarni",
    parentRelationship: "Father",
    parentEmail: "milind.kulkarni@gmail.com",
    parentPhone: "+91 98220 77112",
    address: "210 Karve Putala, Kothrud",
    city: "Pune",
    state: "Maharashtra",
    postalCode: "411038",
    previousSchool: "Abhinava Vidyalaya",
    previousGrade: "Class 9",
    previousGpa: "95.6%",
    entranceTestScore: 98,
    interviewDate: "2026-08-30T10:00:00.000Z",
    interviewFeedback: "Confident communicator; inter-school debate finalist.",
    documents: [
      { id: "doc-adm-11", name: "Birth_Certificate.pdf", required: true, submitted: true, verified: true },
      { id: "doc-adm-12", name: "Class9_Report_Card.pdf", required: true, submitted: true, verified: true },
      { id: "doc-adm-13", name: "Aadhaar_Card.pdf", required: true, submitted: true, verified: true },
      { id: "doc-adm-14", name: "Address_Proof.pdf", required: true, submitted: true, verified: true },
    ],
    notes: "Approved. Awaiting fee payment and section allotment.",
    aadhaarNumber: "234567890124",
    category: "General",
    religion: "Hindu",
    motherTongue: "Marathi",
    board: "CBSE",
    rteQuota: false,
    createdAt: "2026-08-25T11:15:00.000Z",
    updatedAt: "2026-09-01T12:00:00.000Z",
  },
  {
    id: "adm-03",
    applicationNumber: "ADM-2026-103",
    applicantFirstName: "Rohan",
    applicantLastName: "Joshi",
    applicantFullName: "Rohan Joshi",
    dateOfBirth: "2012-03-10",
    gender: "Male",
    gradeApplied: "Class 7",
    branchId: "br-green-04",
    branchName: "Green Valley International School",
    academicYear: "2026-2027",
    submissionDate: "2026-08-29T14:40:00.000Z",
    status: "NEW",
    parentName: "Nilesh Joshi",
    parentRelationship: "Father",
    parentEmail: "nilesh.joshi@gmail.com",
    parentPhone: "+91 98450 99441",
    address: "518 Whitefield",
    city: "Bengaluru",
    state: "Karnataka",
    postalCode: "560066",
    previousSchool: "National Public School",
    previousGrade: "Class 6",
    previousGpa: "88.4%",
    documents: [
      { id: "doc-adm-21", name: "Birth_Certificate.pdf", required: true, submitted: true, verified: false },
      { id: "doc-adm-22", name: "Class6_Report_Card.pdf", required: true, submitted: true, verified: false },
      { id: "doc-adm-23", name: "Aadhaar_Card.pdf", required: true, submitted: false, verified: false },
      { id: "doc-adm-24", name: "Address_Proof.pdf", required: true, submitted: true, verified: false },
    ],
    notes: "New submission. Office assigned to verify Aadhaar and address proof.",
    category: "OBC",
    religion: "Hindu",
    motherTongue: "Kannada",
    board: "ICSE",
    rteQuota: false,
    createdAt: "2026-08-29T14:40:00.000Z",
    updatedAt: "2026-08-29T14:40:00.000Z",
  },
  {
    id: "adm-04",
    applicationNumber: "ADM-2026-104",
    applicantFirstName: "Navya",
    applicantLastName: "Agarwal",
    applicantFullName: "Navya Agarwal",
    dateOfBirth: "2010-11-25",
    gender: "Female",
    gradeApplied: "Class 10",
    branchId: "br-river-06",
    branchName: "Riverdale Arts & Sports Academy",
    academicYear: "2026-2027",
    submissionDate: "2026-08-20T09:00:00.000Z",
    status: "INTERVIEW_SCHEDULED",
    parentName: "Pooja Agarwal",
    parentRelationship: "Mother",
    parentEmail: "pooja.agarwal@gmail.com",
    parentPhone: "+91 98980 33221",
    address: "819 Sabarmati West",
    city: "Ahmedabad",
    state: "Gujarat",
    postalCode: "380061",
    previousSchool: "St. Xavier's School",
    previousGrade: "Class 9",
    previousGpa: "90.1%",
    entranceTestScore: 91,
    interviewDate: "2026-09-05T11:00:00.000Z",
    interviewFeedback: "Drawing portfolio cleared round one; aptitude interaction scheduled with Art HOD.",
    documents: [
      { id: "doc-adm-31", name: "Birth_Certificate.pdf", required: true, submitted: true, verified: true },
      { id: "doc-adm-32", name: "Drawing_Portfolio.pdf", required: true, submitted: true, verified: true },
      { id: "doc-adm-33", name: "Aadhaar_Card.pdf", required: true, submitted: true, verified: true },
      { id: "doc-adm-34", name: "Address_Proof.pdf", required: true, submitted: true, verified: true },
    ],
    notes: "Applying for Kala Utsav arts quota seat.",
    aadhaarNumber: "456789012387",
    category: "General",
    religion: "Hindu",
    motherTongue: "Gujarati",
    board: "CBSE",
    rteQuota: false,
    createdAt: "2026-08-20T09:00:00.000Z",
    updatedAt: "2026-08-30T10:00:00.000Z",
  },
  {
    id: "adm-05",
    applicationNumber: "ADM-2026-105",
    applicantFirstName: "Kabir",
    applicantLastName: "Malhotra",
    applicantFullName: "Kabir Malhotra",
    dateOfBirth: "2022-01-14",
    gender: "Male",
    gradeApplied: "UKG",
    branchId: "br-north-03",
    branchName: "Northpoint Montessori & Prep",
    academicYear: "2026-2027",
    submissionDate: "2026-08-22T13:00:00.000Z",
    status: "APPROVED",
    parentName: "Kavita Malhotra",
    parentRelationship: "Mother",
    parentEmail: "kavita.malhotra@gmail.com",
    parentPhone: "+91 98230 66221",
    address: "44 College Road",
    city: "Nashik",
    state: "Maharashtra",
    postalCode: "422005",
    documents: [
      { id: "doc-adm-41", name: "Birth_Certificate.pdf", required: true, submitted: true, verified: true },
      { id: "doc-adm-42", name: "Vaccination_Record.pdf", required: true, submitted: true, verified: true },
      { id: "doc-adm-43", name: "Address_Proof.pdf", required: true, submitted: true, verified: true },
    ],
    notes: "Admitted to UKG morning batch under RTE quota.",
    category: "SC",
    religion: "Buddhist",
    motherTongue: "Marathi",
    board: "CBSE",
    rteQuota: true,
    createdAt: "2026-08-22T13:00:00.000Z",
    updatedAt: "2026-08-29T16:00:00.000Z",
  },
  {
    id: "adm-06",
    applicationNumber: "ADM-2026-106",
    applicantFirstName: "Dev",
    applicantLastName: "Malhotra",
    applicantFullName: "Dev Malhotra",
    dateOfBirth: "2009-12-05",
    gender: "Male",
    gradeApplied: "Class 11",
    branchId: "br-horizon-05",
    branchName: "Horizon High & College Prep",
    academicYear: "2026-2027",
    submissionDate: "2026-08-15T15:20:00.000Z",
    status: "WAITLISTED",
    parentName: "Anil Malhotra",
    parentRelationship: "Father",
    parentEmail: "anil.malhotra@gmail.com",
    parentPhone: "+91 98290 44001",
    address: "920 Calgeri Marg, Malviya Nagar",
    city: "Jaipur",
    state: "Rajasthan",
    postalCode: "302017",
    previousSchool: "St. Anselm's School",
    previousGrade: "Class 10",
    previousGpa: "84.6%",
    entranceTestScore: 82,
    documents: [
      { id: "doc-adm-51", name: "Birth_Certificate.pdf", required: true, submitted: true, verified: true },
      { id: "doc-adm-52", name: "Class10_Board_Marksheet.pdf", required: true, submitted: true, verified: true },
    ],
    notes: "Waitlisted for Commerce stream due to section capacity limits.",
    category: "General",
    religion: "Hindu",
    motherTongue: "Hindi",
    board: "CBSE",
    rteQuota: false,
    createdAt: "2026-08-15T15:20:00.000Z",
    updatedAt: "2026-08-25T11:00:00.000Z",
  },
];
