import { AdmissionApplication } from "@/types";

export const initialAdmissions: AdmissionApplication[] = [
  {
    id: "adm-01",
    applicationNumber: "ADM-2026-101",
    applicantFirstName: "Julian",
    applicantLastName: "Vance",
    applicantFullName: "Julian Vance",
    dateOfBirth: "2011-05-14",
    gender: "Male",
    gradeApplied: "Grade 9",
    branchId: "br-west-02",
    branchName: "Westside STEM & Innovation Academy",
    academicYear: "2026-2027",
    submissionDate: "2026-08-28T10:30:00.000Z",
    status: "UNDER_REVIEW",
    parentName: "Dr. Robert & Amanda Vance",
    parentRelationship: "Father",
    parentEmail: "robert.vance@biotech.org",
    parentPhone: "+1 (555) 345-8899",
    address: "740 Oakridge Lane",
    city: "Westfield",
    state: "CA",
    postalCode: "94025",
    previousSchool: "St. Jude Middle School",
    previousGrade: "Grade 8",
    previousGpa: "3.92",
    entranceTestScore: 94,
    interviewDate: "2026-09-08T14:00:00.000Z",
    interviewFeedback: "Strong analytical aptitude in algebra and physics; robotics tournament participant.",
    documents: [
      { id: "doc-adm-01", name: "Birth_Certificate.pdf", required: true, submitted: true, verified: true },
      { id: "doc-adm-02", name: "Previous_Grade8_Report_Card.pdf", required: true, submitted: true, verified: true },
      { id: "doc-adm-03", name: "Immunization_Health_Form.pdf", required: true, submitted: true, verified: false },
      { id: "doc-adm-04", name: "Proof_Of_Residence.pdf", required: true, submitted: true, verified: true },
      { id: "doc-adm-05", name: "Teacher_Recommendation.pdf", required: false, submitted: true, verified: false },
    ],
    notes: "Applied for STEM Accelerated Honors track with robotics scholarship.",
    createdAt: "2026-08-28T10:30:00.000Z",
    updatedAt: "2026-09-01T15:00:00.000Z",
  },
  {
    id: "adm-02",
    applicationNumber: "ADM-2026-102",
    applicantFirstName: "Amara",
    applicantLastName: "Okonkwo",
    applicantFullName: "Amara Okonkwo",
    dateOfBirth: "2010-08-20",
    gender: "Female",
    gradeApplied: "Grade 10",
    branchId: "br-apex-01",
    branchName: "Apex Global Campus",
    academicYear: "2026-2027",
    submissionDate: "2026-08-25T11:15:00.000Z",
    status: "APPROVED",
    parentName: "Emeka & Chinwe Okonkwo",
    parentRelationship: "Father",
    parentEmail: "emeka.okonkwo@lawpartners.com",
    parentPhone: "+1 (555) 234-7711",
    address: "210 Grand Avenue, Apt 4B",
    city: "Metro City",
    state: "CA",
    postalCode: "94105",
    previousSchool: "International Preparatory Academy",
    previousGrade: "Grade 9",
    previousGpa: "4.0",
    entranceTestScore: 98,
    interviewDate: "2026-08-30T10:00:00.000Z",
    interviewFeedback: "Outstanding communicative confidence; national debate finalist.",
    documents: [
      { id: "doc-adm-11", name: "Birth_Certificate.pdf", required: true, submitted: true, verified: true },
      { id: "doc-adm-12", name: "Grade9_Official_Transcript.pdf", required: true, submitted: true, verified: true },
      { id: "doc-adm-13", name: "Immunization_Health_Form.pdf", required: true, submitted: true, verified: true },
      { id: "doc-adm-14", name: "Proof_Of_Residence.pdf", required: true, submitted: true, verified: true },
    ],
    notes: "Approved for AP Capstone track. Awaiting student registration finalization.",
    createdAt: "2026-08-25T11:15:00.000Z",
    updatedAt: "2026-09-01T12:00:00.000Z",
  },
  {
    id: "adm-03",
    applicationNumber: "ADM-2026-103",
    applicantFirstName: "Benjamin",
    applicantLastName: "Kim",
    applicantFullName: "Benjamin Kim",
    dateOfBirth: "2012-03-10",
    gender: "Male",
    gradeApplied: "Grade 7",
    branchId: "br-green-04",
    branchName: "Green Valley International School",
    academicYear: "2026-2027",
    submissionDate: "2026-08-29T14:40:00.000Z",
    status: "NEW",
    parentName: "Dr. Ji-Hoon Kim",
    parentRelationship: "Father",
    parentEmail: "jihoon.kim@stanford-edu.us",
    parentPhone: "+1 (555) 567-9944",
    address: "518 Highland Woods Crest",
    city: "Green Valley",
    state: "CA",
    postalCode: "95616",
    previousSchool: "Palo Alto Middle School",
    previousGrade: "Grade 6",
    previousGpa: "3.85",
    documents: [
      { id: "doc-adm-21", name: "Birth_Certificate.pdf", required: true, submitted: true, verified: false },
      { id: "doc-adm-22", name: "Grade6_Report_Card.pdf", required: true, submitted: true, verified: false },
      { id: "doc-adm-23", name: "Immunization_Health_Form.pdf", required: true, submitted: false, verified: false },
      { id: "doc-adm-24", name: "Proof_Of_Residence.pdf", required: true, submitted: true, verified: false },
    ],
    notes: "New submission. Admissions officer assigned to verify health documents.",
    createdAt: "2026-08-29T14:40:00.000Z",
    updatedAt: "2026-08-29T14:40:00.000Z",
  },
  {
    id: "adm-04",
    applicationNumber: "ADM-2026-104",
    applicantFirstName: "Chloe",
    applicantLastName: "Sinclair",
    applicantFullName: "Chloe Sinclair",
    dateOfBirth: "2010-11-25",
    gender: "Female",
    gradeApplied: "Grade 10",
    branchId: "br-river-06",
    branchName: "Riverdale Arts & Sports Academy",
    academicYear: "2026-2027",
    submissionDate: "2026-08-20T09:00:00.000Z",
    status: "INTERVIEW_SCHEDULED",
    parentName: "Gordon & Felicity Sinclair",
    parentRelationship: "Mother",
    parentEmail: "felicity.sinclair@fashionhouse.com",
    parentPhone: "+1 (555) 789-3322",
    address: "819 Waterfront Drive",
    city: "Riverdale",
    state: "CA",
    postalCode: "92501",
    previousSchool: "St. Martin Arts Conservatory",
    previousGrade: "Grade 9",
    previousGpa: "3.75",
    entranceTestScore: 91,
    interviewDate: "2026-09-05T11:00:00.000Z",
    interviewFeedback: "Portfolio passed initial review; audition scheduled with Music Department head.",
    documents: [
      { id: "doc-adm-31", name: "Birth_Certificate.pdf", required: true, submitted: true, verified: true },
      { id: "doc-adm-32", name: "Music_Audition_Tape.mp4", required: true, submitted: true, verified: true },
      { id: "doc-adm-33", name: "Immunization_Health_Form.pdf", required: true, submitted: true, verified: true },
      { id: "doc-adm-34", name: "Proof_Of_Residence.pdf", required: true, submitted: true, verified: true },
    ],
    notes: "Auditioning for classical cello and orchestra scholarship seat.",
    createdAt: "2026-08-20T09:00:00.000Z",
    updatedAt: "2026-08-30T10:00:00.000Z",
  },
  {
    id: "adm-05",
    applicationNumber: "ADM-2026-105",
    applicantFirstName: "Noah",
    applicantLastName: "Sterling",
    applicantFullName: "Noah Sterling",
    dateOfBirth: "2022-01-14",
    gender: "Male",
    gradeApplied: "Montessori Primary",
    branchId: "br-north-03",
    branchName: "Northpoint Montessori & Prep",
    academicYear: "2026-2027",
    submissionDate: "2026-08-22T13:00:00.000Z",
    status: "APPROVED",
    parentName: "Henry & Charlotte Sterling",
    parentRelationship: "Mother",
    parentEmail: "charlotte.sterling@greenridge.org",
    parentPhone: "+1 (555) 456-6622",
    address: "44 Valley Stream Court",
    city: "Northpoint",
    state: "CA",
    postalCode: "94901",
    documents: [
      { id: "doc-adm-41", name: "Birth_Certificate.pdf", required: true, submitted: true, verified: true },
      { id: "doc-adm-42", name: "Immunization_Records.pdf", required: true, submitted: true, verified: true },
      { id: "doc-adm-43", name: "Proof_Of_Address.pdf", required: true, submitted: true, verified: true },
    ],
    notes: "Enrolled in Sunflowers Studio Montessori morning session.",
    createdAt: "2026-08-22T13:00:00.000Z",
    updatedAt: "2026-08-29T16:00:00.000Z",
  },
  {
    id: "adm-06",
    applicationNumber: "ADM-2026-106",
    applicantFirstName: "Daniel",
    applicantLastName: "Ross",
    applicantFullName: "Daniel Ross",
    dateOfBirth: "2009-12-05",
    gender: "Male",
    gradeApplied: "Grade 11",
    branchId: "br-horizon-05",
    branchName: "Horizon High & College Prep",
    academicYear: "2026-2027",
    submissionDate: "2026-08-15T15:20:00.000Z",
    status: "WAITLISTED",
    parentName: "Arthur Ross",
    parentRelationship: "Father",
    parentEmail: "arthur.ross@investcap.com",
    parentPhone: "+1 (555) 678-4400",
    address: "920 University Crest Avenue",
    city: "Horizon Heights",
    state: "CA",
    postalCode: "94704",
    previousSchool: "Pacific Coast Academy",
    previousGrade: "Grade 10",
    previousGpa: "3.62",
    entranceTestScore: 82,
    documents: [
      { id: "doc-adm-51", name: "Birth_Certificate.pdf", required: true, submitted: true, verified: true },
      { id: "doc-adm-52", name: "Grade10_Report_Card.pdf", required: true, submitted: true, verified: true },
    ],
    notes: "Waitlisted for AP Economics track due to section capacity limits.",
    createdAt: "2026-08-15T15:20:00.000Z",
    updatedAt: "2026-08-25T11:00:00.000Z",
  },
];
