import { Branch } from "@/types";

export const initialBranches: Branch[] = [
  {
    id: "br-apex-01",
    name: "Apex Global Campus",
    code: "APX-01",
    tagline: "Flagship Metro Academic & Innovation Center",
    type: "Main Campus",
    principalName: "Dr. Eleanor Vance, Ph.D.",
    principalEmail: "e.vance@apex.edu",
    principalPhone: "+1 (555) 234-5678",
    address: "100 Innovation Boulevard, Downtown Core",
    city: "Metro City",
    state: "CA",
    postalCode: "94105",
    phone: "+1 (555) 234-5000",
    email: "info@apex.edu",
    website: "https://apex.edu",
    establishedYear: 2010,
    status: "ACTIVE",
    totalStudents: 1420,
    capacity: 1800,
    totalTeachers: 86,
    totalStaff: 24,
    totalWorkers: 32,
    monthlyRevenue: 345000,
    monthlyExpenses: 218000,
    attendanceRate: 96.4,
    feeCollectionRate: 94.2,
    facilities: [
      "Olympic Swimming Pool",
      "Robotics AI Lab",
      "Digital Auditorium (800-seat)",
      "Central Library",
      "Smart Classrooms",
      "Cafeteria",
      "Solar Campus Grid",
    ],
    departments: [
      { name: "Science & Technology", head: "Prof. Marcus Brody", staffCount: 28 },
      { name: "Mathematics & Computing", head: "Dr. Sarah Lin", staffCount: 22 },
      { name: "Humanities & Languages", head: "Prof. Robert Thorne", staffCount: 20 },
      { name: "Physical Education & Sports", head: "Coach Dave Miller", staffCount: 16 },
    ],
    color: "#3b82f6", // Blue
    createdAt: "2020-01-15T00:00:00.000Z",
    updatedAt: "2026-08-20T10:30:00.000Z",
  },
  {
    id: "br-west-02",
    name: "Westside STEM & Innovation Academy",
    code: "WST-02",
    tagline: "Empowering Future Engineers & Research Scholars",
    type: "STEM Academy",
    principalName: "Dr. James K. Sutherland",
    principalEmail: "j.sutherland@westside.edu",
    principalPhone: "+1 (555) 345-6789",
    address: "450 Silicon Parkway, Tech District",
    city: "Westfield",
    state: "CA",
    postalCode: "94025",
    phone: "+1 (555) 345-6000",
    email: "admissions@westside.edu",
    website: "https://westside-stem.edu",
    establishedYear: 2016,
    status: "ACTIVE",
    totalStudents: 850,
    capacity: 1000,
    totalTeachers: 54,
    totalStaff: 16,
    totalWorkers: 18,
    monthlyRevenue: 240000,
    monthlyExpenses: 152000,
    attendanceRate: 97.1,
    feeCollectionRate: 96.8,
    facilities: [
      "MakerSpace & 3D Prototyping",
      "Physics & Biotech Labs",
      "Astronomy Observatory",
      "VR / AR Classroom Suite",
      "Fiber Optic Network",
    ],
    departments: [
      { name: "Computer Science & AI", head: "Elena Rostova", staffCount: 18 },
      { name: "Applied Physics & Mechanics", head: "Dr. Arthur Pendelton", staffCount: 16 },
      { name: "Bioengineering & Chemistry", head: "Dr. Maya Patel", staffCount: 20 },
    ],
    color: "#8b5cf6", // Purple
    createdAt: "2021-04-10T00:00:00.000Z",
    updatedAt: "2026-08-24T14:15:00.000Z",
  },
  {
    id: "br-north-03",
    name: "Northpoint Montessori & Prep",
    code: "NPT-03",
    tagline: "Nurturing Curiosity & Foundation Learning",
    type: "Montessori & Prep",
    principalName: "Mrs. Clara Higgins, M.Ed.",
    principalEmail: "c.higgins@northpoint.edu",
    principalPhone: "+1 (555) 456-7890",
    address: "78 Maple Grove Way, North Foothills",
    city: "Northpoint",
    state: "CA",
    postalCode: "94901",
    phone: "+1 (555) 456-7000",
    email: "contact@northpoint.edu",
    website: "https://northpointprep.edu",
    establishedYear: 2018,
    status: "ACTIVE",
    totalStudents: 620,
    capacity: 750,
    totalTeachers: 42,
    totalStaff: 12,
    totalWorkers: 15,
    monthlyRevenue: 165000,
    monthlyExpenses: 102000,
    attendanceRate: 94.8,
    feeCollectionRate: 91.5,
    facilities: [
      "Sensory Play Gardens",
      "Montessori Activity Studios",
      "Children's Amphitheater",
      "Organic Farm & Petting Zone",
      "Pediatric Health Wing",
    ],
    departments: [
      { name: "Early Childhood (Toddler & Primary)", head: "Annette Dupont", staffCount: 22 },
      { name: "Elementary Foundation", head: "Hannah Montgomery", staffCount: 20 },
    ],
    color: "#10b981", // Emerald
    createdAt: "2021-09-01T00:00:00.000Z",
    updatedAt: "2026-08-28T09:00:00.000Z",
  },
  {
    id: "br-green-04",
    name: "Green Valley International School",
    code: "GVI-04",
    tagline: "Global Citizenship, Sustainability & Cambridge IB",
    type: "International",
    principalName: "Sir Julian Sterling, OBE",
    principalEmail: "j.sterling@greenvalley.org",
    principalPhone: "+1 (555) 567-8901",
    address: "220 Eco Valley Drive, Highland Woods",
    city: "Green Valley",
    state: "CA",
    postalCode: "95616",
    phone: "+1 (555) 567-8000",
    email: "admissions@greenvalley.org",
    website: "https://greenvalley.org",
    establishedYear: 2012,
    status: "ACTIVE",
    totalStudents: 1180,
    capacity: 1500,
    totalTeachers: 72,
    totalStaff: 20,
    totalWorkers: 26,
    monthlyRevenue: 310000,
    monthlyExpenses: 195000,
    attendanceRate: 95.9,
    feeCollectionRate: 95.3,
    facilities: [
      "IB Global Diploma Hub",
      "Botanical Conservatory",
      "Indoor Sports Arena (Basketball/Badminton)",
      "Model UN Assembly Hall",
      "Language Immersion Pods",
    ],
    departments: [
      { name: "International Baccalaureate (IB)", head: "Dr. Nigel Ross", staffCount: 30 },
      { name: "World Languages & Cultures", head: "Madame Sylvie Bernard", staffCount: 22 },
      { name: "Environmental Sciences", head: "Dr. Tariq Al-Mansoor", staffCount: 20 },
    ],
    color: "#059669", // Dark Green
    createdAt: "2020-05-18T00:00:00.000Z",
    updatedAt: "2026-08-30T16:20:00.000Z",
  },
  {
    id: "br-horizon-05",
    name: "Horizon High & College Prep",
    code: "HZN-05",
    tagline: "Academic Rigor & Ivy League Pathways",
    type: "High School",
    principalName: "Prof. Evelyn Ward-Collins",
    principalEmail: "e.ward@horizonprep.edu",
    principalPhone: "+1 (555) 678-9012",
    address: "890 University Crest Avenue",
    city: "Horizon Heights",
    state: "CA",
    postalCode: "94704",
    phone: "+1 (555) 678-9000",
    email: "office@horizonprep.edu",
    website: "https://horizonprep.edu",
    establishedYear: 2014,
    status: "EXPANDING",
    totalStudents: 980,
    capacity: 1200,
    totalTeachers: 60,
    totalStaff: 18,
    totalWorkers: 22,
    monthlyRevenue: 265000,
    monthlyExpenses: 170000,
    attendanceRate: 95.2,
    feeCollectionRate: 93.7,
    facilities: [
      "Advanced Placement (AP) Seminar Halls",
      "Mock Courtroom",
      "Career & College Counseling Pavilion",
      "Cybersecurity Testing Sandbox",
      "Fitness & Conditioning Gym",
    ],
    departments: [
      { name: "AP Sciences & Engineering", head: "Dr. Gregory House", staffCount: 24 },
      { name: "Economics, Law & Social Sciences", head: "Rachel Zane, J.D.", staffCount: 20 },
      { name: "Literature & Rhetoric", head: "Prof. Kenneth Branagh", staffCount: 16 },
    ],
    color: "#f59e0b", // Amber
    createdAt: "2020-11-20T00:00:00.000Z",
    updatedAt: "2026-08-31T11:45:00.000Z",
  },
  {
    id: "br-river-06",
    name: "Riverdale Arts & Sports Academy",
    code: "RVD-06",
    tagline: "Excellence in Performing Arts, Design & Athletics",
    type: "Arts & Sports",
    principalName: "David O. Hernandez, M.F.A.",
    principalEmail: "d.hernandez@riverdale.edu",
    principalPhone: "+1 (555) 789-0123",
    address: "310 Riverside Esplanade",
    city: "Riverdale",
    state: "CA",
    postalCode: "92501",
    phone: "+1 (555) 789-0000",
    email: "arts.sports@riverdale.edu",
    website: "https://riverdale-arts.edu",
    establishedYear: 2019,
    status: "ACTIVE",
    totalStudents: 740,
    capacity: 900,
    totalTeachers: 48,
    totalStaff: 14,
    totalWorkers: 20,
    monthlyRevenue: 195000,
    monthlyExpenses: 130000,
    attendanceRate: 96.1,
    feeCollectionRate: 92.4,
    facilities: [
      "Black Box Theater & Sound Stage",
      "Orchestra Rehearsal Hall",
      "Ceramics & Fine Arts Studio",
      "Full-sized FIFA Turf Soccer Pitch",
      "Gymnastics Pavilion",
    ],
    departments: [
      { name: "Visual Arts & Digital Design", head: "Camilla Rossi", staffCount: 18 },
      { name: "Music, Dance & Theater", head: "Sebastian Wilder", staffCount: 16 },
      { name: "Athletics & Kinesiology", head: "Coach Terrell Owens", staffCount: 14 },
    ],
    color: "#ec4899", // Rose Pink
    createdAt: "2022-02-14T00:00:00.000Z",
    updatedAt: "2026-09-01T15:00:00.000Z",
  },
];
