import { Branch } from "@/types";

export const initialBranches: Branch[] = [
  {
    id: "br-apex-01",
    name: "Apex Global Campus",
    code: "APX-01",
    tagline: "Flagship CBSE Campus — Kothrud, Pune",
    type: "Main Campus",
    principalName: "Dr. Meera Kapoor, Ph.D.",
    principalEmail: "meera.kapoor@apex.edu.in",
    principalPhone: "+91 98220 45678",
    address: "100 Paud Road, Kothrud",
    city: "Pune",
    state: "Maharashtra",
    postalCode: "411038",
    phone: "+91 20 2545 6000",
    email: "info@apex.edu.in",
    website: "https://apex.edu.in",
    establishedYear: 2010,
    status: "ACTIVE",
    totalStudents: 1420,
    capacity: 1800,
    totalTeachers: 86,
    totalStaff: 24,
    totalWorkers: 32,
    monthlyRevenue: 6820000,
    monthlyExpenses: 4310000,
    attendanceRate: 96.4,
    feeCollectionRate: 94.2,
    facilities: [
      "Atal Tinkering Lab",
      "Physics, Chemistry & Biology Labs",
      "Central Library (12000+ books)",
      "Smart Classrooms",
      "Cricket & Football Ground",
      "Canteen (FSSAI licensed)",
      "CCTV + GPS Bus Fleet",
      "RO Drinking Water",
    ],
    departments: [
      { name: "Science", head: "Mrs. Sunita Rao", staffCount: 28 },
      { name: "Mathematics", head: "Mr. Rajesh Kulkarni", staffCount: 22 },
      { name: "Social Science & Languages", head: "Mrs. Kavitha Subramaniam", staffCount: 20 },
      { name: "Physical Education & Sports", head: "Mr. Vikram Singh", staffCount: 16 },
    ],
    color: "#3b82f6", // Blue
    udiseCode: "27250500101",
    affiliationNumber: "1130456",
    board: "CBSE",
    createdAt: "2020-01-15T00:00:00.000Z",
    updatedAt: "2026-08-20T10:30:00.000Z",
  },
  {
    id: "br-west-02",
    name: "Westside STEM & Innovation Academy",
    code: "WST-02",
    tagline: "Science & Computer Academy — Baner, Pune",
    type: "STEM Academy",
    principalName: "Mr. Sanjay Kulkarni, M.Sc., B.Ed.",
    principalEmail: "s.kulkarni@westside.edu.in",
    principalPhone: "+91 98901 23456",
    address: "450 Baner Road, Near Balewadi Stadium",
    city: "Pune",
    state: "Maharashtra",
    postalCode: "411045",
    phone: "+91 20 2729 6000",
    email: "admissions@westside.edu.in",
    website: "https://westside.edu.in",
    establishedYear: 2016,
    status: "ACTIVE",
    totalStudents: 850,
    capacity: 1000,
    totalTeachers: 54,
    totalStaff: 16,
    totalWorkers: 18,
    monthlyRevenue: 4740000,
    monthlyExpenses: 3010000,
    attendanceRate: 97.1,
    feeCollectionRate: 96.8,
    facilities: [
      "Atal Tinkering Lab & Robotics Room",
      "Composite Science Lab",
      "Computer Labs (60+ terminals)",
      "Maths Activity Room",
      "Fiber Broadband + Smart Boards",
    ],
    departments: [
      { name: "Computer Science", head: "Ms. Priya Menon", staffCount: 18 },
      { name: "Physics & Mathematics", head: "Dr. Deepa Nair", staffCount: 16 },
      { name: "Chemistry & Biology", head: "Mrs. Sunita Rao", staffCount: 20 },
    ],
    color: "#8b5cf6", // Purple
    udiseCode: "27250500102",
    affiliationNumber: "1130789",
    board: "CBSE",
    createdAt: "2021-04-10T00:00:00.000Z",
    updatedAt: "2026-08-24T14:15:00.000Z",
  },
  {
    id: "br-north-03",
    name: "Northpoint Montessori & Prep",
    code: "NPT-03",
    tagline: "Pre-Primary & Foundation Wing — Nashik",
    type: "Montessori & Prep",
    principalName: "Mrs. Fatima Sheikh, M.Ed.",
    principalEmail: "f.sheikh@northpoint.edu.in",
    principalPhone: "+91 98230 11223",
    address: "78 College Road, Nashik",
    city: "Nashik",
    state: "Maharashtra",
    postalCode: "422005",
    phone: "+91 253 257 7000",
    email: "contact@northpoint.edu.in",
    website: "https://northpoint.edu.in",
    establishedYear: 2018,
    status: "ACTIVE",
    totalStudents: 620,
    capacity: 750,
    totalTeachers: 42,
    totalStaff: 12,
    totalWorkers: 15,
    monthlyRevenue: 1980000,
    monthlyExpenses: 1230000,
    attendanceRate: 94.8,
    feeCollectionRate: 91.5,
    facilities: [
      "Montessori Activity Rooms",
      "Splash Pool & Sand Pit",
      "Story & Rhyme Hall",
      "Children's Play Park",
      "Paediatric Health Room",
    ],
    departments: [
      { name: "Pre-Primary (Nursery–UKG)", head: "Mrs. Lakshmi Venkat", staffCount: 22 },
      { name: "Primary Foundation (1–2)", head: "Ms. Pooja Mehta", staffCount: 20 },
    ],
    color: "#10b981", // Emerald
    udiseCode: "27200500211",
    affiliationNumber: "1131012",
    board: "CBSE",
    createdAt: "2021-09-01T00:00:00.000Z",
    updatedAt: "2026-08-28T09:00:00.000Z",
  },
  {
    id: "br-green-04",
    name: "Green Valley International School",
    code: "GVI-04",
    tagline: "ICSE Campus — Whitefield, Bengaluru",
    type: "International",
    principalName: "Mrs. Lakshmi Venkat, M.A., B.Ed.",
    principalEmail: "l.venkat@greenvalley.edu.in",
    principalPhone: "+91 98450 67890",
    address: "220 Whitefield–Hoskote Road",
    city: "Bengaluru",
    state: "Karnataka",
    postalCode: "560066",
    phone: "+91 80 2845 8000",
    email: "admissions@greenvalley.edu.in",
    website: "https://greenvalley.edu.in",
    establishedYear: 2012,
    status: "ACTIVE",
    totalStudents: 1180,
    capacity: 1500,
    totalTeachers: 72,
    totalStaff: 20,
    totalWorkers: 26,
    monthlyRevenue: 6190000,
    monthlyExpenses: 3890000,
    attendanceRate: 95.9,
    feeCollectionRate: 95.3,
    facilities: [
      "ICSE Science Park",
      "Herbal & Kitchen Garden",
      "Basketball & Badminton Courts",
      "Auditorium (600-seat)",
      "Language Lab (English/Kannada/Hindi)",
    ],
    departments: [
      { name: "Sciences", head: "Dr. Deepa Nair", staffCount: 30 },
      { name: "Languages (Eng/Kan/Hin)", head: "Mrs. Kavitha Subramaniam", staffCount: 22 },
      { name: "Social Science & EVS", head: "Mr. Suresh Pillai", staffCount: 20 },
    ],
    color: "#059669", // Dark Green
    udiseCode: "29280100115",
    affiliationNumber: "KA-214",
    board: "ICSE",
    createdAt: "2020-05-18T00:00:00.000Z",
    updatedAt: "2026-08-30T16:20:00.000Z",
  },
  {
    id: "br-horizon-05",
    name: "Horizon High & College Prep",
    code: "HZN-05",
    tagline: "Secondary & Sr. Secondary — Malviya Nagar, Jaipur",
    type: "High School",
    principalName: "Mr. Ramesh Agarwal, M.Com., B.Ed.",
    principalEmail: "r.agarwal@horizon.edu.in",
    principalPhone: "+91 98290 34567",
    address: "890 Calgeri Marg, Malviya Nagar",
    city: "Jaipur",
    state: "Rajasthan",
    postalCode: "302017",
    phone: "+91 141 252 9000",
    email: "office@horizon.edu.in",
    website: "https://horizon.edu.in",
    establishedYear: 2014,
    status: "EXPANDING",
    totalStudents: 980,
    capacity: 1200,
    totalTeachers: 60,
    totalStaff: 18,
    totalWorkers: 22,
    monthlyRevenue: 4230000,
    monthlyExpenses: 2710000,
    attendanceRate: 95.2,
    feeCollectionRate: 93.7,
    facilities: [
      "JEE/NEET Foundation Cell",
      "Commerce & Accountancy Lab",
      "Career Counselling Cell",
      "NCC & Scouts Troop",
      "Gym & Kho-Kho Ground",
    ],
    departments: [
      { name: "Science (PCM/PCB)", head: "Mr. Amit Shah", staffCount: 24 },
      { name: "Commerce & Humanities", head: "Mrs. Rekha Gupta", staffCount: 20 },
      { name: "English & Hindi", head: "Mrs. Sunita Rao", staffCount: 16 },
    ],
    color: "#f59e0b", // Amber
    udiseCode: "08260100208",
    affiliationNumber: "1730567",
    board: "CBSE",
    createdAt: "2020-11-20T00:00:00.000Z",
    updatedAt: "2026-08-31T11:45:00.000Z",
  },
  {
    id: "br-river-06",
    name: "Riverdale Arts & Sports Academy",
    code: "RVD-06",
    tagline: "Sports & Kala Utsav Wing — Ahmedabad",
    type: "Arts & Sports",
    principalName: "Mr. Arjun Desai, M.P.Ed.",
    principalEmail: "a.desai@riverdale.edu.in",
    principalPhone: "+91 98980 22334",
    address: "310 Sabarmati Riverfront West",
    city: "Ahmedabad",
    state: "Gujarat",
    postalCode: "380061",
    phone: "+91 79 2760 0000",
    email: "arts.sports@riverdale.edu.in",
    website: "https://riverdale.edu.in",
    establishedYear: 2019,
    status: "ACTIVE",
    totalStudents: 740,
    capacity: 900,
    totalTeachers: 48,
    totalStaff: 14,
    totalWorkers: 20,
    monthlyRevenue: 2310000,
    monthlyExpenses: 1540000,
    attendanceRate: 96.1,
    feeCollectionRate: 92.4,
    facilities: [
      "Open-Air Theatre",
      "Music & Classical Dance Halls",
      "Art & Craft Studio",
      "Cricket Turf Wicket",
      "Skating Rink & Gymnastics Hall",
    ],
    departments: [
      { name: "Visual & Performing Arts", head: "Ms. Neha Kapoor", staffCount: 18 },
      { name: "Music & Dance", head: "Mr. Ravi Shankar", staffCount: 16 },
      { name: "Athletics & Games", head: "Mr. Vikram Singh", staffCount: 14 },
    ],
    color: "#ec4899", // Rose Pink
    udiseCode: "24070100319",
    affiliationNumber: "1030891",
    board: "CBSE",
    createdAt: "2022-02-14T00:00:00.000Z",
    updatedAt: "2026-09-01T15:00:00.000Z",
  },
  {
    id: "br-apex-college-07",
    name: "Apex Institute of Technology & Science",
    code: "AITS-07",
    tagline: "Engineering & Degree College — SPPU Affiliated, Pune",
    type: "College",
    principalName: "Dr. Rajeev Kulkarni, Ph.D. (IIT-B)",
    principalEmail: "director@aits.edu.in",
    principalPhone: "+91 98230 44567",
    address: "Survey No. 88, Hinjewadi Phase-1, Near Metro",
    city: "Pune",
    state: "Maharashtra",
    postalCode: "411057",
    phone: "+91 20 6670 9000",
    email: "admissions@aits.edu.in",
    website: "https://aits.edu.in",
    establishedYear: 2012,
    status: "ACTIVE",
    totalStudents: 1860,
    capacity: 2400,
    totalTeachers: 124,
    totalStaff: 46,
    totalWorkers: 38,
    monthlyRevenue: 12850000,
    monthlyExpenses: 8920000,
    attendanceRate: 91.8,
    feeCollectionRate: 89.4,
    facilities: [
      "NBA Accredited Labs (CSE/ECE/Mech)",
      "Central Library (35k+ books, Digital ELibrary)",
      "Boys & Girls Hostel (600 beds)",
      "Industry Incubation Centre & T&P Cell",
      "Sports Complex & Gymkhana",
      "CCTV + Biometric + Campus ERP",
      "Canteen & Food Court (FSSAI)",
      "EV Bus Fleet + Parking",
    ],
    departments: [
      { name: "Computer Engineering (CSE)", head: "Dr. Priya Menon", staffCount: 32 },
      { name: "Electronics & Telecommunication", head: "Dr. Deepa Nair", staffCount: 24 },
      { name: "Mechanical Engineering", head: "Prof. Amit Shah", staffCount: 22 },
      { name: "Commerce & Management (BBA/MBA)", head: "Dr. Rekha Gupta", staffCount: 18 },
      { name: "Science (B.Sc/BCA)", head: "Dr. Kavitha Subramaniam", staffCount: 28 },
    ],
    color: "#0ea5e9",
    udiseCode: "27250500707",
    affiliationNumber: "SPPU-ENG-1147",
    board: "SPPU (Pune)",
    createdAt: "2012-06-15T00:00:00.000Z",
    updatedAt: "2026-09-05T10:00:00.000Z",
  },
];
