import { ClassRoom } from "@/types";

export const initialClasses: ClassRoom[] = [
  {
    id: "cls-g10",
    name: "Grade 10",
    gradeLevel: 10,
    category: "High School",
    branchId: "br-apex-01",
    branchName: "Apex Global Campus",
    totalStudents: 140,
    capacity: 160,
    description: "CBSE Class 10 with board-pattern tests, NTSE and Olympiad tracks.",
    sections: [
      {
        id: "sec-g10-a",
        name: "Section A (STEM Honors)",
        roomNumber: "Room 301",
        classTeacherId: "tch-01",
        classTeacherName: "Mrs. Sunita Rao",
        classTeacherAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100",
        studentCount: 35,
        capacity: 40,
      },
      {
        id: "sec-g10-b",
        name: "Section B (Humanities & Social)",
        roomNumber: "Room 302",
        classTeacherId: "tch-02",
        classTeacherName: "Mr. Rajesh Kulkarni",
        classTeacherAvatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100",
        studentCount: 36,
        capacity: 40,
      },
      {
        id: "sec-g10-c",
        name: "Section C (Commerce & Computing)",
        roomNumber: "Room 303",
        classTeacherId: "tch-03",
        classTeacherName: "Ms. Priya Menon",
        studentCount: 34,
        capacity: 40,
      },
      {
        id: "sec-g10-arts",
        name: "Section D (Arts & Media)",
        roomNumber: "Studio 105",
        classTeacherId: "tch-06",
        classTeacherName: "Ms. Neha Kapoor",
        studentCount: 35,
        capacity: 40,
      },
    ],
    subjects: [
      { id: "sub-101", name: "Mathematics", code: "MATH-10", teacherId: "tch-01", teacherName: "Mrs. Sunita Rao", weeklyPeriods: 6 },
      { id: "sub-102", name: "Science", code: "SCI-10", teacherId: "tch-02", teacherName: "Mr. Rajesh Kulkarni", weeklyPeriods: 5 },
      { id: "sub-103", name: "Computer Science", code: "CS-10", teacherId: "tch-03", teacherName: "Ms. Priya Menon", weeklyPeriods: 4 },
      { id: "sub-104", name: "English", code: "ENG-10", teacherId: "tch-05", teacherName: "Mrs. Kavitha Subramaniam", weeklyPeriods: 5 },
      { id: "sub-105", name: "Art Education", code: "ART-10", teacherId: "tch-06", teacherName: "Ms. Neha Kapoor", weeklyPeriods: 4 },
    ],
  },
  {
    id: "cls-g9",
    name: "Grade 9",
    gradeLevel: 9,
    category: "High School",
    branchId: "br-west-02",
    branchName: "Westside STEM & Innovation Academy",
    totalStudents: 110,
    capacity: 120,
    description: "CBSE Class 9 foundation year with Atal Lab and coding club.",
    sections: [
      {
        id: "sec-g9-a",
        name: "Section Alpha (Robotics Core)",
        roomNumber: "Tech Lab 12",
        classTeacherId: "tch-03",
        classTeacherName: "Ms. Priya Menon",
        studentCount: 38,
        capacity: 40,
      },
      {
        id: "sec-g9-b",
        name: "Section Beta (Applied Bio-Tech)",
        roomNumber: "Bio Lab 14",
        classTeacherId: "tch-02",
        classTeacherName: "Mr. Rajesh Kulkarni",
        studentCount: 36,
        capacity: 40,
      },
      {
        id: "sec-g9-c",
        name: "Section Gamma (Maths Prep)",
        roomNumber: "Room 108",
        classTeacherId: "tch-01",
        classTeacherName: "Mrs. Sunita Rao",
        studentCount: 36,
        capacity: 40,
      },
    ],
    subjects: [
      { id: "sub-901", name: "Mathematics", code: "MATH-09", teacherId: "tch-01", teacherName: "Mrs. Sunita Rao", weeklyPeriods: 6 },
      { id: "sub-902", name: "Science", code: "SCI-09", teacherId: "tch-03", teacherName: "Ms. Priya Menon", weeklyPeriods: 5 },
      { id: "sub-903", name: "Social Science", code: "SST-09", teacherId: "tch-02", teacherName: "Mr. Rajesh Kulkarni", weeklyPeriods: 5 },
    ],
  },
  {
    id: "cls-g11",
    name: "Grade 11",
    gradeLevel: 11,
    category: "Senior Secondary",
    branchId: "br-green-04",
    branchName: "Green Valley International School",
    totalStudents: 125,
    capacity: 150,
    description: "ICSE Class 11 — Science and Commerce streams with JEE/NEET foundation.",
    sections: [
      {
        id: "sec-g11-ib",
        name: "IB Diploma Cohort 1",
        roomNumber: "IB Wing 201",
        classTeacherId: "tch-05",
        classTeacherName: "Mrs. Kavitha Subramaniam",
        studentCount: 32,
        capacity: 35,
      },
      {
        id: "sec-g11-a",
        name: "AP STEM Scholars",
        roomNumber: "Hall 401",
        classTeacherId: "tch-02",
        classTeacherName: "Mr. Rajesh Kulkarni",
        studentCount: 34,
        capacity: 40,
      },
    ],
    subjects: [
      { id: "sub-1101", name: "English", code: "ENG-11", teacherId: "tch-05", teacherName: "Mrs. Kavitha Subramaniam", weeklyPeriods: 6 },
      { id: "sub-1102", name: "Physics", code: "PHY-11", teacherId: "tch-02", teacherName: "Mr. Rajesh Kulkarni", weeklyPeriods: 6 },
      { id: "sub-1103", name: "Mathematics", code: "MATH-11", teacherId: "tch-01", teacherName: "Mrs. Sunita Rao", weeklyPeriods: 6 },
    ],
  },
  {
    id: "cls-g12",
    name: "Grade 12",
    gradeLevel: 12,
    category: "Senior Secondary",
    branchId: "br-apex-01",
    branchName: "Apex Global Campus",
    totalStudents: 130,
    capacity: 150,
    description: "Board year with pre-boards, career counselling and remedial support.",
    sections: [
      {
        id: "sec-g12-a",
        name: "Section A (Ivy Placement)",
        roomNumber: "Senior Quad 1",
        classTeacherId: "tch-01",
        classTeacherName: "Mrs. Sunita Rao",
        studentCount: 34,
        capacity: 38,
      },
      {
        id: "sec-g12-ib",
        name: "IB Diploma Year 2",
        roomNumber: "Senior Quad 2",
        classTeacherId: "tch-05",
        classTeacherName: "Mrs. Kavitha Subramaniam",
        studentCount: 30,
        capacity: 35,
      },
    ],
    subjects: [
      { id: "sub-1201", name: "Mathematics", code: "MATH-12", teacherId: "tch-01", teacherName: "Mrs. Sunita Rao", weeklyPeriods: 6 },
      { id: "sub-1202", name: "Physics", code: "PHY-12", teacherId: "tch-02", teacherName: "Mr. Rajesh Kulkarni", weeklyPeriods: 6 },
      { id: "sub-1203", name: "Chemistry", code: "CHEM-12", teacherId: "tch-01", teacherName: "Mrs. Sunita Rao", weeklyPeriods: 4 },
    ],
  },
  {
    id: "cls-mont",
    name: "Montessori Primary",
    gradeLevel: 0,
    category: "Kindergarten",
    branchId: "br-north-03",
    branchName: "Northpoint Montessori & Prep",
    totalStudents: 85,
    capacity: 100,
    description: "Balvatika / pre-primary (ages 3–6) with phonics and activity corners.",
    sections: [
      {
        id: "sec-mont-a",
        name: "Sunflowers Studio",
        roomNumber: "Garden Studio 1",
        classTeacherId: "tch-04",
        classTeacherName: "Mrs. Lakshmi Venkat",
        studentCount: 22,
        capacity: 25,
      },
      {
        id: "sec-mont-b",
        name: "Bluebells Studio",
        roomNumber: "Garden Studio 2",
        classTeacherId: "tch-04",
        classTeacherName: "Mrs. Lakshmi Venkat",
        studentCount: 20,
        capacity: 25,
      },
    ],
    subjects: [
      { id: "sub-001", name: "Phonics & Language Readiness", code: "MONT-LANG", teacherId: "tch-04", teacherName: "Mrs. Lakshmi Venkat", weeklyPeriods: 10 },
      { id: "sub-002", name: "Number Readiness & Play", code: "MONT-NUM", teacherId: "tch-04", teacherName: "Mrs. Lakshmi Venkat", weeklyPeriods: 10 },
    ],
  },
];
