import { ClassRoom } from "@/types";

export const initialClasses: ClassRoom[] = [
  {
    id: "cls-g10",
    name: "Grade 10",
    gradeLevel: 10,
    category: "High School",
    branchId: "br-apex-01",
    branchName: "Apex Global Campus",
    totalStudents: 140,
    capacity: 160,
    description: "Sophomore secondary curriculum with honors & pre-AP tracks.",
    sections: [
      {
        id: "sec-g10-a",
        name: "Section A (STEM Honors)",
        roomNumber: "Room 301",
        classTeacherId: "tch-01",
        classTeacherName: "Dr. Sarah Lin",
        classTeacherAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100",
        studentCount: 35,
        capacity: 40,
      },
      {
        id: "sec-g10-b",
        name: "Section B (Humanities & Social)",
        roomNumber: "Room 302",
        classTeacherId: "tch-02",
        classTeacherName: "Prof. Marcus Brody",
        classTeacherAvatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100",
        studentCount: 36,
        capacity: 40,
      },
      {
        id: "sec-g10-c",
        name: "Section C (Commerce & Computing)",
        roomNumber: "Room 303",
        classTeacherId: "tch-03",
        classTeacherName: "Elena Rostova, M.S.",
        studentCount: 34,
        capacity: 40,
      },
      {
        id: "sec-g10-arts",
        name: "Section D (Arts & Media)",
        roomNumber: "Studio 105",
        classTeacherId: "tch-06",
        classTeacherName: "Camilla Rossi, M.F.A.",
        studentCount: 35,
        capacity: 40,
      },
    ],
    subjects: [
      { id: "sub-101", name: "Honors Mathematics", code: "MATH-10H", teacherId: "tch-01", teacherName: "Dr. Sarah Lin", weeklyPeriods: 6 },
      { id: "sub-102", name: "General Physics", code: "PHYS-10", teacherId: "tch-02", teacherName: "Prof. Marcus Brody", weeklyPeriods: 5 },
      { id: "sub-103", name: "Computer Science Principles", code: "CS-10", teacherId: "tch-03", teacherName: "Elena Rostova", weeklyPeriods: 4 },
      { id: "sub-104", name: "World Literature", code: "LIT-10", teacherId: "tch-05", teacherName: "Dr. Nigel Ross", weeklyPeriods: 5 },
      { id: "sub-105", name: "Studio Art & Design", code: "ART-10", teacherId: "tch-06", teacherName: "Camilla Rossi", weeklyPeriods: 4 },
    ],
  },
  {
    id: "cls-g9",
    name: "Grade 9",
    gradeLevel: 9,
    category: "High School",
    branchId: "br-west-02",
    branchName: "Westside STEM & Innovation Academy",
    totalStudents: 110,
    capacity: 120,
    description: "Freshman high school year with robotics foundation.",
    sections: [
      {
        id: "sec-g9-a",
        name: "Section Alpha (Robotics Core)",
        roomNumber: "Tech Lab 12",
        classTeacherId: "tch-03",
        classTeacherName: "Elena Rostova, M.S.",
        studentCount: 38,
        capacity: 40,
      },
      {
        id: "sec-g9-b",
        name: "Section Beta (Applied Bio-Tech)",
        roomNumber: "Bio Lab 14",
        classTeacherId: "tch-02",
        classTeacherName: "Prof. Marcus Brody",
        studentCount: 36,
        capacity: 40,
      },
      {
        id: "sec-g9-c",
        name: "Section Gamma (Calculus Prep)",
        roomNumber: "Room 108",
        classTeacherId: "tch-01",
        classTeacherName: "Dr. Sarah Lin",
        studentCount: 36,
        capacity: 40,
      },
    ],
    subjects: [
      { id: "sub-901", name: "Integrated Algebra & Geometry", code: "MATH-09", teacherId: "tch-01", teacherName: "Dr. Sarah Lin", weeklyPeriods: 6 },
      { id: "sub-902", name: "Introductory Robotics & Coding", code: "ROB-09", teacherId: "tch-03", teacherName: "Elena Rostova", weeklyPeriods: 5 },
      { id: "sub-903", name: "Biological Foundations", code: "BIO-09", teacherId: "tch-02", teacherName: "Prof. Marcus Brody", weeklyPeriods: 5 },
    ],
  },
  {
    id: "cls-g11",
    name: "Grade 11",
    gradeLevel: 11,
    category: "Senior Secondary",
    branchId: "br-green-04",
    branchName: "Green Valley International School",
    totalStudents: 125,
    capacity: 150,
    description: "IB Diploma Programme Year 1 & AP Capstone.",
    sections: [
      {
        id: "sec-g11-ib",
        name: "IB Diploma Cohort 1",
        roomNumber: "IB Wing 201",
        classTeacherId: "tch-05",
        classTeacherName: "Dr. Nigel Ross",
        studentCount: 32,
        capacity: 35,
      },
      {
        id: "sec-g11-a",
        name: "AP STEM Scholars",
        roomNumber: "Hall 401",
        classTeacherId: "tch-02",
        classTeacherName: "Prof. Marcus Brody",
        studentCount: 34,
        capacity: 40,
      },
    ],
    subjects: [
      { id: "sub-1101", name: "IB English Literature HL", code: "IB-LIT-11", teacherId: "tch-05", teacherName: "Dr. Nigel Ross", weeklyPeriods: 6 },
      { id: "sub-1102", name: "AP Physics 1", code: "AP-PHYS-1", teacherId: "tch-02", teacherName: "Prof. Marcus Brody", weeklyPeriods: 6 },
      { id: "sub-1103", name: "AP Calculus AB", code: "AP-CALC-AB", teacherId: "tch-01", teacherName: "Dr. Sarah Lin", weeklyPeriods: 6 },
    ],
  },
  {
    id: "cls-g12",
    name: "Grade 12",
    gradeLevel: 12,
    category: "Senior Secondary",
    branchId: "br-apex-01",
    branchName: "Apex Global Campus",
    totalStudents: 130,
    capacity: 150,
    description: "Graduating senior class with university prep and college counseling.",
    sections: [
      {
        id: "sec-g12-a",
        name: "Section A (Ivy Placement)",
        roomNumber: "Senior Quad 1",
        classTeacherId: "tch-01",
        classTeacherName: "Dr. Sarah Lin",
        studentCount: 34,
        capacity: 38,
      },
      {
        id: "sec-g12-ib",
        name: "IB Diploma Year 2",
        roomNumber: "Senior Quad 2",
        classTeacherId: "tch-05",
        classTeacherName: "Dr. Nigel Ross",
        studentCount: 30,
        capacity: 35,
      },
    ],
    subjects: [
      { id: "sub-1201", name: "AP Calculus BC", code: "AP-CALC-BC", teacherId: "tch-01", teacherName: "Dr. Sarah Lin", weeklyPeriods: 6 },
      { id: "sub-1202", name: "AP Physics C", code: "AP-PHYS-C", teacherId: "tch-02", teacherName: "Prof. Marcus Brody", weeklyPeriods: 6 },
      { id: "sub-1203", name: "Theory of Knowledge (TOK)", code: "IB-TOK-12", teacherId: "tch-05", teacherName: "Dr. Nigel Ross", weeklyPeriods: 4 },
    ],
  },
  {
    id: "cls-mont",
    name: "Montessori Primary",
    gradeLevel: 0,
    category: "Kindergarten",
    branchId: "br-north-03",
    branchName: "Northpoint Montessori & Prep",
    totalStudents: 85,
    capacity: 100,
    description: "Multi-age early childhood classroom (ages 3–6) focusing on self-discovery.",
    sections: [
      {
        id: "sec-mont-a",
        name: "Sunflowers Studio",
        roomNumber: "Garden Studio 1",
        classTeacherId: "tch-04",
        classTeacherName: "Annette Dupont, M.Ed.",
        studentCount: 22,
        capacity: 25,
      },
      {
        id: "sec-mont-b",
        name: "Bluebells Studio",
        roomNumber: "Garden Studio 2",
        classTeacherId: "tch-04",
        classTeacherName: "Annette Dupont, M.Ed.",
        studentCount: 20,
        capacity: 25,
      },
    ],
    subjects: [
      { id: "sub-001", name: "Sensorial Explorations", code: "MONT-SNS", teacherId: "tch-04", teacherName: "Annette Dupont", weeklyPeriods: 10 },
      { id: "sub-002", name: "Early Language Immersion", code: "MONT-LANG", teacherId: "tch-04", teacherName: "Annette Dupont", weeklyPeriods: 10 },
    ],
  },
];
