import {
  AdmissionFunnelPoint,
  AttendanceTrendPoint,
  BiometricDevice,
  FeeCollectionPoint,
  Notice,
  ActivityLog,
  UserSession,
} from "@/types";

export const defaultUserSession: UserSession = {
  id: "usr-admin-01",
  name: "Dr. Alexander Wright",
  email: "alexander.wright@schools-group.org",
  avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
  role: "SUPER_ADMIN",
  branchId: "all",
  roleLabel: "Super Admin (Global ERP)",
  title: "Group Director & Chief Academic Officer",
};

export const demoRolesList: { role: UserSession["role"]; label: string; description: string; branchId: string }[] = [
  {
    role: "SUPER_ADMIN",
    label: "Super Admin (Global View)",
    description: "Full multi-branch oversight, financial controls & system settings",
    branchId: "all",
  },
  {
    role: "PRINCIPAL",
    label: "Principal (Apex Campus)",
    description: "Campus-wide academic, teacher & student administration",
    branchId: "br-apex-01",
  },
  {
    role: "TEACHER",
    label: "Senior Teacher (Westside STEM)",
    description: "Attendance, assignments, grade entry & classroom portal",
    branchId: "br-west-02",
  },
  {
    role: "ACCOUNTANT",
    label: "Chief Accountant (Group Finance)",
    description: "Invoicing, fee collections, payroll & expense ledger",
    branchId: "all",
  },
  {
    role: "HR_MANAGER",
    label: "HR Director (Staff & Workers)",
    description: "Teacher recruitment, staff leaves, worker shifts & biometric logs",
    branchId: "all",
  },
  {
    role: "PARENT",
    label: "Parent Portal Demo",
    description: "Child attendance, fee payments, report cards & teacher messages",
    branchId: "br-green-04",
  },
  {
    role: "STUDENT",
    label: "Student Portal Demo",
    description: "Timetable, homework, exam results & library access",
    branchId: "br-horizon-05",
  },
];

export const initialAttendanceTrends: AttendanceTrendPoint[] = [
  { date: "Aug 05", students: 95.2, teachers: 98.4, workers: 94.1 },
  { date: "Aug 09", students: 96.0, teachers: 97.9, workers: 95.3 },
  { date: "Aug 13", students: 94.7, teachers: 96.8, workers: 93.8 },
  { date: "Aug 17", students: 96.8, teachers: 99.1, workers: 96.2 },
  { date: "Aug 21", students: 95.4, teachers: 98.0, workers: 94.9 },
  { date: "Aug 25", students: 97.3, teachers: 98.7, workers: 96.5 },
  { date: "Aug 29", students: 96.1, teachers: 97.5, workers: 95.0 },
  { date: "Sep 02", students: 96.5, teachers: 98.9, workers: 95.8 },
];

export const initialFeeCollections: FeeCollectionPoint[] = [
  { month: "Apr", collected: 1320000, target: 1400000, pending: 80000 },
  { month: "May", collected: 1410000, target: 1400000, pending: 65000 },
  { month: "Jun", collected: 1380000, target: 1450000, pending: 95000 },
  { month: "Jul", collected: 1490000, target: 1500000, pending: 72000 },
  { month: "Aug", collected: 1520000, target: 1550000, pending: 58000 },
  { month: "Sep (MTD)", collected: 620000, target: 1550000, pending: 930000 },
];

export const initialAdmissionFunnel: AdmissionFunnelPoint[] = [
  { stage: "Inquiries", count: 1840, percentage: 100, fill: "#3b82f6" },
  { stage: "Applications", count: 1420, percentage: 77, fill: "#6366f1" },
  { stage: "Assessment/Exam", count: 1100, percentage: 60, fill: "#8b5cf6" },
  { stage: "Interview", count: 890, percentage: 48, fill: "#ec4899" },
  { stage: "Approved / Enrolled", count: 680, percentage: 37, fill: "#10b981" },
];

export const initialNotices: Notice[] = [
  {
    id: "not-01",
    title: "Annual Science & Innovation Expo 2026",
    content: "All campuses are requested to finalize student STEM project submissions by September 15. The grand inter-branch showcase will be hosted at Westside STEM Academy.",
    date: "2026-09-02T08:30:00.000Z",
    priority: "HIGH",
    branchId: "all",
    category: "Academic",
    author: "Academics Council",
    targetAudience: ["ALL", "TEACHERS", "PARENTS", "STUDENTS"],
  },
  {
    id: "not-02",
    title: "Biometric Device Firmware Upgrade & Network Maintenance",
    content: "Scheduled synchronization and maintenance for terminal gateways across Apex Global and Green Valley on Friday from 10:00 PM to 12:00 AM.",
    date: "2026-09-01T14:00:00.000Z",
    priority: "URGENT",
    branchId: "br-apex-01",
    category: "Administrative",
    author: "IT Infrastructure Team",
    targetAudience: ["STAFF"],
  },
  {
    id: "not-03",
    title: "Term 1 Tuition Fee Installment Due Date",
    content: "Gentle reminder to parents: Term 1 fee installments are due on September 10. Online portal payments and receipt generation are active 24/7.",
    date: "2026-08-30T10:15:00.000Z",
    priority: "NORMAL",
    branchId: "all",
    category: "Administrative",
    author: "Central Accounts Office",
    targetAudience: ["PARENTS"],
  },
  {
    id: "not-04",
    title: "Montessori Grandparents Day Celebration",
    content: "Northpoint campus cordially invites all grandparents for an open garden tea and musical performance this Saturday morning.",
    date: "2026-08-28T09:00:00.000Z",
    priority: "NORMAL",
    branchId: "br-north-03",
    category: "Event",
    author: "Clara Higgins (Principal)",
    targetAudience: ["PARENTS", "STUDENTS"],
  },
];

export const initialActivities: ActivityLog[] = [
  {
    id: "act-01",
    user: {
      name: "Sarah Lin",
      avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100",
      role: "Faculty Head",
    },
    action: "UPDATE",
    module: "Classes",
    entityName: "Grade 10 Mathematics Syllabus & Test Rubric",
    entityId: "cls-math-10",
    timestamp: "2026-09-02T09:15:00.000Z",
    branchId: "br-apex-01",
    branchName: "Apex Global Campus",
    details: "Uploaded Midterm sample test papers and updated grading criteria.",
    status: "SUCCESS",
  },
  {
    id: "act-02",
    user: {
      name: "Marcus Vance",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100",
      role: "Admissions Officer",
    },
    action: "APPROVE",
    module: "Admissions",
    entityName: "Application #ADM-2026-908 (Liam Chen)",
    entityId: "adm-908",
    timestamp: "2026-09-02T08:45:00.000Z",
    branchId: "br-west-02",
    branchName: "Westside STEM & Innovation Academy",
    details: "Approved Grade 9 STEM track admission following interview clearance.",
    status: "SUCCESS",
  },
  {
    id: "act-03",
    user: {
      name: "Hannah Montgomery",
      avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100",
      role: "Accountant",
    },
    action: "PAYMENT",
    module: "Fees",
    entityName: "Receipt #RCP-44910 ($2,450.00)",
    entityId: "fee-44910",
    timestamp: "2026-09-02T08:20:00.000Z",
    branchId: "br-green-04",
    branchName: "Green Valley International",
    details: "Processed Term 1 Tuition & Transport fee via Stripe Mock Gateway.",
    status: "SUCCESS",
  },
  {
    id: "act-04",
    user: {
      name: "System Gateway",
      avatar: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=100",
      role: "Biometric Sync Service",
    },
    action: "SYNC",
    module: "Biometric",
    entityName: "ZKTeco Terminal Cluster #4",
    entityId: "bio-term-04",
    timestamp: "2026-09-02T08:00:00.000Z",
    branchId: "br-horizon-05",
    branchName: "Horizon High",
    details: "Synced 1,024 morning check-in fingerprint/RFID punch records.",
    status: "SUCCESS",
  },
  {
    id: "act-05",
    user: {
      name: "Terrell Owens",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100",
      role: "Transport Supervisor",
    },
    action: "UPDATE",
    module: "Transport",
    entityName: "Bus Route #08 (Downtown Express)",
    entityId: "rt-08",
    timestamp: "2026-09-01T17:30:00.000Z",
    branchId: "br-river-06",
    branchName: "Riverdale Arts & Sports Academy",
    details: "Added new pickup stop at Riverside Park Station with GPS live simulator.",
    status: "SUCCESS",
  },
];

export const initialBiometricDevices: BiometricDevice[] = [
  {
    id: "dev-01",
    name: "Main Gate Turnstile A (Face + Fingerprint)",
    location: "Main Entrance Gate",
    branchId: "br-apex-01",
    branchName: "Apex Global Campus",
    ipAddress: "192.168.10.21",
    status: "ONLINE",
    lastSync: "2026-09-02T09:12:00.000Z",
    enrolledUsers: 1538,
    batteryLevel: 98,
  },
  {
    id: "dev-02",
    name: "Faculty & Staff Lounge Reader",
    location: "Admin Block - 2nd Floor",
    branchId: "br-apex-01",
    branchName: "Apex Global Campus",
    ipAddress: "192.168.10.22",
    status: "ONLINE",
    lastSync: "2026-09-02T09:14:00.000Z",
    enrolledUsers: 142,
    batteryLevel: 100,
  },
  {
    id: "dev-03",
    name: "STEM Wing Biometric Terminal",
    location: "Robotics & Labs Entrance",
    branchId: "br-west-02",
    branchName: "Westside STEM",
    ipAddress: "192.168.20.15",
    status: "ONLINE",
    lastSync: "2026-09-02T09:10:00.000Z",
    enrolledUsers: 920,
    batteryLevel: 94,
  },
  {
    id: "dev-04",
    name: "Transport Depot & Driver Punch Box",
    location: "Central Fleet Garage",
    branchId: "all",
    branchName: "Global Fleet Depot",
    ipAddress: "192.168.50.8",
    status: "SYNCING",
    lastSync: "2026-09-02T09:05:00.000Z",
    enrolledUsers: 110,
    batteryLevel: 88,
  },
];
