import { CalendarEvent, EventVenue } from "@/types";

export const initialEventVenues: EventVenue[] = [
  { id: "ven-001", name: "Main Auditorium", address: "Block A, Ground Floor", capacity: 500, branchId: "br-apex-01", branchName: "Apex Global Campus", facilities: ["Stage", "Sound System", "Projector", "AC", "Green Room"] },
  { id: "ven-002", name: "Conference Hall", address: "Admin Block, 2nd Floor", capacity: 80, branchId: "br-apex-01", branchName: "Apex Global Campus", facilities: ["Projector", "Video Conferencing", "Whiteboard", "AC"] },
  { id: "ven-003", name: "Sports Ground", address: "Outdoor Area, East Wing", capacity: 1000, branchId: "br-apex-01", branchName: "Apex Global Campus", facilities: ["Track", "Football Field", "Basketball Court", "Spectator Stands"] },
  { id: "ven-004", name: "Seminar Hall", address: "Block C, 1st Floor", capacity: 120, branchId: "br-west-02", branchName: "Westside STEM & Innovation Academy", facilities: ["Projector", "Sound System", "AC", "Recording Setup"] },
  { id: "ven-005", name: "Garden Studio", address: "Montessori Wing", capacity: 40, branchId: "br-north-03", branchName: "Northpoint Montessori & Prep", facilities: ["Open Air", "Art Supplies", "Natural Lighting"] },
];

export const initialCalendarEvents: CalendarEvent[] = [
  {
    id: "evt-001",
    title: "Annual Day Celebration 2026",
    description: "The 15th Annual Day Celebration of Apex Global Campus will feature cultural performances by students, the Annual Awards ceremony, and the inauguration of the new STEM Innovation Wing. Chief Guest: Dr. A.P.J. Digital Memorial Foundation Director.",
    category: "CULTURAL",
    status: "UPCOMING",
    visibility: "PUBLIC",
    branchId: "br-apex-01",
    branchName: "Apex Global Campus",
    venueId: "ven-001",
    venueName: "Main Auditorium",
    venueAddress: "Block A, Ground Floor",
    startDate: "2026-09-15",
    endDate: "2026-09-15",
    startTime: "17:00",
    endTime: "21:00",
    allDay: false,
    organizer: "Principal Dr. Meera Kapoor",
    organizerRole: "PRINCIPAL",
    participantCount: 380,
    maxParticipants: 500,
    participantType: "ALL",
    reminders: [
      { id: "rem-001", eventId: "evt-001", remindBefore: 1440, channel: "IN_APP", sent: true },
      { id: "rem-002", eventId: "evt-001", remindBefore: 60, channel: "SMS", sent: false },
    ],
    tags: ["annual-day", "cultural", "awards"],
    createdAt: "2026-08-15T09:00:00Z",
    updatedAt: "2026-08-25T10:00:00Z",
  },
  {
    id: "evt-002",
    title: "Parent-Teacher Meeting — Mid-Term",
    description: "Discuss mid-term examination results with class teachers and subject teachers. Parents can book 15-minute slots. Report cards will be distributed. Bring your child's school ID.",
    category: "MEETING",
    status: "UPCOMING",
    visibility: "PARENTS_ONLY",
    branchId: "br-apex-01",
    branchName: "Apex Global Campus",
    venueId: "ven-002",
    venueName: "Conference Hall",
    venueAddress: "Admin Block, 2nd Floor",
    startDate: "2026-09-08",
    endDate: "2026-09-08",
    startTime: "09:00",
    endTime: "13:00",
    allDay: false,
    organizer: "Vice Principal Mr. Arjun Desai",
    organizerRole: "PRINCIPAL",
    participantCount: 210,
    maxParticipants: 250,
    participantType: "PARENTS",
    classIds: ["cls-g10", "cls-g11", "cls-g12"],
    classNames: ["Grade 10", "Grade 11", "Grade 12"],
    reminders: [
      { id: "rem-003", eventId: "evt-002", remindBefore: 10080, channel: "EMAIL", sent: true },
      { id: "rem-004", eventId: "evt-002", remindBefore: 1440, channel: "SMS", sent: false },
    ],
    tags: ["ptm", "results", "parents"],
    createdAt: "2026-08-28T10:00:00Z",
    updatedAt: "2026-08-28T10:00:00Z",
  },
  {
    id: "evt-003",
    title: "Science Exhibition — Call for Projects",
    description: "Inter-School Science Exhibition showcasing student projects in Physics, Chemistry, Biology, Computer Science, and Environmental Science. Open to public viewing from 10 AM. Judging from 2 PM. Awards at 4 PM.",
    category: "ACADEMIC",
    status: "UPCOMING",
    visibility: "PUBLIC",
    branchId: "br-apex-01",
    branchName: "Apex Global Campus",
    startDate: "2026-10-20",
    endDate: "2026-10-20",
    startTime: "10:00",
    endTime: "17:00",
    allDay: false,
    organizer: "Dr. Sarah Lin (HOD Science)",
    organizerRole: "TEACHER",
    participantCount: 64,
    maxParticipants: 100,
    participantType: "STUDENTS",
    classIds: ["cls-g9", "cls-g10", "cls-g11", "cls-g12"],
    classNames: ["Grade 9", "Grade 10", "Grade 11", "Grade 12"],
    reminders: [
      { id: "rem-005", eventId: "evt-003", remindBefore: 20160, channel: "IN_APP", sent: false },
    ],
    tags: ["science", "exhibition", "projects"],
    createdAt: "2026-08-20T11:00:00Z",
    updatedAt: "2026-08-20T11:00:00Z",
  },
  {
    id: "evt-004",
    title: "Teacher Training Workshop — AI in Education",
    description: "Mandatory workshop covering: 1) AI-powered grading tools, 2) Personalized learning platforms, 3) ChatGPT in curriculum design, 4) Ethical AI use in schools. Bring your laptop. Certificates provided.",
    category: "WORKSHOP",
    status: "UPCOMING",
    visibility: "STAFF_ONLY",
    branchId: "all",
    branchName: "All Campuses",
    venueId: "ven-002",
    venueName: "Conference Hall",
    venueAddress: "Admin Block, 2nd Floor",
    startDate: "2026-09-05",
    endDate: "2026-09-05",
    startTime: "14:00",
    endTime: "17:00",
    allDay: false,
    organizer: "Principal Dr. Meera Kapoor",
    organizerRole: "PRINCIPAL",
    participantCount: 42,
    maxParticipants: 60,
    participantType: "TEACHERS",
    reminders: [
      { id: "rem-006", eventId: "evt-004", remindBefore: 1440, channel: "IN_APP", sent: false },
    ],
    tags: ["training", "ai", "workshop", "mandatory"],
    createdAt: "2026-08-30T08:00:00Z",
    updatedAt: "2026-08-30T08:00:00Z",
  },
  {
    id: "evt-005",
    title: "Ganesh Chaturthi Celebration",
    description: "A special assembly and cultural program celebrating Ganesh Chaturthi. Students will present a short play and devotional songs. Eco-friendly Ganesh idol making competition for primary students.",
    category: "CULTURAL",
    status: "UPCOMING",
    visibility: "PUBLIC",
    branchId: "br-north-03",
    branchName: "Northpoint Montessori & Prep",
    venueId: "ven-005",
    venueName: "Garden Studio",
    venueAddress: "Montessori Wing",
    startDate: "2026-09-05",
    endDate: "2026-09-05",
    startTime: "08:30",
    endTime: "12:00",
    allDay: false,
    organizer: "Annette Dupont (Class Teacher)",
    organizerRole: "TEACHER",
    participantCount: 42,
    maxParticipants: 50,
    participantType: "STUDENTS",
    reminders: [
      { id: "rem-007", eventId: "evt-005", remindBefore: 1440, channel: "IN_APP", sent: false },
    ],
    tags: ["festival", "cultural", "eco-friendly"],
    createdAt: "2026-08-25T09:00:00Z",
    updatedAt: "2026-08-25T09:00:00Z",
  },
  {
    id: "evt-006",
    title: "Sports Day — Inter-Class Athletics",
    description: "Annual Sports Day featuring track events, team sports, and fun activities. Houses compete for the Championship Trophy. Parents welcome to attend and cheer.",
    category: "SPORTS",
    status: "UPCOMING",
    visibility: "PUBLIC",
    branchId: "br-apex-01",
    branchName: "Apex Global Campus",
    venueId: "ven-003",
    venueName: "Sports Ground",
    venueAddress: "Outdoor Area, East Wing",
    startDate: "2026-11-15",
    endDate: "2026-11-15",
    startTime: "07:30",
    endTime: "16:00",
    allDay: true,
    organizer: "Sports Department",
    organizerRole: "STAFF",
    participantCount: 450,
    maxParticipants: 600,
    participantType: "STUDENTS",
    reminders: [
      { id: "rem-008", eventId: "evt-006", remindBefore: 43200, channel: "IN_APP", sent: false },
      { id: "rem-009", eventId: "evt-006", remindBefore: 10080, channel: "SMS", sent: false },
    ],
    tags: ["sports", "athletics", "competition"],
    createdAt: "2026-09-01T10:00:00Z",
    updatedAt: "2026-09-01T10:00:00Z",
  },
  {
    id: "evt-007",
    title: "Fire Safety Drill",
    description: "Mandatory fire safety drill across all campuses. Students will be guided to assembly points by class teachers. Fire department officials will demonstrate extinguisher use. Duration: 30 minutes.",
    category: "OTHER",
    status: "UPCOMING",
    visibility: "PUBLIC",
    branchId: "all",
    branchName: "All Campuses",
    startDate: "2026-09-12",
    endDate: "2026-09-12",
    startTime: "10:30",
    endTime: "11:00",
    allDay: false,
    organizer: "Safety Officer Mr. Ravi Shankar",
    organizerRole: "STAFF",
    participantCount: 800,
    maxParticipants: 1200,
    participantType: "ALL",
    reminders: [
      { id: "rem-010", eventId: "evt-007", remindBefore: 1440, channel: "IN_APP", sent: false },
    ],
    tags: ["safety", "drill", "mandatory"],
    createdAt: "2026-09-03T09:00:00Z",
    updatedAt: "2026-09-03T09:00:00Z",
  },
  {
    id: "evt-008",
    title: "Diwali Celebration & Craft Workshop",
    description: "Celebrate Diwali with rangoli competition, diya painting, and a special assembly. Parents are invited for the evening cultural program from 5 PM.",
    category: "CULTURAL",
    status: "UPCOMING",
    visibility: "PUBLIC",
    branchId: "br-west-02",
    branchName: "Westside STEM & Innovation Academy",
    venueId: "ven-004",
    venueName: "Seminar Hall",
    venueAddress: "Block C, 1st Floor",
    startDate: "2026-10-20",
    endDate: "2026-10-20",
    startTime: "09:00",
    endTime: "18:00",
    allDay: false,
    organizer: "Cultural Committee",
    organizerRole: "STAFF",
    participantCount: 180,
    maxParticipants: 200,
    participantType: "ALL",
    reminders: [
      { id: "rem-011", eventId: "evt-008", remindBefore: 20160, channel: "IN_APP", sent: false },
    ],
    tags: ["diwali", "festival", "craft", "cultural"],
    createdAt: "2026-09-02T10:00:00Z",
    updatedAt: "2026-09-02T10:00:00Z",
  },
];
