import { Exam, ExamType, ExamSchedule, MarkEntry, GradeScale, Result } from "@/types";

export const initialExamTypes: ExamType[] = [
  { id: "ety-001", name: "Weekly Test", category: "WEEKLY_TEST", description: "Weekly formative test — 20 marks", maxMarks: 20, passingMarks: 7, weightage: 5, branchId: "all", defaultMode: "OBJECTIVE" },
  { id: "ety-002", name: "Monthly Test", category: "MONTHLY_TEST", description: "Monthly assessment — 50 marks", maxMarks: 50, passingMarks: 18, weightage: 10, branchId: "all", defaultMode: "BOTH" },
  { id: "ety-003", name: "Unit Test", category: "UNIT_TEST", description: "Unit Test — periodic class test (50 marks)", maxMarks: 50, passingMarks: 18, weightage: 10, branchId: "all", defaultMode: "SUBJECTIVE" },
  { id: "ety-004", name: "Subjective", category: "SUBJECTIVE", description: "Descriptive/theory paper", maxMarks: 100, passingMarks: 33, weightage: 15, branchId: "all", defaultMode: "SUBJECTIVE" },
  { id: "ety-005", name: "Objective", category: "OBJECTIVE", description: "MCQ / OMR objective paper", maxMarks: 100, passingMarks: 33, weightage: 15, branchId: "all", defaultMode: "OBJECTIVE" },
  { id: "ety-006", name: "Half Yearly", category: "MIDTERM", description: "Half-yearly comprehensive (100 marks)", maxMarks: 100, passingMarks: 33, weightage: 25, branchId: "all", defaultMode: "BOTH" },
  { id: "ety-007", name: "Final", category: "FINAL", description: "Annual final examination", maxMarks: 100, passingMarks: 33, weightage: 40, branchId: "all", defaultMode: "BOTH" },
  { id: "ety-008", name: "Annual", category: "ANNUAL", description: "Year-end annual examination", maxMarks: 100, passingMarks: 33, weightage: 40, branchId: "all", defaultMode: "BOTH" },
  { id: "ety-009", name: "Custom", category: "CUSTOM", description: "Custom / remedial / re-test", maxMarks: 50, passingMarks: 18, weightage: 5, branchId: "all", defaultMode: "BOTH" },
];

export const initialExams: Exam[] = [
  {
    id: "ex-2026-g10-half",
    name: "Half Yearly Exam",
    examTypeId: "ety-006",
    examTypeName: "Half Yearly",
    category: "MIDTERM",
    examMode: "BOTH",
    academicYear: "2026-2027",
    classId: "cls-g10",
    className: "Grade 10",
    sectionId: "sec-g10-a",
    sectionName: "Section A (STEM Honors)",
    branchId: "br-apex-01",
    branchName: "Apex Global Campus",
    startDate: "2026-10-10",
    endDate: "2026-10-20",
    status: "PUBLISHED",
    instructions: "Bring admit card, school ID, and stationery. Reporting time 8:30 AM. No electronic devices.",
    noticePublishedAt: "2026-08-02T10:00:00Z",
    noticePublishedBy: "Admin",
    createdBy: "Admin",
    createdAt: "2026-08-01T10:00:00Z",
    updatedAt: "2026-08-02T10:00:00Z",
  },
  {
    id: "ex-2026-g12-half",
    name: "Half Yearly Exam",
    examTypeId: "ety-006",
    examTypeName: "Half Yearly",
    category: "MIDTERM",
    examMode: "BOTH",
    academicYear: "2026-2027",
    classId: "cls-g12",
    className: "Grade 12",
    sectionId: "sec-g12-a",
    sectionName: "Section A (Ivy Placement)",
    branchId: "br-apex-01",
    branchName: "Apex Global Campus",
    startDate: "2026-10-10",
    endDate: "2026-10-20",
    status: "PUBLISHED",
    instructions: "Strict invigilation. Calculators allowed for Science only.",
    noticePublishedAt: "2026-08-02T10:00:00Z",
    noticePublishedBy: "Admin",
    createdBy: "Admin",
    createdAt: "2026-08-01T10:00:00Z",
    updatedAt: "2026-08-02T10:00:00Z",
  },
  {
    id: "ex-2026-g9-ut1",
    name: "Unit Test",
    examTypeId: "ety-003",
    examTypeName: "Unit Test",
    category: "UNIT_TEST",
    examMode: "SUBJECTIVE",
    academicYear: "2026-2027",
    classId: "cls-g9",
    className: "Grade 9",
    sectionId: "sec-g9-a",
    sectionName: "Section Alpha (Robotics Core)",
    branchId: "br-west-02",
    branchName: "Westside STEM & Innovation Academy",
    startDate: "2026-10-05",
    endDate: "2026-10-08",
    status: "PUBLISHED",
    instructions: "50 marks per subject. Duration 90 minutes.",
    noticePublishedAt: "2026-08-16T10:00:00Z",
    noticePublishedBy: "Admin",
    createdBy: "Admin",
    createdAt: "2026-08-15T10:00:00Z",
    updatedAt: "2026-08-16T10:00:00Z",
  },
  {
    id: "ex-2026-g10-weekly",
    name: "Weekly Test",
    examTypeId: "ety-001",
    examTypeName: "Weekly Test",
    category: "WEEKLY_TEST",
    examMode: "OBJECTIVE",
    academicYear: "2026-2027",
    classId: "cls-g10",
    className: "Grade 10",
    sectionId: "sec-g10-a",
    sectionName: "Section A (STEM Honors)",
    branchId: "br-apex-01",
    branchName: "Apex Global Campus",
    startDate: "2026-09-01",
    endDate: "2026-09-06",
    status: "DRAFT",
    instructions: "OMR based objective test.",
    createdBy: "Admin",
    createdAt: "2026-08-20T10:00:00Z",
    updatedAt: "2026-08-20T10:00:00Z",
  },
];

// CBSE 9-point grading scale (Classes 9-12)
export const initialGradeScale: GradeScale[] = [
  { id: "gs-01", grade: "A1", minPercentage: 91, maxPercentage: 100, gpa: 4.0, description: "Outstanding", color: "emerald" },
  { id: "gs-02", grade: "A2", minPercentage: 81, maxPercentage: 90.99, gpa: 3.7, description: "Excellent", color: "emerald" },
  { id: "gs-03", grade: "B1", minPercentage: 71, maxPercentage: 80.99, gpa: 3.3, description: "Very Good", color: "blue" },
  { id: "gs-04", grade: "B2", minPercentage: 61, maxPercentage: 70.99, gpa: 3.0, description: "Good", color: "blue" },
  { id: "gs-05", grade: "C1", minPercentage: 51, maxPercentage: 60.99, gpa: 2.3, description: "Average", color: "amber" },
  { id: "gs-06", grade: "C2", minPercentage: 41, maxPercentage: 50.99, gpa: 2.0, description: "Below Average", color: "amber" },
  { id: "gs-07", grade: "D", minPercentage: 33, maxPercentage: 40.99, gpa: 1.0, description: "Needs Improvement", color: "rose" },
  { id: "gs-08", grade: "E", minPercentage: 0, maxPercentage: 32.99, gpa: 0.0, description: "Fail — needs re-exam", color: "rose" },
];

export const initialExamSchedules: ExamSchedule[] = [
  // Half-Yearly Exams - Grade 10 (10-20 Oct 2026) — Published
  { id: "es-001", examId: "ex-2026-g10-half", examName: "Half Yearly Exam - Mathematics", examTypeId: "ety-006", examTypeName: "Half Yearly", classId: "cls-g10", className: "Grade 10", sectionId: "sec-g10-a", sectionName: "Section A (STEM Honors)", subjectId: "sub-101", subjectName: "Mathematics", branchId: "br-apex-01", branchName: "Apex Global Campus", academicYear: "2026-2027", examDate: "2026-10-10", startTime: "09:00", endTime: "12:00", room: "Room 301", status: "SCHEDULED", publicationStatus: "PUBLISHED", isPublished: true, totalMarks: 100, passingMarks: 33 },
  { id: "es-002", examName: "Half Yearly Exam - Science", examId: "ex-2026-g10-half", examTypeId: "ety-006", examTypeName: "Half Yearly", classId: "cls-g10", className: "Grade 10", sectionId: "sec-g10-a", sectionName: "Section A (STEM Honors)", subjectId: "sub-102", subjectName: "Science", branchId: "br-apex-01", branchName: "Apex Global Campus", academicYear: "2026-2027", examDate: "2026-10-12", startTime: "09:00", endTime: "12:00", room: "Physics Lab 3", status: "SCHEDULED", publicationStatus: "PUBLISHED", isPublished: true, totalMarks: 100, passingMarks: 33 },
  { id: "es-003", examName: "Half Yearly Exam - English", examId: "ex-2026-g10-half", examTypeId: "ety-006", examTypeName: "Half Yearly", classId: "cls-g10", className: "Grade 10", sectionId: "sec-g10-a", sectionName: "Section A (STEM Honors)", subjectId: "sub-104", subjectName: "English", branchId: "br-apex-01", branchName: "Apex Global Campus", academicYear: "2026-2027", examDate: "2026-10-15", startTime: "09:00", endTime: "11:30", room: "Tech Lab 12", status: "SCHEDULED", publicationStatus: "PUBLISHED", isPublished: true, totalMarks: 100, passingMarks: 33 },

  // Unit Test - Grade 9
  { id: "es-004", examId: "ex-2026-g9-ut1", examName: "Unit Test - Mathematics", examTypeId: "ety-003", examTypeName: "Unit Test", classId: "cls-g9", className: "Grade 9", sectionId: "sec-g9-a", sectionName: "Section Alpha (Robotics Core)", subjectId: "sub-901", subjectName: "Mathematics", branchId: "br-west-02", branchName: "Westside STEM & Innovation Academy", academicYear: "2026-2027", examDate: "2026-10-05", startTime: "10:00", endTime: "11:30", room: "Room 108", status: "SCHEDULED", publicationStatus: "PUBLISHED", isPublished: true, totalMarks: 50, passingMarks: 18 },
  { id: "es-005", examName: "Unit Test - Science", examId: "ex-2026-g9-ut1", examTypeId: "ety-003", examTypeName: "Unit Test", classId: "cls-g9", className: "Grade 9", sectionId: "sec-g9-a", sectionName: "Section Alpha (Robotics Core)", subjectId: "sub-902", subjectName: "Science", branchId: "br-west-02", branchName: "Westside STEM & Innovation Academy", academicYear: "2026-2027", examDate: "2026-10-07", startTime: "10:00", endTime: "12:00", room: "Tech Lab 12", status: "SCHEDULED", publicationStatus: "PUBLISHED", isPublished: true, totalMarks: 50, passingMarks: 18 },

  // Completed Half-Yearly - Grade 12 (already conducted)
  { id: "es-006", examId: "ex-2026-g12-half", examName: "Half Yearly Exam - Mathematics", examTypeId: "ety-006", examTypeName: "Half Yearly", classId: "cls-g12", className: "Grade 12", sectionId: "sec-g12-a", sectionName: "Section A (Ivy Placement)", subjectId: "sub-1201", subjectName: "Mathematics", branchId: "br-apex-01", branchName: "Apex Global Campus", academicYear: "2026-2027", examDate: "2026-08-20", startTime: "09:00", endTime: "12:00", room: "Class 12-A", status: "COMPLETED", publicationStatus: "PUBLISHED", isPublished: true, totalMarks: 100, passingMarks: 33 },
  { id: "es-007", examName: "Half Yearly Exam - Physics", examId: "ex-2026-g12-half", examTypeId: "ety-006", examTypeName: "Half Yearly", classId: "cls-g12", className: "Grade 12", sectionId: "sec-g12-a", sectionName: "Section A (Ivy Placement)", subjectId: "sub-1202", subjectName: "Physics", branchId: "br-apex-01", branchName: "Apex Global Campus", academicYear: "2026-2027", examDate: "2026-08-21", startTime: "09:00", endTime: "12:00", room: "Physics Lab 3", status: "COMPLETED", publicationStatus: "PUBLISHED", isPublished: true, totalMarks: 100, passingMarks: 33 },
  { id: "es-008", examName: "Half Yearly Exam - Chemistry", examId: "ex-2026-g12-half", examTypeId: "ety-006", examTypeName: "Half Yearly", classId: "cls-g12", className: "Grade 12", sectionId: "sec-g12-a", sectionName: "Section A (Ivy Placement)", subjectId: "sub-1203", subjectName: "Chemistry", branchId: "br-apex-01", branchName: "Apex Global Campus", academicYear: "2026-2027", examDate: "2026-08-22", startTime: "09:00", endTime: "11:30", room: "Class 12-A", status: "COMPLETED", publicationStatus: "PUBLISHED", isPublished: true, totalMarks: 100, passingMarks: 33 },
];

export const initialMarkEntries: MarkEntry[] = [
  // Grade 12 Half-Yearly Results — workflow VERIFIED/LOCKED sample
  { id: "mk-001", examScheduleId: "es-006", studentId: "stu-12-01", studentName: "Arjun Nair", studentRoll: "STU-1201", subjectId: "sub-1201", subjectName: "Mathematics", marksObtained: 92, totalMarks: 100, percentage: 92, grade: "A1", status: "PASS", remarks: "Outstanding performance", enteredBy: "Mrs. Sunita Rao", enteredAt: "2026-08-25T10:00:00Z", workflowStatus: "VERIFIED", verifiedBy: "Admin" },
  { id: "mk-002", examScheduleId: "es-006", studentId: "stu-12-02", studentName: "Kavya Iyer", studentRoll: "STU-1202", subjectId: "sub-1201", subjectName: "Mathematics", marksObtained: 87, totalMarks: 100, percentage: 87, grade: "A2", status: "PASS", remarks: "Excellent analytical skills", enteredBy: "Mrs. Sunita Rao", enteredAt: "2026-08-25T10:05:00Z", workflowStatus: "VERIFIED" },
  { id: "mk-003", examScheduleId: "es-006", studentId: "stu-12-03", studentName: "Rohan Gupta", studentRoll: "STU-1203", subjectId: "sub-1201", subjectName: "Mathematics", marksObtained: 78, totalMarks: 100, percentage: 78, grade: "B1", status: "PASS", remarks: "Good grasp of integration concepts", enteredBy: "Mrs. Sunita Rao", enteredAt: "2026-08-25T10:10:00Z", workflowStatus: "SUBMITTED" },
  { id: "mk-004", examScheduleId: "es-006", studentId: "stu-12-04", studentName: "Anika Verma", studentRoll: "STU-1204", subjectId: "sub-1201", subjectName: "Mathematics", marksObtained: 95, totalMarks: 100, percentage: 95, grade: "A1", status: "PASS", remarks: "Top of class", enteredBy: "Mrs. Sunita Rao", enteredAt: "2026-08-25T10:15:00Z", workflowStatus: "VERIFIED" },
  { id: "mk-005", examScheduleId: "es-006", studentId: "stu-12-05", studentName: "Dev Malhotra", studentRoll: "STU-1205", subjectId: "sub-1201", subjectName: "Mathematics", marksObtained: 65, totalMarks: 100, percentage: 65, grade: "B2", status: "PASS", remarks: "Needs practice in determinants", enteredBy: "Mrs. Sunita Rao", enteredAt: "2026-08-25T10:20:00Z", workflowStatus: "DRAFT" },

  { id: "mk-006", examScheduleId: "es-007", studentId: "stu-12-01", studentName: "Arjun Nair", studentRoll: "STU-1201", subjectId: "sub-1202", subjectName: "Physics", marksObtained: 88, totalMarks: 100, percentage: 88, grade: "A2", status: "PASS", remarks: "Strong numericals understanding", enteredBy: "Mr. Rajesh Kulkarni", enteredAt: "2026-08-25T11:00:00Z", workflowStatus: "VERIFIED" },
  { id: "mk-007", examScheduleId: "es-007", studentId: "stu-12-02", studentName: "Kavya Iyer", studentRoll: "STU-1202", subjectId: "sub-1202", subjectName: "Physics", marksObtained: 82, totalMarks: 100, percentage: 82, grade: "A2", status: "PASS", remarks: "Good lab record and theory", enteredBy: "Mr. Rajesh Kulkarni", enteredAt: "2026-08-25T11:05:00Z", workflowStatus: "VERIFIED" },
  { id: "mk-008", examScheduleId: "es-007", studentId: "stu-12-03", studentName: "Rohan Gupta", studentRoll: "STU-1203", subjectId: "sub-1202", subjectName: "Physics", marksObtained: 71, totalMarks: 100, percentage: 71, grade: "B1", status: "PASS", remarks: "Solid but needs more numerical practice", enteredBy: "Mr. Rajesh Kulkarni", enteredAt: "2026-08-25T11:10:00Z", workflowStatus: "VERIFIED" },
  { id: "mk-009", examScheduleId: "es-007", studentId: "stu-12-04", studentName: "Anika Verma", studentRoll: "STU-1204", subjectId: "sub-1202", subjectName: "Physics", marksObtained: 91, totalMarks: 100, percentage: 91, grade: "A1", status: "PASS", remarks: "Excellent derivations and diagrams", enteredBy: "Mr. Rajesh Kulkarni", enteredAt: "2026-08-25T11:15:00Z", workflowStatus: "VERIFIED" },
  { id: "mk-010", examScheduleId: "es-007", studentId: "stu-12-05", studentName: "Dev Malhotra", studentRoll: "STU-1205", subjectId: "sub-1202", subjectName: "Physics", marksObtained: 58, totalMarks: 100, percentage: 58, grade: "C1", status: "PASS", remarks: "Below expectations. Extra class recommended.", enteredBy: "Mr. Rajesh Kulkarni", enteredAt: "2026-08-25T11:20:00Z", workflowStatus: "VERIFIED" },

  { id: "mk-011", examScheduleId: "es-008", studentId: "stu-12-01", studentName: "Arjun Nair", studentRoll: "STU-1201", subjectId: "sub-1203", subjectName: "Chemistry", marksObtained: 85, totalMarks: 100, percentage: 85, grade: "A2", status: "PASS", remarks: "Good organic conversions", enteredBy: "Mrs. Sunita Rao", enteredAt: "2026-08-25T12:00:00Z", workflowStatus: "VERIFIED" },
  { id: "mk-012", examScheduleId: "es-008", studentId: "stu-12-02", studentName: "Kavya Iyer", studentRoll: "STU-1202", subjectId: "sub-1203", subjectName: "Chemistry", marksObtained: 90, totalMarks: 100, percentage: 90, grade: "A2", status: "PASS", remarks: "Neat salt analysis record", enteredBy: "Mrs. Sunita Rao", enteredAt: "2026-08-25T12:05:00Z", workflowStatus: "VERIFIED" },
  { id: "mk-013", examScheduleId: "es-008", studentId: "stu-12-03", studentName: "Rohan Gupta", studentRoll: "STU-1203", subjectId: "sub-1203", subjectName: "Chemistry", marksObtained: 76, totalMarks: 100, percentage: 76, grade: "B1", status: "PASS", remarks: "Good chemical equations", enteredBy: "Mrs. Sunita Rao", enteredAt: "2026-08-25T12:10:00Z", workflowStatus: "VERIFIED" },
  { id: "mk-014", examScheduleId: "es-008", studentId: "stu-12-04", studentName: "Anika Verma", studentRoll: "STU-1204", subjectId: "sub-1203", subjectName: "Chemistry", marksObtained: 93, totalMarks: 100, percentage: 93, grade: "A1", status: "PASS", remarks: "Exceptional clarity in physical chemistry", enteredBy: "Mrs. Sunita Rao", enteredAt: "2026-08-25T12:15:00Z", workflowStatus: "VERIFIED" },
  { id: "mk-015", examScheduleId: "es-008", studentId: "stu-12-05", studentName: "Dev Malhotra", studentRoll: "STU-1205", subjectId: "sub-1203", subjectName: "Chemistry", marksObtained: 68, totalMarks: 100, percentage: 68, grade: "B2", status: "PASS", remarks: "Needs to revise named reactions", enteredBy: "Mrs. Sunita Rao", enteredAt: "2026-08-25T12:20:00Z", workflowStatus: "VERIFIED" },
  // Absent sample
  { id: "mk-016", examScheduleId: "es-006", studentId: "stu-12-06", studentName: "Riya Kulkarni", studentRoll: "STU-1206", subjectId: "sub-1201", subjectName: "Mathematics", marksObtained: 0, totalMarks: 100, percentage: 0, grade: "E", status: "FAIL", remarks: "Absent", enteredBy: "Mrs. Sunita Rao", enteredAt: "2026-08-25T12:25:00Z", isAbsent: true, workflowStatus: "SUBMITTED" },
];

export const initialResults: Result[] = [
  {
    id: "res-001",
    studentId: "stu-12-01",
    studentName: "Arjun Nair",
    studentRoll: "STU-1201",
    admissionNumber: "ADM-2024-012",
    classId: "cls-g12",
    className: "Grade 12",
    sectionId: "sec-g12-a",
    sectionName: "Section A (Ivy Placement)",
    branchId: "br-apex-01",
    branchName: "Apex Global Campus",
    examId: "ex-2026-g12-half",
    examTypeId: "ety-006",
    examTypeName: "Half Yearly",
    examMode: "BOTH",
    academicYear: "2026-2027",
    totalMarks: 300,
    marksObtained: 265,
    percentage: 88.33,
    overallGrade: "A2",
    gpa: 3.7,
    rank: 2,
    totalStudents: 34,
    status: "PASS",
    isPublished: true,
    publicationStatus: "PUBLISHED",
    publishedAt: "2026-08-26T10:00:00Z",
    subjects: [
      { subjectId: "sub-1201", subjectName: "Mathematics", marksObtained: 92, totalMarks: 100, percentage: 92, grade: "A1", status: "PASS" },
      { subjectId: "sub-1202", subjectName: "Physics", marksObtained: 88, totalMarks: 100, percentage: 88, grade: "A2", status: "PASS" },
      { subjectId: "sub-1203", subjectName: "Chemistry", marksObtained: 85, totalMarks: 100, percentage: 85, grade: "A2", status: "PASS" },
    ],
    remarks: "Excellent overall performance. Keep it up!",
    createdAt: "2026-08-26T10:00:00Z",
    updatedAt: "2026-08-26T10:00:00Z",
  },
  {
    id: "res-002",
    studentId: "stu-12-02",
    studentName: "Kavya Iyer",
    studentRoll: "STU-1202",
    admissionNumber: "ADM-2024-013",
    classId: "cls-g12",
    className: "Grade 12",
    sectionId: "sec-g12-a",
    sectionName: "Section A (Ivy Placement)",
    branchId: "br-apex-01",
    branchName: "Apex Global Campus",
    examId: "ex-2026-g12-half",
    examTypeId: "ety-006",
    examTypeName: "Half Yearly",
    academicYear: "2026-2027",
    totalMarks: 300,
    marksObtained: 259,
    percentage: 86.33,
    overallGrade: "A2",
    gpa: 3.7,
    rank: 3,
    totalStudents: 34,
    status: "PASS",
    isPublished: true,
    publicationStatus: "PUBLISHED",
    subjects: [
      { subjectId: "sub-1201", subjectName: "Mathematics", marksObtained: 87, totalMarks: 100, percentage: 87, grade: "A2", status: "PASS" },
      { subjectId: "sub-1202", subjectName: "Physics", marksObtained: 82, totalMarks: 100, percentage: 82, grade: "A2", status: "PASS" },
      { subjectId: "sub-1203", subjectName: "Chemistry", marksObtained: 90, totalMarks: 100, percentage: 90, grade: "A2", status: "PASS" },
    ],
    remarks: "Consistent performance across all subjects.",
    createdAt: "2026-08-26T10:00:00Z",
    updatedAt: "2026-08-26T10:00:00Z",
  },
  {
    id: "res-003",
    studentId: "stu-12-03",
    studentName: "Rohan Gupta",
    studentRoll: "STU-1203",
    admissionNumber: "ADM-2024-014",
    classId: "cls-g12",
    className: "Grade 12",
    sectionId: "sec-g12-a",
    sectionName: "Section A (Ivy Placement)",
    branchId: "br-apex-01",
    branchName: "Apex Global Campus",
    examId: "ex-2026-g12-half",
    examTypeId: "ety-006",
    examTypeName: "Half Yearly",
    academicYear: "2026-2027",
    totalMarks: 300,
    marksObtained: 225,
    percentage: 75.0,
    overallGrade: "B1",
    gpa: 3.3,
    rank: 4,
    totalStudents: 34,
    status: "PASS",
    isPublished: true,
    publicationStatus: "PUBLISHED",
    subjects: [
      { subjectId: "sub-1201", subjectName: "Mathematics", marksObtained: 78, totalMarks: 100, percentage: 78, grade: "B1", status: "PASS" },
      { subjectId: "sub-1202", subjectName: "Physics", marksObtained: 71, totalMarks: 100, percentage: 71, grade: "B1", status: "PASS" },
      { subjectId: "sub-1203", subjectName: "Chemistry", marksObtained: 76, totalMarks: 100, percentage: 76, grade: "B1", status: "PASS" },
    ],
    remarks: "Good performance. Focus on revision speed.",
    createdAt: "2026-08-26T10:00:00Z",
    updatedAt: "2026-08-26T10:00:00Z",
  },
  {
    id: "res-004",
    studentId: "stu-12-04",
    studentName: "Anika Verma",
    studentRoll: "STU-1204",
    admissionNumber: "ADM-2024-015",
    classId: "cls-g12",
    className: "Grade 12",
    sectionId: "sec-g12-a",
    sectionName: "Section A (Ivy Placement)",
    branchId: "br-apex-01",
    branchName: "Apex Global Campus",
    examId: "ex-2026-g12-half",
    examTypeId: "ety-006",
    examTypeName: "Half Yearly",
    academicYear: "2026-2027",
    totalMarks: 300,
    marksObtained: 279,
    percentage: 93.0,
    overallGrade: "A1",
    gpa: 4.0,
    rank: 1,
    totalStudents: 34,
    status: "PASS",
    isPublished: true,
    publicationStatus: "PUBLISHED",
    subjects: [
      { subjectId: "sub-1201", subjectName: "Mathematics", marksObtained: 95, totalMarks: 100, percentage: 95, grade: "A1", status: "PASS" },
      { subjectId: "sub-1202", subjectName: "Physics", marksObtained: 91, totalMarks: 100, percentage: 91, grade: "A1", status: "PASS" },
      { subjectId: "sub-1203", subjectName: "Chemistry", marksObtained: 93, totalMarks: 100, percentage: 93, grade: "A1", status: "PASS" },
    ],
    remarks: "School topper! Exceptional work.",
    createdAt: "2026-08-26T10:00:00Z",
    updatedAt: "2026-08-26T10:00:00Z",
  },
  {
    id: "res-005",
    studentId: "stu-12-05",
    studentName: "Dev Malhotra",
    studentRoll: "STU-1205",
    admissionNumber: "ADM-2024-016",
    classId: "cls-g12",
    className: "Grade 12",
    sectionId: "sec-g12-a",
    sectionName: "Section A (Ivy Placement)",
    branchId: "br-apex-01",
    branchName: "Apex Global Campus",
    examId: "ex-2026-g12-half",
    examTypeId: "ety-006",
    examTypeName: "Half Yearly",
    academicYear: "2026-2027",
    totalMarks: 300,
    marksObtained: 191,
    percentage: 63.67,
    overallGrade: "B2",
    gpa: 3.0,
    rank: 5,
    totalStudents: 34,
    status: "PASS",
    isPublished: true,
    publicationStatus: "PUBLISHED",
    subjects: [
      { subjectId: "sub-1201", subjectName: "Mathematics", marksObtained: 65, totalMarks: 100, percentage: 65, grade: "B2", status: "PASS" },
      { subjectId: "sub-1202", subjectName: "Physics", marksObtained: 58, totalMarks: 100, percentage: 58, grade: "C1", status: "PASS" },
      { subjectId: "sub-1203", subjectName: "Chemistry", marksObtained: 68, totalMarks: 100, percentage: 68, grade: "B2", status: "PASS" },
    ],
    remarks: "Needs improvement. PTM scheduled with parents.",
    createdAt: "2026-08-26T10:00:00Z",
    updatedAt: "2026-08-26T10:00:00Z",
  },
];
