import { ExamType, ExamSchedule, MarkEntry, GradeScale, Result } from "@/types";

export const initialExamTypes: ExamType[] = [
  { id: "ety-001", name: "Periodic Test 1", category: "UNIT_TEST", description: "First periodic test covering initial chapters (pen-paper, 50 marks)", maxMarks: 50, passingMarks: 18, weightage: 10, branchId: "all" },
  { id: "ety-002", name: "Half-Yearly Examination", category: "MIDTERM", description: "Half-yearly comprehensive exam on CBSE pattern (100 marks)", maxMarks: 100, passingMarks: 33, weightage: 25, branchId: "all" },
  { id: "ety-003", name: "Annual Examination", category: "FINAL", description: "End-of-session board-pattern examination", maxMarks: 100, passingMarks: 33, weightage: 40, branchId: "all" },
  { id: "ety-004", name: "Periodic Test 2", category: "QUARTERLY", description: "Second periodic assessment with notebook + subject enrichment", maxMarks: 50, passingMarks: 18, weightage: 15, branchId: "all" },
  { id: "ety-005", name: "Practical / Internal Assessment", category: "CUSTOM", description: "Lab practicals, project and internal assessment", maxMarks: 50, passingMarks: 20, weightage: 10, branchId: "all" },
];

// CBSE 9-point grading scale (Classes 9-12)
export const initialGradeScale: GradeScale[] = [
  { id: "gs-01", grade: "A1", minPercentage: 91, maxPercentage: 100, gpa: 4.0, description: "Outstanding", color: "emerald" },
  { id: "gs-02", grade: "A2", minPercentage: 81, maxPercentage: 90.99, gpa: 3.7, description: "Excellent", color: "emerald" },
  { id: "gs-03", grade: "B1", minPercentage: 71, maxPercentage: 80.99, gpa: 3.3, description: "Very Good", color: "blue" },
  { id: "gs-04", grade: "B2", minPercentage: 61, maxPercentage: 70.99, gpa: 3.0, description: "Good", color: "blue" },
  { id: "gs-05", grade: "C1", minPercentage: 51, maxPercentage: 60.99, gpa: 2.3, description: "Average", color: "amber" },
  { id: "gs-06", grade: "C2", minPercentage: 41, maxPercentage: 50.99, gpa: 2.0, description: "Below Average", color: "amber" },
  { id: "gs-07", grade: "D", minPercentage: 33, maxPercentage: 40.99, gpa: 1.0, description: "Needs Improvement", color: "rose" },
  { id: "gs-08", grade: "E", minPercentage: 0, maxPercentage: 32.99, gpa: 0.0, description: "Fail — needs re-exam", color: "rose" },
];

export const initialExamSchedules: ExamSchedule[] = [
  // Half-Yearly Exams - Grade 10
  { id: "es-001", examName: "Half-Yearly - Mathematics", examTypeId: "ety-002", examTypeName: "Half-Yearly Examination", classId: "cls-g10", className: "Grade 10", sectionId: "sec-g10-a", sectionName: "Section A (STEM Honors)", subjectId: "sub-101", subjectName: "Mathematics", branchId: "br-apex-01", branchName: "Apex Global Campus", examDate: "2026-09-15", startTime: "09:00", endTime: "12:00", room: "Room 301", status: "SCHEDULED", totalMarks: 100, passingMarks: 33 },
  { id: "es-002", examName: "Half-Yearly - Science", examTypeId: "ety-002", examTypeName: "Half-Yearly Examination", classId: "cls-g10", className: "Grade 10", sectionId: "sec-g10-a", sectionName: "Section A (STEM Honors)", subjectId: "sub-102", subjectName: "Science", branchId: "br-apex-01", branchName: "Apex Global Campus", examDate: "2026-09-16", startTime: "09:00", endTime: "12:00", room: "Physics Lab 3", status: "SCHEDULED", totalMarks: 100, passingMarks: 33 },
  { id: "es-003", examName: "Half-Yearly - Computer Science", examTypeId: "ety-002", examTypeName: "Half-Yearly Examination", classId: "cls-g10", className: "Grade 10", sectionId: "sec-g10-a", sectionName: "Section A (STEM Honors)", subjectId: "sub-103", subjectName: "Computer Science", branchId: "br-apex-01", branchName: "Apex Global Campus", examDate: "2026-09-17", startTime: "09:00", endTime: "11:30", room: "Tech Lab 12", status: "SCHEDULED", totalMarks: 100, passingMarks: 33 },

  // Periodic Test - Grade 9
  { id: "es-004", examName: "Periodic Test 1 - Mathematics", examTypeId: "ety-001", examTypeName: "Periodic Test 1", classId: "cls-g9", className: "Grade 9", sectionId: "sec-g9-a", sectionName: "Section Alpha (Robotics Core)", subjectId: "sub-901", subjectName: "Mathematics", branchId: "br-west-02", branchName: "Westside STEM & Innovation Academy", examDate: "2026-09-08", startTime: "10:00", endTime: "11:30", room: "Room 108", status: "SCHEDULED", totalMarks: 50, passingMarks: 18 },
  { id: "es-005", examName: "Periodic Test 1 - Science", examTypeId: "ety-001", examTypeName: "Periodic Test 1", classId: "cls-g9", className: "Grade 9", sectionId: "sec-g9-a", sectionName: "Section Alpha (Robotics Core)", subjectId: "sub-902", subjectName: "Science", branchId: "br-west-02", branchName: "Westside STEM & Innovation Academy", examDate: "2026-09-09", startTime: "10:00", endTime: "12:00", room: "Tech Lab 12", status: "SCHEDULED", totalMarks: 50, passingMarks: 18 },

  // Completed Half-Yearly - Grade 12
  { id: "es-006", examName: "Half-Yearly - Mathematics", examTypeId: "ety-002", examTypeName: "Half-Yearly Examination", classId: "cls-g12", className: "Grade 12", sectionId: "sec-g12-a", sectionName: "Section A (Ivy Placement)", subjectId: "sub-1201", subjectName: "Mathematics", branchId: "br-apex-01", branchName: "Apex Global Campus", examDate: "2026-08-20", startTime: "09:00", endTime: "12:00", room: "Class 12-A", status: "COMPLETED", totalMarks: 100, passingMarks: 33 },
  { id: "es-007", examName: "Half-Yearly - Physics", examTypeId: "ety-002", examTypeName: "Half-Yearly Examination", classId: "cls-g12", className: "Grade 12", sectionId: "sec-g12-a", sectionName: "Section A (Ivy Placement)", subjectId: "sub-1202", subjectName: "Physics", branchId: "br-apex-01", branchName: "Apex Global Campus", examDate: "2026-08-21", startTime: "09:00", endTime: "12:00", room: "Physics Lab 3", status: "COMPLETED", totalMarks: 100, passingMarks: 33 },
  { id: "es-008", examName: "Half-Yearly - Chemistry", examTypeId: "ety-002", examTypeName: "Half-Yearly Examination", classId: "cls-g12", className: "Grade 12", sectionId: "sec-g12-a", sectionName: "Section A (Ivy Placement)", subjectId: "sub-1203", subjectName: "Chemistry", branchId: "br-apex-01", branchName: "Apex Global Campus", examDate: "2026-08-22", startTime: "09:00", endTime: "11:30", room: "Class 12-A", status: "COMPLETED", totalMarks: 100, passingMarks: 33 },
];

export const initialMarkEntries: MarkEntry[] = [
  // Grade 12 Half-Yearly Results
  { id: "mk-001", examScheduleId: "es-006", studentId: "stu-12-01", studentName: "Arjun Nair", studentRoll: "STU-1201", subjectId: "sub-1201", subjectName: "Mathematics", marksObtained: 92, totalMarks: 100, percentage: 92, grade: "A1", status: "PASS", remarks: "Outstanding performance", enteredBy: "Mrs. Sunita Rao", enteredAt: "2026-08-25T10:00:00Z" },
  { id: "mk-002", examScheduleId: "es-006", studentId: "stu-12-02", studentName: "Kavya Iyer", studentRoll: "STU-1202", subjectId: "sub-1201", subjectName: "Mathematics", marksObtained: 87, totalMarks: 100, percentage: 87, grade: "A2", status: "PASS", remarks: "Excellent analytical skills", enteredBy: "Mrs. Sunita Rao", enteredAt: "2026-08-25T10:05:00Z" },
  { id: "mk-003", examScheduleId: "es-006", studentId: "stu-12-03", studentName: "Rohan Gupta", studentRoll: "STU-1203", subjectId: "sub-1201", subjectName: "Mathematics", marksObtained: 78, totalMarks: 100, percentage: 78, grade: "B1", status: "PASS", remarks: "Good grasp of integration concepts", enteredBy: "Mrs. Sunita Rao", enteredAt: "2026-08-25T10:10:00Z" },
  { id: "mk-004", examScheduleId: "es-006", studentId: "stu-12-04", studentName: "Anika Verma", studentRoll: "STU-1204", subjectId: "sub-1201", subjectName: "Mathematics", marksObtained: 95, totalMarks: 100, percentage: 95, grade: "A1", status: "PASS", remarks: "Top of class", enteredBy: "Mrs. Sunita Rao", enteredAt: "2026-08-25T10:15:00Z" },
  { id: "mk-005", examScheduleId: "es-006", studentId: "stu-12-05", studentName: "Dev Malhotra", studentRoll: "STU-1205", subjectId: "sub-1201", subjectName: "Mathematics", marksObtained: 65, totalMarks: 100, percentage: 65, grade: "B2", status: "PASS", remarks: "Needs practice in determinants", enteredBy: "Mrs. Sunita Rao", enteredAt: "2026-08-25T10:20:00Z" },

  { id: "mk-006", examScheduleId: "es-007", studentId: "stu-12-01", studentName: "Arjun Nair", studentRoll: "STU-1201", subjectId: "sub-1202", subjectName: "Physics", marksObtained: 88, totalMarks: 100, percentage: 88, grade: "A2", status: "PASS", remarks: "Strong numericals understanding", enteredBy: "Mr. Rajesh Kulkarni", enteredAt: "2026-08-25T11:00:00Z" },
  { id: "mk-007", examScheduleId: "es-007", studentId: "stu-12-02", studentName: "Kavya Iyer", studentRoll: "STU-1202", subjectId: "sub-1202", subjectName: "Physics", marksObtained: 82, totalMarks: 100, percentage: 82, grade: "A2", status: "PASS", remarks: "Good lab record and theory", enteredBy: "Mr. Rajesh Kulkarni", enteredAt: "2026-08-25T11:05:00Z" },
  { id: "mk-008", examScheduleId: "es-007", studentId: "stu-12-03", studentName: "Rohan Gupta", studentRoll: "STU-1203", subjectId: "sub-1202", subjectName: "Physics", marksObtained: 71, totalMarks: 100, percentage: 71, grade: "B1", status: "PASS", remarks: "Solid but needs more numerical practice", enteredBy: "Mr. Rajesh Kulkarni", enteredAt: "2026-08-25T11:10:00Z" },
  { id: "mk-009", examScheduleId: "es-007", studentId: "stu-12-04", studentName: "Anika Verma", studentRoll: "STU-1204", subjectId: "sub-1202", subjectName: "Physics", marksObtained: 91, totalMarks: 100, percentage: 91, grade: "A1", status: "PASS", remarks: "Excellent derivations and diagrams", enteredBy: "Mr. Rajesh Kulkarni", enteredAt: "2026-08-25T11:15:00Z" },
  { id: "mk-010", examScheduleId: "es-007", studentId: "stu-12-05", studentName: "Dev Malhotra", studentRoll: "STU-1205", subjectId: "sub-1202", subjectName: "Physics", marksObtained: 58, totalMarks: 100, percentage: 58, grade: "C1", status: "PASS", remarks: "Below expectations. Extra class recommended.", enteredBy: "Mr. Rajesh Kulkarni", enteredAt: "2026-08-25T11:20:00Z" },

  { id: "mk-011", examScheduleId: "es-008", studentId: "stu-12-01", studentName: "Arjun Nair", studentRoll: "STU-1201", subjectId: "sub-1203", subjectName: "Chemistry", marksObtained: 85, totalMarks: 100, percentage: 85, grade: "A2", status: "PASS", remarks: "Good organic conversions", enteredBy: "Mrs. Sunita Rao", enteredAt: "2026-08-25T12:00:00Z" },
  { id: "mk-012", examScheduleId: "es-008", studentId: "stu-12-02", studentName: "Kavya Iyer", studentRoll: "STU-1202", subjectId: "sub-1203", subjectName: "Chemistry", marksObtained: 90, totalMarks: 100, percentage: 90, grade: "A2", status: "PASS", remarks: "Neat salt analysis record", enteredBy: "Mrs. Sunita Rao", enteredAt: "2026-08-25T12:05:00Z" },
  { id: "mk-013", examScheduleId: "es-008", studentId: "stu-12-03", studentName: "Rohan Gupta", studentRoll: "STU-1203", subjectId: "sub-1203", subjectName: "Chemistry", marksObtained: 76, totalMarks: 100, percentage: 76, grade: "B1", status: "PASS", remarks: "Good chemical equations", enteredBy: "Mrs. Sunita Rao", enteredAt: "2026-08-25T12:10:00Z" },
  { id: "mk-014", examScheduleId: "es-008", studentId: "stu-12-04", studentName: "Anika Verma", studentRoll: "STU-1204", subjectId: "sub-1203", subjectName: "Chemistry", marksObtained: 93, totalMarks: 100, percentage: 93, grade: "A1", status: "PASS", remarks: "Exceptional clarity in physical chemistry", enteredBy: "Mrs. Sunita Rao", enteredAt: "2026-08-25T12:15:00Z" },
  { id: "mk-015", examScheduleId: "es-008", studentId: "stu-12-05", studentName: "Dev Malhotra", studentRoll: "STU-1205", subjectId: "sub-1203", subjectName: "Chemistry", marksObtained: 68, totalMarks: 100, percentage: 68, grade: "B2", status: "PASS", remarks: "Needs to revise named reactions", enteredBy: "Mrs. Sunita Rao", enteredAt: "2026-08-25T12:20:00Z" },
];

export const initialResults: Result[] = [
  {
    id: "res-001",
    studentId: "stu-12-01",
    studentName: "Arjun Nair",
    studentRoll: "STU-1201",
    classId: "cls-g12",
    className: "Grade 12",
    sectionId: "sec-g12-a",
    sectionName: "Section A (Ivy Placement)",
    branchId: "br-apex-01",
    branchName: "Apex Global Campus",
    examTypeId: "ety-002",
    examTypeName: "Half-Yearly Examination",
    academicYear: "2026-2027",
    totalMarks: 300,
    marksObtained: 265,
    percentage: 88.33,
    overallGrade: "A2",
    gpa: 3.7,
    rank: 2,
    totalStudents: 34,
    status: "PASS",
    subjects: [
      { subjectId: "sub-1201", subjectName: "Mathematics", marksObtained: 92, totalMarks: 100, percentage: 92, grade: "A1", status: "PASS" },
      { subjectId: "sub-1202", subjectName: "Physics", marksObtained: 88, totalMarks: 100, percentage: 88, grade: "A2", status: "PASS" },
      { subjectId: "sub-1203", subjectName: "Chemistry", marksObtained: 85, totalMarks: 100, percentage: 85, grade: "A2", status: "PASS" },
    ],
    remarks: "Excellent overall performance. Keep it up!",
    createdAt: "2026-08-26T10:00:00Z",
    updatedAt: "2026-08-26T10:00:00Z",
  },
  {
    id: "res-002",
    studentId: "stu-12-02",
    studentName: "Kavya Iyer",
    studentRoll: "STU-1202",
    classId: "cls-g12",
    className: "Grade 12",
    sectionId: "sec-g12-a",
    sectionName: "Section A (Ivy Placement)",
    branchId: "br-apex-01",
    branchName: "Apex Global Campus",
    examTypeId: "ety-002",
    examTypeName: "Half-Yearly Examination",
    academicYear: "2026-2027",
    totalMarks: 300,
    marksObtained: 259,
    percentage: 86.33,
    overallGrade: "A2",
    gpa: 3.7,
    rank: 3,
    totalStudents: 34,
    status: "PASS",
    subjects: [
      { subjectId: "sub-1201", subjectName: "Mathematics", marksObtained: 87, totalMarks: 100, percentage: 87, grade: "A2", status: "PASS" },
      { subjectId: "sub-1202", subjectName: "Physics", marksObtained: 82, totalMarks: 100, percentage: 82, grade: "A2", status: "PASS" },
      { subjectId: "sub-1203", subjectName: "Chemistry", marksObtained: 90, totalMarks: 100, percentage: 90, grade: "A2", status: "PASS" },
    ],
    remarks: "Consistent performance across all subjects.",
    createdAt: "2026-08-26T10:00:00Z",
    updatedAt: "2026-08-26T10:00:00Z",
  },
  {
    id: "res-003",
    studentId: "stu-12-03",
    studentName: "Rohan Gupta",
    studentRoll: "STU-1203",
    classId: "cls-g12",
    className: "Grade 12",
    sectionId: "sec-g12-a",
    sectionName: "Section A (Ivy Placement)",
    branchId: "br-apex-01",
    branchName: "Apex Global Campus",
    examTypeId: "ety-002",
    examTypeName: "Half-Yearly Examination",
    academicYear: "2026-2027",
    totalMarks: 300,
    marksObtained: 225,
    percentage: 75.0,
    overallGrade: "B1",
    gpa: 3.3,
    rank: 4,
    totalStudents: 34,
    status: "PASS",
    subjects: [
      { subjectId: "sub-1201", subjectName: "Mathematics", marksObtained: 78, totalMarks: 100, percentage: 78, grade: "B1", status: "PASS" },
      { subjectId: "sub-1202", subjectName: "Physics", marksObtained: 71, totalMarks: 100, percentage: 71, grade: "B1", status: "PASS" },
      { subjectId: "sub-1203", subjectName: "Chemistry", marksObtained: 76, totalMarks: 100, percentage: 76, grade: "B1", status: "PASS" },
    ],
    remarks: "Good performance. Focus on revision speed.",
    createdAt: "2026-08-26T10:00:00Z",
    updatedAt: "2026-08-26T10:00:00Z",
  },
  {
    id: "res-004",
    studentId: "stu-12-04",
    studentName: "Anika Verma",
    studentRoll: "STU-1204",
    classId: "cls-g12",
    className: "Grade 12",
    sectionId: "sec-g12-a",
    sectionName: "Section A (Ivy Placement)",
    branchId: "br-apex-01",
    branchName: "Apex Global Campus",
    examTypeId: "ety-002",
    examTypeName: "Half-Yearly Examination",
    academicYear: "2026-2027",
    totalMarks: 300,
    marksObtained: 279,
    percentage: 93.0,
    overallGrade: "A1",
    gpa: 4.0,
    rank: 1,
    totalStudents: 34,
    status: "PASS",
    subjects: [
      { subjectId: "sub-1201", subjectName: "Mathematics", marksObtained: 95, totalMarks: 100, percentage: 95, grade: "A1", status: "PASS" },
      { subjectId: "sub-1202", subjectName: "Physics", marksObtained: 91, totalMarks: 100, percentage: 91, grade: "A1", status: "PASS" },
      { subjectId: "sub-1203", subjectName: "Chemistry", marksObtained: 93, totalMarks: 100, percentage: 93, grade: "A1", status: "PASS" },
    ],
    remarks: "School topper! Exceptional work.",
    createdAt: "2026-08-26T10:00:00Z",
    updatedAt: "2026-08-26T10:00:00Z",
  },
  {
    id: "res-005",
    studentId: "stu-12-05",
    studentName: "Dev Malhotra",
    studentRoll: "STU-1205",
    classId: "cls-g12",
    className: "Grade 12",
    sectionId: "sec-g12-a",
    sectionName: "Section A (Ivy Placement)",
    branchId: "br-apex-01",
    branchName: "Apex Global Campus",
    examTypeId: "ety-002",
    examTypeName: "Half-Yearly Examination",
    academicYear: "2026-2027",
    totalMarks: 300,
    marksObtained: 191,
    percentage: 63.67,
    overallGrade: "B2",
    gpa: 3.0,
    rank: 5,
    totalStudents: 34,
    status: "PASS",
    subjects: [
      { subjectId: "sub-1201", subjectName: "Mathematics", marksObtained: 65, totalMarks: 100, percentage: 65, grade: "B2", status: "PASS" },
      { subjectId: "sub-1202", subjectName: "Physics", marksObtained: 58, totalMarks: 100, percentage: 58, grade: "C1", status: "PASS" },
      { subjectId: "sub-1203", subjectName: "Chemistry", marksObtained: 68, totalMarks: 100, percentage: 68, grade: "B2", status: "PASS" },
    ],
    remarks: "Needs improvement. PTM scheduled with parents.",
    createdAt: "2026-08-26T10:00:00Z",
    updatedAt: "2026-08-26T10:00:00Z",
  },
];
