import { ExamType, ExamSchedule, MarkEntry, GradeScale, Result } from "@/types";

export const initialExamTypes: ExamType[] = [
  { id: "ety-001", name: "Unit Test 1", category: "UNIT_TEST", description: "First unit assessment covering initial chapters", maxMarks: 50, passingMarks: 18, weightage: 10, branchId: "all" },
  { id: "ety-002", name: "Mid-Term Examination", category: "MIDTERM", description: "Half-yearly comprehensive exam covering syllabus up to mid-term", maxMarks: 100, passingMarks: 35, weightage: 25, branchId: "all" },
  { id: "ety-003", name: "Final Examination", category: "FINAL", description: "End-of-year comprehensive examination", maxMarks: 100, passingMarks: 35, weightage: 40, branchId: "all" },
  { id: "ety-004", name: "Quarterly Assessment", category: "QUARTERLY", description: "Quarterly progress assessment", maxMarks: 50, passingMarks: 18, weightage: 15, branchId: "all" },
  { id: "ety-005", name: "Practical Examination", category: "CUSTOM", description: "Lab and practical skills assessment", maxMarks: 50, passingMarks: 20, weightage: 10, branchId: "all" },
];

export const initialGradeScale: GradeScale[] = [
  { id: "gs-01", grade: "A+", minPercentage: 90, maxPercentage: 100, gpa: 4.0, description: "Outstanding", color: "emerald" },
  { id: "gs-02", grade: "A", minPercentage: 80, maxPercentage: 89.99, gpa: 3.7, description: "Excellent", color: "emerald" },
  { id: "gs-03", grade: "B+", minPercentage: 70, maxPercentage: 79.99, gpa: 3.3, description: "Very Good", color: "blue" },
  { id: "gs-04", grade: "B", minPercentage: 60, maxPercentage: 69.99, gpa: 3.0, description: "Good", color: "blue" },
  { id: "gs-05", grade: "C+", minPercentage: 50, maxPercentage: 59.99, gpa: 2.3, description: "Average", color: "amber" },
  { id: "gs-06", grade: "C", minPercentage: 40, maxPercentage: 49.99, gpa: 2.0, description: "Below Average", color: "amber" },
  { id: "gs-07", grade: "D", minPercentage: 33, maxPercentage: 39.99, gpa: 1.0, description: "Poor", color: "rose" },
  { id: "gs-08", grade: "F", minPercentage: 0, maxPercentage: 32.99, gpa: 0.0, description: "Fail", color: "rose" },
];

export const initialExamSchedules: ExamSchedule[] = [
  // Mid-Term Exams - Grade 10
  { id: "es-001", examName: "Mid-Term - Mathematics", examTypeId: "ety-002", examTypeName: "Mid-Term Examination", classId: "cls-g10", className: "Grade 10", sectionId: "sec-g10-a", sectionName: "Section A (STEM Honors)", subjectId: "sub-101", subjectName: "Honors Mathematics", branchId: "br-apex-01", branchName: "Apex Global Campus", examDate: "2026-09-15", startTime: "09:00", endTime: "12:00", room: "Room 301", status: "SCHEDULED", totalMarks: 100, passingMarks: 35 },
  { id: "es-002", examName: "Mid-Term - Physics", examTypeId: "ety-002", examTypeName: "Mid-Term Examination", classId: "cls-g10", className: "Grade 10", sectionId: "sec-g10-a", sectionName: "Section A (STEM Honors)", subjectId: "sub-102", subjectName: "General Physics", branchId: "br-apex-01", branchName: "Apex Global Campus", examDate: "2026-09-16", startTime: "09:00", endTime: "12:00", room: "Physics Lab 3", status: "SCHEDULED", totalMarks: 100, passingMarks: 35 },
  { id: "es-003", examName: "Mid-Term - Computer Science", examTypeId: "ety-002", examTypeName: "Mid-Term Examination", classId: "cls-g10", className: "Grade 10", sectionId: "sec-g10-a", sectionName: "Section A (STEM Honors)", subjectId: "sub-103", subjectName: "Computer Science Principles", branchId: "br-apex-01", branchName: "Apex Global Campus", examDate: "2026-09-17", startTime: "09:00", endTime: "11:30", room: "Tech Lab 12", status: "SCHEDULED", totalMarks: 100, passingMarks: 35 },

  // Unit Test - Grade 9
  { id: "es-004", examName: "Unit Test 1 - Algebra", examTypeId: "ety-001", examTypeName: "Unit Test 1", classId: "cls-g9", className: "Grade 9", sectionId: "sec-g9-a", sectionName: "Section Alpha (Robotics Core)", subjectId: "sub-901", subjectName: "Integrated Algebra & Geometry", branchId: "br-west-02", branchName: "Westside STEM & Innovation Academy", examDate: "2026-09-08", startTime: "10:00", endTime: "11:30", room: "Room 108", status: "SCHEDULED", totalMarks: 50, passingMarks: 18 },
  { id: "es-005", examName: "Unit Test 1 - Robotics", examTypeId: "ety-001", examTypeName: "Unit Test 1", classId: "cls-g9", className: "Grade 9", sectionId: "sec-g9-a", sectionName: "Section Alpha (Robotics Core)", subjectId: "sub-902", subjectName: "Introductory Robotics & Coding", branchId: "br-west-02", branchName: "Westside STEM & Innovation Academy", examDate: "2026-09-09", startTime: "10:00", endTime: "12:00", room: "Tech Lab 12", status: "SCHEDULED", totalMarks: 50, passingMarks: 18 },

  // Completed Mid-Term - Grade 12
  { id: "es-006", examName: "Mid-Term - AP Calculus BC", examTypeId: "ety-002", examTypeName: "Mid-Term Examination", classId: "cls-g12", className: "Grade 12", sectionId: "sec-g12-a", sectionName: "Section A (Ivy Placement)", subjectId: "sub-1201", subjectName: "AP Calculus BC", branchId: "br-apex-01", branchName: "Apex Global Campus", examDate: "2026-08-20", startTime: "09:00", endTime: "12:00", room: "Senior Quad 1", status: "COMPLETED", totalMarks: 100, passingMarks: 35 },
  { id: "es-007", examName: "Mid-Term - AP Physics C", examTypeId: "ety-002", examTypeName: "Mid-Term Examination", classId: "cls-g12", className: "Grade 12", sectionId: "sec-g12-a", sectionName: "Section A (Ivy Placement)", subjectId: "sub-1202", subjectName: "AP Physics C", branchId: "br-apex-01", branchName: "Apex Global Campus", examDate: "2026-08-21", startTime: "09:00", endTime: "12:00", room: "Physics Lab 3", status: "COMPLETED", totalMarks: 100, passingMarks: 35 },
  { id: "es-008", examName: "Mid-Term - TOK", examTypeId: "ety-002", examTypeName: "Mid-Term Examination", classId: "cls-g12", className: "Grade 12", sectionId: "sec-g12-a", sectionName: "Section A (Ivy Placement)", subjectId: "sub-1203", subjectName: "Theory of Knowledge (TOK)", branchId: "br-apex-01", branchName: "Apex Global Campus", examDate: "2026-08-22", startTime: "09:00", endTime: "11:30", room: "Senior Quad 1", status: "COMPLETED", totalMarks: 100, passingMarks: 35 },
];

export const initialMarkEntries: MarkEntry[] = [
  // Grade 12 Mid-Term Results
  { id: "mk-001", examScheduleId: "es-006", studentId: "stu-12-01", studentName: "Arjun Nair", studentRoll: "STU-1201", subjectId: "sub-1201", subjectName: "AP Calculus BC", marksObtained: 92, totalMarks: 100, percentage: 92, grade: "A+", status: "PASS", remarks: "Outstanding performance", enteredBy: "Dr. Sarah Lin", enteredAt: "2026-08-25T10:00:00Z" },
  { id: "mk-002", examScheduleId: "es-006", studentId: "stu-12-02", studentName: "Kavya Iyer", studentRoll: "STU-1202", subjectId: "sub-1201", subjectName: "AP Calculus BC", marksObtained: 87, totalMarks: 100, percentage: 87, grade: "A", status: "PASS", remarks: "Excellent analytical skills", enteredBy: "Dr. Sarah Lin", enteredAt: "2026-08-25T10:05:00Z" },
  { id: "mk-003", examScheduleId: "es-006", studentId: "stu-12-03", studentName: "Rohan Gupta", studentRoll: "STU-1203", subjectId: "sub-1201", subjectName: "AP Calculus BC", marksObtained: 78, totalMarks: 100, percentage: 78, grade: "B+", status: "PASS", remarks: "Good grasp of integration concepts", enteredBy: "Dr. Sarah Lin", enteredAt: "2026-08-25T10:10:00Z" },
  { id: "mk-004", examScheduleId: "es-006", studentId: "stu-12-04", studentName: "Anika Verma", studentRoll: "STU-1204", subjectId: "sub-1201", subjectName: "AP Calculus BC", marksObtained: 95, totalMarks: 100, percentage: 95, grade: "A+", status: "PASS", remarks: "Top of class", enteredBy: "Dr. Sarah Lin", enteredAt: "2026-08-25T10:15:00Z" },
  { id: "mk-005", examScheduleId: "es-006", studentId: "stu-12-05", studentName: "Dev Malhotra", studentRoll: "STU-1205", subjectId: "sub-1201", subjectName: "AP Calculus BC", marksObtained: 65, totalMarks: 100, percentage: 65, grade: "B", status: "PASS", remarks: "Needs improvement in series convergence", enteredBy: "Dr. Sarah Lin", enteredAt: "2026-08-25T10:20:00Z" },

  { id: "mk-006", examScheduleId: "es-007", studentId: "stu-12-01", studentName: "Arjun Nair", studentRoll: "STU-1201", subjectId: "sub-1202", subjectName: "AP Physics C", marksObtained: 88, totalMarks: 100, percentage: 88, grade: "A", status: "PASS", remarks: "Strong mechanics understanding", enteredBy: "Prof. Marcus Brody", enteredAt: "2026-08-25T11:00:00Z" },
  { id: "mk-007", examScheduleId: "es-007", studentId: "stu-12-02", studentName: "Kavya Iyer", studentRoll: "STU-1202", subjectId: "sub-1202", subjectName: "AP Physics C", marksObtained: 82, totalMarks: 100, percentage: 82, grade: "A", status: "PASS", remarks: "Good lab work and theory", enteredBy: "Prof. Marcus Brody", enteredAt: "2026-08-25T11:05:00Z" },
  { id: "mk-008", examScheduleId: "es-007", studentId: "stu-12-03", studentName: "Rohan Gupta", studentRoll: "STU-1203", subjectId: "sub-1202", subjectName: "AP Physics C", marksObtained: 71, totalMarks: 100, percentage: 71, grade: "B+", status: "PASS", remarks: "Solid but needs more practice problems", enteredBy: "Prof. Marcus Brody", enteredAt: "2026-08-25T11:10:00Z" },
  { id: "mk-009", examScheduleId: "es-007", studentId: "stu-12-04", studentName: "Anika Verma", studentRoll: "STU-1204", subjectId: "sub-1202", subjectName: "AP Physics C", marksObtained: 91, totalMarks: 100, percentage: 91, grade: "A+", status: "PASS", remarks: "Excellent problem-solving skills", enteredBy: "Prof. Marcus Brody", enteredAt: "2026-08-25T11:15:00Z" },
  { id: "mk-010", examScheduleId: "es-007", studentId: "stu-12-05", studentName: "Dev Malhotra", studentRoll: "STU-1205", subjectId: "sub-1202", subjectName: "AP Physics C", marksObtained: 58, totalMarks: 100, percentage: 58, grade: "C+", status: "PASS", remarks: "Below expectations. See me for extra tutoring.", enteredBy: "Prof. Marcus Brody", enteredAt: "2026-08-25T11:20:00Z" },

  { id: "mk-011", examScheduleId: "es-008", studentId: "stu-12-01", studentName: "Arjun Nair", studentRoll: "STU-1201", subjectId: "sub-1203", subjectName: "Theory of Knowledge (TOK)", marksObtained: 85, totalMarks: 100, percentage: 85, grade: "A", status: "PASS", remarks: "Insightful essay on knowledge frameworks", enteredBy: "Dr. Nigel Ross", enteredAt: "2026-08-25T12:00:00Z" },
  { id: "mk-012", examScheduleId: "es-008", studentId: "stu-12-02", studentName: "Kavya Iyer", studentRoll: "STU-1202", subjectId: "sub-1203", subjectName: "Theory of Knowledge (TOK)", marksObtained: 90, totalMarks: 100, percentage: 90, grade: "A+", status: "PASS", remarks: "Outstanding presentation and exhibition", enteredBy: "Dr. Nigel Ross", enteredAt: "2026-08-25T12:05:00Z" },
  { id: "mk-013", examScheduleId: "es-008", studentId: "stu-12-03", studentName: "Rohan Gupta", studentRoll: "STU-1203", subjectId: "sub-1203", subjectName: "Theory of Knowledge (TOK)", marksObtained: 76, totalMarks: 100, percentage: 76, grade: "B+", status: "PASS", remarks: "Good critical analysis in essay", enteredBy: "Dr. Nigel Ross", enteredAt: "2026-08-25T12:10:00Z" },
  { id: "mk-014", examScheduleId: "es-008", studentId: "stu-12-04", studentName: "Anika Verma", studentRoll: "STU-1204", subjectId: "sub-1203", subjectName: "Theory of Knowledge (TOK)", marksObtained: 93, totalMarks: 100, percentage: 93, grade: "A+", status: "PASS", remarks: "Exceptional clarity of thought", enteredBy: "Dr. Nigel Ross", enteredAt: "2026-08-25T12:15:00Z" },
  { id: "mk-015", examScheduleId: "es-008", studentId: "stu-12-05", studentName: "Dev Malhotra", studentRoll: "STU-1205", subjectId: "sub-1203", subjectName: "Theory of Knowledge (TOK)", marksObtained: 68, totalMarks: 100, percentage: 68, grade: "B", status: "PASS", remarks: "Needs to develop argumentation skills", enteredBy: "Dr. Nigel Ross", enteredAt: "2026-08-25T12:20:00Z" },
];

export const initialResults: Result[] = [
  {
    id: "res-001",
    studentId: "stu-12-01",
    studentName: "Arjun Nair",
    studentRoll: "STU-1201",
    classId: "cls-g12",
    className: "Grade 12",
    sectionId: "sec-g12-a",
    sectionName: "Section A (Ivy Placement)",
    branchId: "br-apex-01",
    branchName: "Apex Global Campus",
    examTypeId: "ety-002",
    examTypeName: "Mid-Term Examination",
    academicYear: "2026-2027",
    totalMarks: 300,
    marksObtained: 265,
    percentage: 88.33,
    overallGrade: "A",
    gpa: 3.7,
    rank: 2,
    totalStudents: 34,
    status: "PASS",
    subjects: [
      { subjectId: "sub-1201", subjectName: "AP Calculus BC", marksObtained: 92, totalMarks: 100, percentage: 92, grade: "A+", status: "PASS" },
      { subjectId: "sub-1202", subjectName: "AP Physics C", marksObtained: 88, totalMarks: 100, percentage: 88, grade: "A", status: "PASS" },
      { subjectId: "sub-1203", subjectName: "Theory of Knowledge (TOK)", marksObtained: 85, totalMarks: 100, percentage: 85, grade: "A", status: "PASS" },
    ],
    remarks: "Excellent overall performance. Keep it up!",
    createdAt: "2026-08-26T10:00:00Z",
    updatedAt: "2026-08-26T10:00:00Z",
  },
  {
    id: "res-002",
    studentId: "stu-12-02",
    studentName: "Kavya Iyer",
    studentRoll: "STU-1202",
    classId: "cls-g12",
    className: "Grade 12",
    sectionId: "sec-g12-a",
    sectionName: "Section A (Ivy Placement)",
    branchId: "br-apex-01",
    branchName: "Apex Global Campus",
    examTypeId: "ety-002",
    examTypeName: "Mid-Term Examination",
    academicYear: "2026-2027",
    totalMarks: 300,
    marksObtained: 259,
    percentage: 86.33,
    overallGrade: "A",
    gpa: 3.7,
    rank: 3,
    totalStudents: 34,
    status: "PASS",
    subjects: [
      { subjectId: "sub-1201", subjectName: "AP Calculus BC", marksObtained: 87, totalMarks: 100, percentage: 87, grade: "A", status: "PASS" },
      { subjectId: "sub-1202", subjectName: "AP Physics C", marksObtained: 82, totalMarks: 100, percentage: 82, grade: "A", status: "PASS" },
      { subjectId: "sub-1203", subjectName: "Theory of Knowledge (TOK)", marksObtained: 90, totalMarks: 100, percentage: 90, grade: "A+", status: "PASS" },
    ],
    remarks: "Consistent performance across all subjects.",
    createdAt: "2026-08-26T10:00:00Z",
    updatedAt: "2026-08-26T10:00:00Z",
  },
  {
    id: "res-003",
    studentId: "stu-12-03",
    studentName: "Rohan Gupta",
    studentRoll: "STU-1203",
    classId: "cls-g12",
    className: "Grade 12",
    sectionId: "sec-g12-a",
    sectionName: "Section A (Ivy Placement)",
    branchId: "br-apex-01",
    branchName: "Apex Global Campus",
    examTypeId: "ety-002",
    examTypeName: "Mid-Term Examination",
    academicYear: "2026-2027",
    totalMarks: 300,
    marksObtained: 225,
    percentage: 75.0,
    overallGrade: "B+",
    gpa: 3.3,
    rank: 4,
    totalStudents: 34,
    status: "PASS",
    subjects: [
      { subjectId: "sub-1201", subjectName: "AP Calculus BC", marksObtained: 78, totalMarks: 100, percentage: 78, grade: "B+", status: "PASS" },
      { subjectId: "sub-1202", subjectName: "AP Physics C", marksObtained: 71, totalMarks: 100, percentage: 71, grade: "B+", status: "PASS" },
      { subjectId: "sub-1203", subjectName: "Theory of Knowledge (TOK)", marksObtained: 76, totalMarks: 100, percentage: 76, grade: "B+", status: "PASS" },
    ],
    remarks: "Good performance. Focus on problem-solving speed.",
    createdAt: "2026-08-26T10:00:00Z",
    updatedAt: "2026-08-26T10:00:00Z",
  },
  {
    id: "res-004",
    studentId: "stu-12-04",
    studentName: "Anika Verma",
    studentRoll: "STU-1204",
    classId: "cls-g12",
    className: "Grade 12",
    sectionId: "sec-g12-a",
    sectionName: "Section A (Ivy Placement)",
    branchId: "br-apex-01",
    branchName: "Apex Global Campus",
    examTypeId: "ety-002",
    examTypeName: "Mid-Term Examination",
    academicYear: "2026-2027",
    totalMarks: 300,
    marksObtained: 279,
    percentage: 93.0,
    overallGrade: "A+",
    gpa: 4.0,
    rank: 1,
    totalStudents: 34,
    status: "PASS",
    subjects: [
      { subjectId: "sub-1201", subjectName: "AP Calculus BC", marksObtained: 95, totalMarks: 100, percentage: 95, grade: "A+", status: "PASS" },
      { subjectId: "sub-1202", subjectName: "AP Physics C", marksObtained: 91, totalMarks: 100, percentage: 91, grade: "A+", status: "PASS" },
      { subjectId: "sub-1203", subjectName: "Theory of Knowledge (TOK)", marksObtained: 93, totalMarks: 100, percentage: 93, grade: "A+", status: "PASS" },
    ],
    remarks: "Toppers of the class! Exceptional work.",
    createdAt: "2026-08-26T10:00:00Z",
    updatedAt: "2026-08-26T10:00:00Z",
  },
  {
    id: "res-005",
    studentId: "stu-12-05",
    studentName: "Dev Malhotra",
    studentRoll: "STU-1205",
    classId: "cls-g12",
    className: "Grade 12",
    sectionId: "sec-g12-a",
    sectionName: "Section A (Ivy Placement)",
    branchId: "br-apex-01",
    branchName: "Apex Global Campus",
    examTypeId: "ety-002",
    examTypeName: "Mid-Term Examination",
    academicYear: "2026-2027",
    totalMarks: 300,
    marksObtained: 191,
    percentage: 63.67,
    overallGrade: "B",
    gpa: 3.0,
    rank: 5,
    totalStudents: 34,
    status: "PASS",
    subjects: [
      { subjectId: "sub-1201", subjectName: "AP Calculus BC", marksObtained: 65, totalMarks: 100, percentage: 65, grade: "B", status: "PASS" },
      { subjectId: "sub-1202", subjectName: "AP Physics C", marksObtained: 58, totalMarks: 100, percentage: 58, grade: "C+", status: "PASS" },
      { subjectId: "sub-1203", subjectName: "Theory of Knowledge (TOK)", marksObtained: 68, totalMarks: 100, percentage: 68, grade: "B", status: "PASS" },
    ],
    remarks: "Needs improvement. Schedule parent-teacher meeting.",
    createdAt: "2026-08-26T10:00:00Z",
    updatedAt: "2026-08-26T10:00:00Z",
  },
];
