import { Homework, HomeworkSubmission } from "@/types";

export const initialHomework: Homework[] = [
  {
    id: "hw-001",
    title: "Quadratic Equations Problem Set",
    description: "Complete exercises 1-20 from Chapter 4. Show all working steps and verify each solution by substitution. Focus on factoring, completing the square, and the quadratic formula.",
    subjectId: "sub-101",
    subjectName: "Honors Mathematics",
    subjectCode: "MATH-10H",
    classId: "cls-g10",
    className: "Grade 10",
    sectionId: "sec-g10-a",
    sectionName: "Section A (STEM Honors)",
    branchId: "br-apex-01",
    branchName: "Apex Global Campus",
    teacherId: "tch-01",
    teacherName: "Dr. Sarah Lin",
    assignedDate: "2026-08-25",
    dueDate: "2026-09-01",
    maxMarks: 50,
    status: "ACTIVE",
    createdAt: "2026-08-25T09:00:00Z",
    updatedAt: "2026-08-25T09:00:00Z",
  },
  {
    id: "hw-002",
    title: "Physics Lab Report: Newton's Second Law",
    description: "Write a formal lab report for the inclined plane experiment. Include hypothesis, methodology, data tables, graphs, and conclusion. Use proper scientific notation.",
    subjectId: "sub-102",
    subjectName: "General Physics",
    subjectCode: "PHYS-10",
    classId: "cls-g10",
    className: "Grade 10",
    sectionId: "sec-g10-a",
    sectionName: "Section A (STEM Honors)",
    branchId: "br-apex-01",
    branchName: "Apex Global Campus",
    teacherId: "tch-02",
    teacherName: "Prof. Marcus Brody",
    assignedDate: "2026-08-26",
    dueDate: "2026-09-03",
    maxMarks: 30,
    status: "ACTIVE",
    createdAt: "2026-08-26T10:00:00Z",
    updatedAt: "2026-08-26T10:00:00Z",
  },
  {
    id: "hw-003",
    title: "Python Data Structures Assignment",
    description: "Implement a student record management system using lists, dictionaries, and tuples. Include functions for add, search, sort, and delete operations. Submit .py file.",
    subjectId: "sub-103",
    subjectName: "Computer Science Principles",
    subjectCode: "CS-10",
    classId: "cls-g10",
    className: "Grade 10",
    sectionId: "sec-g10-a",
    sectionName: "Section A (STEM Honors)",
    branchId: "br-apex-01",
    branchName: "Apex Global Campus",
    teacherId: "tch-03",
    teacherName: "Elena Rostova",
    assignedDate: "2026-08-27",
    dueDate: "2026-09-05",
    maxMarks: 40,
    status: "ACTIVE",
    createdAt: "2026-08-27T11:00:00Z",
    updatedAt: "2026-08-27T11:00:00Z",
  },
  {
    id: "hw-004",
    title: "Shakespeare Essay: Hamlet Analysis",
    description: "Write a 1200-word analytical essay on the theme of indecision in Hamlet. Cite at least 5 specific passages. MLA format required.",
    subjectId: "sub-104",
    subjectName: "World Literature",
    subjectCode: "LIT-10",
    classId: "cls-g10",
    className: "Grade 10",
    sectionId: "sec-g10-b",
    sectionName: "Section B (Humanities & Social)",
    branchId: "br-apex-01",
    branchName: "Apex Global Campus",
    teacherId: "tch-05",
    teacherName: "Dr. Nigel Ross",
    assignedDate: "2026-08-24",
    dueDate: "2026-09-02",
    maxMarks: 30,
    status: "ACTIVE",
    createdAt: "2026-08-24T09:00:00Z",
    updatedAt: "2026-08-24T09:00:00Z",
  },
  {
    id: "hw-005",
    title: "Robotics Challenge: Line Follower",
    description: "Design and build a line-following robot using the provided Arduino kit. Program must handle 90-degree turns and intersections. Submit code and a 2-minute demo video.",
    subjectId: "sub-902",
    subjectName: "Introductory Robotics & Coding",
    subjectCode: "ROB-09",
    classId: "cls-g9",
    className: "Grade 9",
    sectionId: "sec-g9-a",
    sectionName: "Section Alpha (Robotics Core)",
    branchId: "br-west-02",
    branchName: "Westside STEM & Innovation Academy",
    teacherId: "tch-03",
    teacherName: "Elena Rostova",
    assignedDate: "2026-08-28",
    dueDate: "2026-09-10",
    maxMarks: 60,
    status: "ACTIVE",
    createdAt: "2026-08-28T10:00:00Z",
    updatedAt: "2026-08-28T10:00:00Z",
  },
  {
    id: "hw-006",
    title: "Biology Cell Division Worksheet",
    description: "Complete the mitosis and meiosis comparison worksheet. Include labeled diagrams of each phase and explain the biological significance of genetic variation.",
    subjectId: "sub-903",
    subjectName: "Biological Foundations",
    subjectCode: "BIO-09",
    classId: "cls-g9",
    className: "Grade 9",
    sectionId: "sec-g9-b",
    sectionName: "Section Beta (Applied Bio-Tech)",
    branchId: "br-west-02",
    branchName: "Westside STEM & Innovation Academy",
    teacherId: "tch-02",
    teacherName: "Prof. Marcus Brody",
    assignedDate: "2026-08-25",
    dueDate: "2026-08-30",
    maxMarks: 25,
    status: "COMPLETED",
    createdAt: "2026-08-25T14:00:00Z",
    updatedAt: "2026-08-30T12:00:00Z",
  },
  {
    id: "hw-007",
    title: "Calculus Integration Practice",
    description: "Solve integration problems using substitution, by parts, and partial fractions. Include real-world applications in physics and engineering contexts.",
    subjectId: "sub-1201",
    subjectName: "AP Calculus BC",
    subjectCode: "AP-CALC-BC",
    classId: "cls-g12",
    className: "Grade 12",
    sectionId: "sec-g12-a",
    sectionName: "Section A (Ivy Placement)",
    branchId: "br-apex-01",
    branchName: "Apex Global Campus",
    teacherId: "tch-01",
    teacherName: "Dr. Sarah Lin",
    assignedDate: "2026-08-29",
    dueDate: "2026-09-05",
    maxMarks: 45,
    status: "ACTIVE",
    createdAt: "2026-08-29T09:00:00Z",
    updatedAt: "2026-08-29T09:00:00Z",
  },
  {
    id: "hw-008",
    title: "Art Portfolio: Still Life Collection",
    description: "Create 3 still life sketches using pencil, charcoal, and watercolor. Focus on light, shadow, and composition. Mount on A3 boards for classroom display.",
    subjectId: "sub-105",
    subjectName: "Studio Art & Design",
    subjectCode: "ART-10",
    classId: "cls-g10",
    className: "Grade 10",
    sectionId: "sec-g10-arts",
    sectionName: "Section D (Arts & Media)",
    branchId: "br-apex-01",
    branchName: "Apex Global Campus",
    teacherId: "tch-06",
    teacherName: "Camilla Rossi",
    assignedDate: "2026-08-22",
    dueDate: "2026-09-08",
    maxMarks: 35,
    status: "ACTIVE",
    createdAt: "2026-08-22T11:00:00Z",
    updatedAt: "2026-08-22T11:00:00Z",
  },
  {
    id: "hw-009",
    title: "Physics: Electromagnetic Induction Problems",
    description: "Solve 15 problems on Faraday's law and Lenz's law. Include diagrams and show all calculations with proper units.",
    subjectId: "sub-1102",
    subjectName: "AP Physics 1",
    subjectCode: "AP-PHYS-1",
    classId: "cls-g11",
    className: "Grade 11",
    sectionId: "sec-g11-a",
    sectionName: "AP STEM Scholars",
    branchId: "br-green-04",
    branchName: "Green Valley International School",
    teacherId: "tch-02",
    teacherName: "Prof. Marcus Brody",
    assignedDate: "2026-08-27",
    dueDate: "2026-09-04",
    maxMarks: 40,
    status: "ACTIVE",
    createdAt: "2026-08-27T10:00:00Z",
    updatedAt: "2026-08-27T10:00:00Z",
  },
  {
    id: "hw-010",
    title: "Mathematics Worksheet: Linear Equations",
    description: "Complete the linear equations worksheet covering slope-intercept form, point-slope form, and systems of equations. Show all steps.",
    subjectId: "sub-901",
    subjectName: "Integrated Algebra & Geometry",
    subjectCode: "MATH-09",
    classId: "cls-g9",
    className: "Grade 9",
    sectionId: "sec-g9-c",
    sectionName: "Section Gamma (Calculus Prep)",
    branchId: "br-west-02",
    branchName: "Westside STEM & Innovation Academy",
    teacherId: "tch-01",
    teacherName: "Dr. Sarah Lin",
    assignedDate: "2026-08-26",
    dueDate: "2026-08-29",
    maxMarks: 20,
    status: "COMPLETED",
    createdAt: "2026-08-26T09:00:00Z",
    updatedAt: "2026-08-29T15:00:00Z",
  },
];

export const initialHomeworkSubmissions: HomeworkSubmission[] = [
  // Submissions for hw-006 (completed homework)
  { id: "sub-001", homeworkId: "hw-006", studentId: "stu-01", studentName: "Aarav Mehta", studentRoll: "STU-1001", submissionDate: "2026-08-29", status: "GRADED", marksObtained: 22, remarks: "Good understanding of meiosis. Diagrams were clear." },
  { id: "sub-002", homeworkId: "hw-006", studentId: "stu-02", studentName: "Priya Sharma", studentRoll: "STU-1002", submissionDate: "2026-08-29", status: "GRADED", marksObtained: 24, remarks: "Excellent comparison chart. Minor labeling error on telophase." },
  { id: "sub-003", homeworkId: "hw-006", studentId: "stu-03", studentName: "Leo Rodriguez", studentRoll: "STU-1003", submissionDate: "2026-08-30", status: "GRADED", marksObtained: 20, remarks: "Solid work. Needs more detail on significance of crossing over." },
  { id: "sub-004", homeworkId: "hw-006", studentId: "stu-04", studentName: "Maya Chen", studentRoll: "STU-1004", submissionDate: "2026-08-29", status: "GRADED", marksObtained: 25, remarks: "Outstanding! Perfect diagrams and thorough explanation." },
  { id: "sub-005", homeworkId: "hw-006", studentId: "stu-05", studentName: "James Wilson", studentRoll: "STU-1005", submissionDate: "2026-08-28", status: "GRADED", marksObtained: 18, remarks: "Late submission. Content was good but needs proofreading." },

  // Submissions for hw-010 (completed homework)
  { id: "sub-006", homeworkId: "hw-010", studentId: "stu-06", studentName: "Sofia Kim", studentRoll: "STU-1006", submissionDate: "2026-08-28", status: "GRADED", marksObtained: 19, remarks: "Almost perfect. One error in systems of equations." },
  { id: "sub-007", homeworkId: "hw-010", studentId: "stu-07", studentName: "Ethan Patel", studentRoll: "STU-1007", submissionDate: "2026-08-29", status: "GRADED", marksObtained: 16, remarks: "Good effort. Slope calculations need review." },
  { id: "sub-008", homeworkId: "hw-010", studentId: "stu-08", studentName: "Zara Ahmed", studentRoll: "STU-1008", submissionDate: "2026-08-28", status: "GRADED", marksObtained: 20, remarks: "Perfect score! Clear, organized work." },

  // Partial submissions for active homework (hw-001)
  { id: "sub-009", homeworkId: "hw-001", studentId: "stu-01", studentName: "Aarav Mehta", studentRoll: "STU-1001", submissionDate: "2026-08-30", status: "SUBMITTED", remarks: "Submitted early. 18 of 20 problems completed." },
  { id: "sub-010", homeworkId: "hw-001", studentId: "stu-02", studentName: "Priya Sharma", studentRoll: "STU-1002", submissionDate: "2026-08-31", status: "SUBMITTED", remarks: "All problems completed." },
  { id: "sub-011", homeworkId: "hw-001", studentId: "stu-04", studentName: "Maya Chen", studentRoll: "STU-1004", submissionDate: "2026-08-30", status: "SUBMITTED", remarks: "Submitted with detailed solutions." },
];
