import { Homework, HomeworkSubmission } from "@/types";

export const initialHomework: Homework[] = [
  {
    id: "hw-001",
    title: "Quadratic Equations Problem Set",
    description: "Complete exercises 1-20 from Chapter 4. Show all working steps and verify each solution by substitution. Focus on factoring, completing the square, and the quadratic formula.",
    subjectId: "sub-101",
    subjectName: "Mathematics",
    subjectCode: "MATH-10",
    classId: "cls-g10",
    className: "Grade 10",
    sectionId: "sec-g10-a",
    sectionName: "Section A (STEM Honors)",
    branchId: "br-apex-01",
    branchName: "Apex Global Campus",
    teacherId: "tch-01",
    teacherName: "Mrs. Sunita Rao",
    assignedDate: "2026-08-25",
    dueDate: "2026-09-01",
    maxMarks: 50,
    status: "ACTIVE",
    homeworkType: "HW",
    priority: "HIGH",
    createdAt: "2026-08-25T09:00:00Z",
    updatedAt: "2026-08-25T09:00:00Z",
  },
  {
    id: "hw-002",
    title: "Science Activity: Light – Reflection Worksheet",
    description: "Complete NCERT Exemplar questions on reflection of light. Draw ray diagrams for concave mirror and write laws of reflection with two daily-life examples.",
    subjectId: "sub-102",
    subjectName: "Science",
    subjectCode: "SCI-10",
    classId: "cls-g10",
    className: "Grade 10",
    sectionId: "sec-g10-a",
    sectionName: "Section A (STEM Honors)",
    branchId: "br-apex-01",
    branchName: "Apex Global Campus",
    teacherId: "tch-02",
    teacherName: "Mr. Rajesh Kulkarni",
    assignedDate: "2026-08-26",
    dueDate: "2026-09-03",
    maxMarks: 30,
    status: "ACTIVE",
    homeworkType: "CW",
    priority: "MEDIUM",
    createdAt: "2026-08-26T10:00:00Z",
    updatedAt: "2026-08-26T10:00:00Z",
  },
  {
    id: "hw-003",
    title: "Python Data Structures Assignment",
    description: "Implement a student record management system using lists, dictionaries, and tuples. Include functions for add, search, sort, and delete operations. Submit .py file.",
    subjectId: "sub-103",
    subjectName: "Computer Science",
    subjectCode: "CS-10",
    classId: "cls-g10",
    className: "Grade 10",
    sectionId: "sec-g10-a",
    sectionName: "Section A (STEM Honors)",
    branchId: "br-apex-01",
    branchName: "Apex Global Campus",
    teacherId: "tch-03",
    teacherName: "Ms. Priya Menon",
    assignedDate: "2026-08-27",
    dueDate: "2026-09-05",
    maxMarks: 40,
    status: "ACTIVE",
    homeworkType: "ASSIGNMENT",
    priority: "HIGH",
    createdAt: "2026-08-27T11:00:00Z",
    updatedAt: "2026-08-27T11:00:00Z",
  },
  {
    id: "hw-004",
    title: "English Writing Skills: Notice & Diary Entry",
    description: "Draft a formal notice for the school annual function and a diary entry on sports day. Follow CBSE writing format (name, date, word limit).",
    subjectId: "sub-104",
    subjectName: "English",
    subjectCode: "ENG-10",
    classId: "cls-g10",
    className: "Grade 10",
    sectionId: "sec-g10-b",
    sectionName: "Section B (Humanities & Social)",
    branchId: "br-apex-01",
    branchName: "Apex Global Campus",
    teacherId: "tch-05",
    teacherName: "Mrs. Kavitha Subramaniam",
    assignedDate: "2026-08-24",
    dueDate: "2026-09-02",
    maxMarks: 30,
    status: "ACTIVE",
    homeworkType: "HW",
    priority: "MEDIUM",
    createdAt: "2026-08-24T09:00:00Z",
    updatedAt: "2026-08-24T09:00:00Z",
  },
  {
    id: "hw-005",
    title: "Robotics Challenge: Line Follower",
    description: "Design and build a line-following robot using the provided Arduino kit. Program must handle 90-degree turns and intersections. Submit code and a 2-minute demo video.",
    subjectId: "sub-902",
    subjectName: "Science",
    subjectCode: "SCI-09",
    classId: "cls-g9",
    className: "Grade 9",
    sectionId: "sec-g9-a",
    sectionName: "Section Alpha (Robotics Core)",
    branchId: "br-west-02",
    branchName: "Westside STEM & Innovation Academy",
    teacherId: "tch-03",
    teacherName: "Ms. Priya Menon",
    assignedDate: "2026-08-28",
    dueDate: "2026-09-10",
    maxMarks: 60,
    status: "ACTIVE",
    homeworkType: "PROJECT",
    priority: "HIGH",
    createdAt: "2026-08-28T10:00:00Z",
    updatedAt: "2026-08-28T10:00:00Z",
  },
  {
    id: "hw-006",
    title: "Biology Cell Division Worksheet",
    description: "Complete the mitosis and meiosis comparison worksheet. Include labeled diagrams of each phase and explain the biological significance of genetic variation.",
    subjectId: "sub-903",
    subjectName: "Social Science",
    subjectCode: "SST-09",
    classId: "cls-g9",
    className: "Grade 9",
    sectionId: "sec-g9-b",
    sectionName: "Section Beta (Applied Bio-Tech)",
    branchId: "br-west-02",
    branchName: "Westside STEM & Innovation Academy",
    teacherId: "tch-02",
    teacherName: "Mr. Rajesh Kulkarni",
    assignedDate: "2026-08-25",
    dueDate: "2026-08-30",
    maxMarks: 25,
    status: "COMPLETED",
    homeworkType: "CW",
    priority: "LOW",
    createdAt: "2026-08-25T14:00:00Z",
    updatedAt: "2026-08-30T12:00:00Z",
  },
  {
    id: "hw-007",
    title: "Maths Practice: Definite Integration (NCERT Ex 7.9)",
    description: "Solve NCERT Exercise 7.9 Q1–Q15 on definite integration. Show substitution steps clearly and verify answers with the NCERT solutions key.",
    subjectId: "sub-1201",
    subjectName: "Mathematics",
    subjectCode: "MATH-12",
    classId: "cls-g12",
    className: "Grade 12",
    sectionId: "sec-g12-a",
    sectionName: "Section A (Ivy Placement)",
    branchId: "br-apex-01",
    branchName: "Apex Global Campus",
    teacherId: "tch-01",
    teacherName: "Mrs. Sunita Rao",
    assignedDate: "2026-08-29",
    dueDate: "2026-09-05",
    maxMarks: 45,
    status: "ACTIVE",
    homeworkType: "HW",
    priority: "HIGH",
    createdAt: "2026-08-29T09:00:00Z",
    updatedAt: "2026-08-29T09:00:00Z",
  },
  {
    id: "hw-008",
    title: "Art Portfolio: Still Life Collection",
    description: "Create 3 still life sketches using pencil, charcoal, and watercolor. Focus on light, shadow, and composition. Mount on A3 boards for classroom display.",
    subjectId: "sub-105",
    subjectName: "Art Education",
    subjectCode: "ART-10",
    classId: "cls-g10",
    className: "Grade 10",
    sectionId: "sec-g10-arts",
    sectionName: "Section D (Arts & Media)",
    branchId: "br-apex-01",
    branchName: "Apex Global Campus",
    teacherId: "tch-06",
    teacherName: "Ms. Neha Kapoor",
    assignedDate: "2026-08-22",
    dueDate: "2026-09-08",
    maxMarks: 35,
    status: "ACTIVE",
    homeworkType: "PROJECT",
    priority: "MEDIUM",
    createdAt: "2026-08-22T11:00:00Z",
    updatedAt: "2026-08-22T11:00:00Z",
  },
  {
    id: "hw-009",
    title: "Physics Numerics: Electromagnetic Induction",
    description: "Solve 15 NCERT numericals on Faraday's law and Lenz's law. Draw circuit diagrams and show SI units in every step.",
    subjectId: "sub-1102",
    subjectName: "Physics",
    subjectCode: "PHY-11",
    classId: "cls-g11",
    className: "Grade 11",
    sectionId: "sec-g11-a",
    sectionName: "AP STEM Scholars",
    branchId: "br-green-04",
    branchName: "Green Valley International School",
    teacherId: "tch-02",
    teacherName: "Mr. Rajesh Kulkarni",
    assignedDate: "2026-08-27",
    dueDate: "2026-09-04",
    maxMarks: 40,
    status: "ACTIVE",
    homeworkType: "ASSIGNMENT",
    priority: "HIGH",
    createdAt: "2026-08-27T10:00:00Z",
    updatedAt: "2026-08-27T10:00:00Z",
  },
  {
    id: "hw-010",
    title: "Maths Worksheet: Pair of Linear Equations (Ch 3)",
    description: "Solve NCERT Class 9 Chapter 3 exercise on elimination and substitution methods. Check each answer by back-substitution.",
    subjectId: "sub-901",
    subjectName: "Mathematics",
    subjectCode: "MATH-09",
    classId: "cls-g9",
    className: "Grade 9",
    sectionId: "sec-g9-c",
    sectionName: "Section Gamma (Calculus Prep)",
    branchId: "br-west-02",
    branchName: "Westside STEM & Innovation Academy",
    teacherId: "tch-01",
    teacherName: "Mrs. Sunita Rao",
    assignedDate: "2026-08-26",
    dueDate: "2026-08-29",
    maxMarks: 20,
    status: "COMPLETED",
    homeworkType: "HW",
    priority: "MEDIUM",
    createdAt: "2026-08-26T09:00:00Z",
    updatedAt: "2026-08-29T15:00:00Z",
  },
];

export const initialHomeworkSubmissions: HomeworkSubmission[] = [
  // Submissions for hw-006 (completed homework)
  { id: "sub-001", homeworkId: "hw-006", studentId: "stu-01", studentName: "Aarav Mehta", studentRoll: "STU-1001", submissionDate: "2026-08-29", status: "GRADED", marksObtained: 22, remarks: "Good understanding of meiosis. Diagrams were clear." },
  { id: "sub-002", homeworkId: "hw-006", studentId: "stu-02", studentName: "Priya Sharma", studentRoll: "STU-1002", submissionDate: "2026-08-29", status: "GRADED", marksObtained: 24, remarks: "Excellent comparison chart. Minor labeling error on telophase." },
  { id: "sub-003", homeworkId: "hw-006", studentId: "stu-03", studentName: "Rohan Joshi", studentRoll: "STU-1003", submissionDate: "2026-08-30", status: "GRADED", marksObtained: 20, remarks: "Solid work. Needs more detail on significance of crossing over." },
  { id: "sub-004", homeworkId: "hw-006", studentId: "stu-04", studentName: "Diya Patel", studentRoll: "STU-1004", submissionDate: "2026-08-29", status: "GRADED", marksObtained: 25, remarks: "Outstanding! Perfect diagrams and thorough explanation." },
  { id: "sub-005", homeworkId: "hw-006", studentId: "stu-05", studentName: "Kabir Singh", studentRoll: "STU-1005", submissionDate: "2026-08-28", status: "GRADED", marksObtained: 18, remarks: "Late submission. Content was good but needs proofreading." },

  // Submissions for hw-010 (completed homework)
  { id: "sub-006", homeworkId: "hw-010", studentId: "stu-06", studentName: "Navya Agarwal", studentRoll: "STU-1006", submissionDate: "2026-08-28", status: "GRADED", marksObtained: 19, remarks: "Almost perfect. One error in systems of equations." },
  { id: "sub-007", homeworkId: "hw-010", studentId: "stu-07", studentName: "Ethan Patel", studentRoll: "STU-1007", submissionDate: "2026-08-29", status: "GRADED", marksObtained: 16, remarks: "Good effort. Slope calculations need review." },
  { id: "sub-008", homeworkId: "hw-010", studentId: "stu-08", studentName: "Zara Ahmed", studentRoll: "STU-1008", submissionDate: "2026-08-28", status: "GRADED", marksObtained: 20, remarks: "Perfect score! Clear, organized work." },

  // Partial submissions for active homework (hw-001)
  { id: "sub-009", homeworkId: "hw-001", studentId: "stu-01", studentName: "Aarav Mehta", studentRoll: "STU-1001", submissionDate: "2026-08-30", status: "SUBMITTED", remarks: "Submitted early. 18 of 20 problems completed." },
  { id: "sub-010", homeworkId: "hw-001", studentId: "stu-02", studentName: "Priya Sharma", studentRoll: "STU-1002", submissionDate: "2026-08-31", status: "SUBMITTED", remarks: "All problems completed." },
  { id: "sub-011", homeworkId: "hw-001", studentId: "stu-04", studentName: "Diya Patel", studentRoll: "STU-1004", submissionDate: "2026-08-30", status: "SUBMITTED", remarks: "Submitted with detailed solutions." },
];
