import { Announcement, Message, MessageThread, Notification, NotificationPreference } from "@/types";

export const initialAnnouncements: Announcement[] = [
  {
    id: "ann-001",
    title: "Annual Day Celebration 2026",
    content: "We are delighted to announce that the Annual Day Celebration will be held on September 15, 2026. All students, parents, and staff are invited to attend. The event will feature cultural performances, prize distribution, and the launch of the new STEM wing. Please confirm attendance by September 10.",
    summary: "Annual Day on Sep 15 with cultural performances and prize distribution.",
    author: "Principal Dr. Meera Kapoor",
    authorRole: "PRINCIPAL",
    branchId: "br-apex-01",
    branchName: "Apex Global Campus",
    priority: "HIGH",
    status: "PUBLISHED",
    target: "ALL",
    publishDate: "2026-08-25",
    expiryDate: "2026-09-16",
    viewCount: 342,
    createdAt: "2026-08-25T09:00:00Z",
    updatedAt: "2026-08-25T09:00:00Z",
  },
  {
    id: "ann-002",
    title: "Parent-Teacher Meeting — Mid-Term Results",
    content: "A Parent-Teacher Meeting is scheduled for September 8, 2026 to discuss mid-term examination results. Parents of Grade 9-12 students are requested to attend between 9:00 AM and 1:00 PM. Please bring your child's report card. Slots can be booked through the school app.",
    summary: "PTM on Sep 8 for mid-term results discussion (Grade 9-12).",
    author: "Vice Principal Mr. Arjun Desai",
    authorRole: "PRINCIPAL",
    branchId: "br-apex-01",
    branchName: "Apex Global Campus",
    priority: "HIGH",
    status: "PUBLISHED",
    target: "PARENTS",
    publishDate: "2026-08-28",
    expiryDate: "2026-09-09",
    viewCount: 189,
    createdAt: "2026-08-28T10:00:00Z",
    updatedAt: "2026-08-28T10:00:00Z",
  },
  {
    id: "ann-003",
    title: "Science Exhibition — Call for Projects",
    content: "The Science Department invites all students from Grade 6-12 to submit project proposals for the Inter-School Science Exhibition on October 20, 2026. Projects can be in categories: Physics, Chemistry, Biology, Computer Science, or Environmental Science. Last date for proposal submission: September 20.",
    summary: "Science Exhibition on Oct 20. Submit project proposals by Sep 20.",
    author: "Mrs. Sunita Rao",
    authorRole: "TEACHER",
    branchId: "br-apex-01",
    branchName: "Apex Global Campus",
    priority: "NORMAL",
    status: "PUBLISHED",
    target: "STUDENTS",
    publishDate: "2026-08-20",
    expiryDate: "2026-09-21",
    viewCount: 256,
    createdAt: "2026-08-20T11:00:00Z",
    updatedAt: "2026-08-20T11:00:00Z",
  },
  {
    id: "ann-004",
    title: "Transport Fee Revision — Effective October",
    content: "Please be informed that the transport fee for all routes will be revised effective October 1, 2026. The new fee structure will be shared with parents via email. Students currently using transport services must confirm continued usage by September 25.",
    summary: "Transport fee revision from Oct 1. Confirm usage by Sep 25.",
    author: "Accounts Department",
    authorRole: "ACCOUNTANT",
    branchId: "all",
    branchName: "All Campuses",
    priority: "NORMAL",
    status: "PUBLISHED",
    target: "PARENTS",
    publishDate: "2026-08-22",
    expiryDate: "2026-09-26",
    viewCount: 145,
    createdAt: "2026-08-22T09:00:00Z",
    updatedAt: "2026-08-22T09:00:00Z",
  },
  {
    id: "ann-005",
    title: "Teacher Training Workshop — AI in Education",
    content: "All faculty members are required to attend a mandatory workshop on 'Integrating AI Tools in Classroom Teaching' on September 5, 2026 from 2:00 PM to 5:00 PM in the Conference Hall. Attendance will be recorded. Please bring your laptop.",
    summary: "Mandatory AI in Education workshop for teachers on Sep 5.",
    author: "Principal Dr. Meera Kapoor",
    authorRole: "PRINCIPAL",
    branchId: "all",
    branchName: "All Campuses",
    priority: "URGENT",
    status: "PUBLISHED",
    target: "TEACHERS",
    publishDate: "2026-08-30",
    expiryDate: "2026-09-06",
    viewCount: 78,
    createdAt: "2026-08-30T08:00:00Z",
    updatedAt: "2026-08-30T08:00:00Z",
  },
  {
    id: "ann-006",
    title: "Holiday Notice — Ganesh Chaturthi",
    content: "The school will remain closed on September 6, 2026 on account of Ganesh Chaturthi. Regular classes will resume on September 8 (Monday). Wishing everyone a happy and safe festival.",
    summary: "School closed on Sep 6 for Ganesh Chaturthi. Classes resume Sep 8.",
    author: "Admin Office",
    authorRole: "STAFF",
    branchId: "all",
    branchName: "All Campuses",
    priority: "NORMAL",
    status: "PUBLISHED",
    target: "ALL",
    publishDate: "2026-09-01",
    expiryDate: "2026-09-07",
    viewCount: 412,
    createdAt: "2026-09-01T07:00:00Z",
    updatedAt: "2026-09-01T07:00:00Z",
  },
  {
    id: "ann-007",
    title: "Emergency Drill — Fire Safety",
    content: "A fire safety drill will be conducted on September 12, 2026 at 10:30 AM across all campuses. All students and staff must participate. Class teachers will guide students to assembly points. Please familiarize yourself with evacuation routes.",
    summary: "Fire safety drill on Sep 12 at 10:30 AM. All must participate.",
    author: "Safety Officer Mr. Ravi Shankar",
    authorRole: "STAFF",
    branchId: "all",
    branchName: "All Campuses",
    priority: "URGENT",
    status: "PUBLISHED",
    target: "ALL",
    publishDate: "2026-09-03",
    expiryDate: "2026-09-13",
    viewCount: 389,
    createdAt: "2026-09-03T09:00:00Z",
    updatedAt: "2026-09-03T09:00:00Z",
  },
  {
    id: "ann-008",
    title: "Library Book Return Reminder",
    content: "All students are reminded to return borrowed library books by September 5, 2026. Overdue books will incur a fine of ₹5 per day. New book orders for the semester have arrived and will be available from September 8.",
    summary: "Return library books by Sep 5. New books available from Sep 8.",
    author: "Librarian Ms. Pooja Mehta",
    authorRole: "STAFF",
    branchId: "br-apex-01",
    branchName: "Apex Global Campus",
    priority: "LOW",
    status: "PUBLISHED",
    target: "STUDENTS",
    publishDate: "2026-09-01",
    expiryDate: "2026-09-06",
    viewCount: 98,
    createdAt: "2026-09-01T10:00:00Z",
    updatedAt: "2026-09-01T10:00:00Z",
  },
];

export const initialMessages: Message[] = [
  {
    id: "msg-001",
    subject: "Query about Mathematics homework",
    body: "Dear Dr. Lin, my son Aarav is finding the quadratic equations chapter difficult. Could you please share some additional practice problems or recommend any online resources? Thank you.",
    senderId: "par-001",
    senderName: "Vikram Mehta (Parent of Aarav Mehta)",
    senderRole: "PARENT",
    recipientIds: ["tch-01"],
    recipientNames: ["Mrs. Sunita Rao"],
    recipientType: "INDIVIDUAL",
    channel: "IN_APP",
    channelStatus: "READ",
    branchId: "br-apex-01",
    branchName: "Apex Global Campus",
    isRead: true,
    isStarred: false,
    sentAt: "2026-08-28T14:30:00Z",
    readAt: "2026-08-28T16:45:00Z",
  },
  {
    id: "msg-002",
    subject: "RE: Query about Mathematics homework",
    body: "Dear Mr. Mehta, thank you for reaching out. I understand Aarav's concern. I've attached some supplementary worksheets and a link to Khan Academy's quadratic equations module. I'd also be happy to arrange a 15-minute extra class if needed. Let me know.",
    senderId: "tch-01",
    senderName: "Mrs. Sunita Rao",
    senderRole: "TEACHER",
    senderAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100",
    recipientIds: ["par-001"],
    recipientNames: ["Vikram Mehta"],
    recipientType: "INDIVIDUAL",
    channel: "IN_APP",
    channelStatus: "READ",
    branchId: "br-apex-01",
    branchName: "Apex Global Campus",
    isRead: true,
    isStarred: false,
    replyToId: "msg-001",
    threadId: "thr-001",
    sentAt: "2026-08-28T17:15:00Z",
    readAt: "2026-08-29T08:00:00Z",
  },
  {
    id: "msg-003",
    subject: "Bus route change request",
    body: "Hello Transport Team, we've recently shifted to Sunrise Apartments. Can Kavya be moved from Route B to Route A? Her stop would be Sunrise Apartments. Please let me know if any formal application is needed.",
    senderId: "par-002",
    senderName: "Sanjay Iyer (Parent of Kavya Iyer)",
    senderRole: "PARENT",
    recipientIds: ["tch-03"],
    recipientNames: ["Transport Department"],
    recipientType: "INDIVIDUAL",
    channel: "IN_APP",
    channelStatus: "DELIVERED",
    branchId: "br-apex-01",
    branchName: "Apex Global Campus",
    isRead: false,
    isStarred: true,
    sentAt: "2026-09-01T09:00:00Z",
  },
  {
    id: "msg-004",
    subject: "Staff meeting minutes — August",
    body: "Dear Faculty, please find attached the minutes from the August staff meeting. Key decisions: 1) New grading policy effective Oct 1, 2) Sports day on Nov 15, 3) Curriculum review committee formation. Please review and share feedback by Sep 5.",
    senderId: "tch-05",
    senderName: "Mrs. Kavitha Subramaniam (HOD English)",
    senderRole: "TEACHER",
    senderAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100",
    recipientIds: [],
    recipientNames: ["All Teachers"],
    recipientType: "ALL_TEACHERS",
    channel: "IN_APP",
    channelStatus: "SENT",
    branchId: "br-apex-01",
    branchName: "Apex Global Campus",
    isRead: false,
    isStarred: false,
    sentAt: "2026-09-02T10:00:00Z",
  },
  {
    id: "msg-005",
    subject: "Uniform policy reminder",
    body: "Dear Parents, this is a gentle reminder that starting September 1, all students must wear the complete school uniform including proper black shoes. Students not in proper uniform may be sent back. Exceptions will be made for medical reasons with a doctor's note.",
    senderId: "admin-001",
    senderName: "Admin Office",
    senderRole: "STAFF",
    recipientIds: [],
    recipientNames: ["All Parents"],
    recipientType: "ALL_PARENTS",
    channel: "WHATSAPP",
    channelStatus: "DELIVERED",
    branchId: "all",
    branchName: "All Campuses",
    isRead: false,
    isStarred: false,
    sentAt: "2026-08-30T08:00:00Z",
  },
  {
    id: "msg-006",
    subject: "Project submission extension",
    body: "Dear Students, due to the holiday on Sep 6, the deadline for the Science Exhibition project proposals has been extended to September 22, 2026. Please ensure your proposals include: title, hypothesis, methodology, expected outcomes, and materials needed. All the best!",
    senderId: "tch-02",
    senderName: "Mr. Rajesh Kulkarni",
    senderRole: "TEACHER",
    senderAvatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100",
    recipientIds: [],
    recipientNames: ["All Students"],
    recipientType: "ALL_STUDENTS",
    channel: "IN_APP",
    channelStatus: "SENT",
    branchId: "br-apex-01",
    branchName: "Apex Global Campus",
    isRead: true,
    isStarred: false,
    sentAt: "2026-09-01T11:30:00Z",
    readAt: "2026-09-01T14:00:00Z",
  },
];

export const initialMessageThreads: MessageThread[] = [
  {
    id: "thr-001",
    subject: "Query about Mathematics homework",
    participants: [
      { id: "par-001", name: "Vikram Mehta" },
      { id: "tch-01", name: "Mrs. Sunita Rao", avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100" },
    ],
    lastMessage: "Thank you so much, Dr. Lin! The worksheets are very helpful.",
    lastMessageAt: "2026-08-29T08:00:00Z",
    unreadCount: 0,
    branchId: "br-apex-01",
  },
  {
    id: "thr-002",
    subject: "Bus route change request",
    participants: [
      { id: "par-002", name: "Sanjay Iyer" },
    ],
    lastMessage: "Hello Transport Team, we've recently shifted to Sunrise Apartments...",
    lastMessageAt: "2026-09-01T09:00:00Z",
    unreadCount: 1,
    branchId: "br-apex-01",
  },
];

export const initialNotifications: Notification[] = [
  { id: "noti-001", title: "New Announcement", message: "Annual Day Celebration 2026 has been announced for September 15.", category: "EVENT", priority: "HIGH", isRead: false, isArchived: false, userId: "all", branchId: "br-apex-01", branchName: "Apex Global Campus", actionUrl: "/announcements", actionLabel: "View Announcement", icon: "Megaphone", channels: ["IN_APP"], deliveredChannels: ["IN_APP"], createdAt: "2026-08-25T09:05:00Z" },
  { id: "noti-002", title: "Homework Graded", message: "Mrs. Sunita Rao has graded your Mathematics homework. Marks: 45/50", category: "ACADEMIC", priority: "NORMAL", isRead: true, isArchived: false, userId: "stu-01", branchId: "br-apex-01", branchName: "Apex Global Campus", actionUrl: "/homework", actionLabel: "View Homework", icon: "BookOpen", channels: ["IN_APP"], deliveredChannels: ["IN_APP"], createdAt: "2026-08-26T14:00:00Z", readAt: "2026-08-26T15:30:00Z" },
  { id: "noti-003", title: "Fee Reminder", message: "Your outstanding fee balance is ₹6,000. Due date: September 10, 2026.", category: "FINANCE", priority: "HIGH", isRead: false, isArchived: false, userId: "par-001", branchId: "br-apex-01", branchName: "Apex Global Campus", actionUrl: "/fees", actionLabel: "Pay Now", icon: "CreditCard", channels: ["IN_APP", "SMS", "EMAIL"], deliveredChannels: ["IN_APP", "SMS"], createdAt: "2026-08-28T08:00:00Z" },
  { id: "noti-004", title: "Exam Schedule Published", message: "Mid-Term Examination schedule for Grade 12 has been published.", category: "ACADEMIC", priority: "NORMAL", isRead: false, isArchived: false, userId: "all", branchId: "br-apex-01", branchName: "Apex Global Campus", actionUrl: "/exams", actionLabel: "View Schedule", icon: "FileSpreadsheet", channels: ["IN_APP"], deliveredChannels: ["IN_APP"], createdAt: "2026-08-20T10:00:00Z" },
  { id: "noti-005", title: "Bus Delay Alert", message: "Route A - North District bus is running 10 minutes late due to traffic.", category: "TRANSPORT", priority: "URGENT", isRead: true, isArchived: false, userId: "all", branchId: "br-apex-01", branchName: "Apex Global Campus", icon: "Bus", channels: ["IN_APP", "SMS", "WHATSAPP"], deliveredChannels: ["IN_APP", "SMS", "WHATSAPP"], createdAt: "2026-09-01T07:15:00Z", readAt: "2026-09-01T07:20:00Z" },
  { id: "noti-006", title: "New Message", message: "Mrs. Sunita Rao replied to your query about Mathematics homework.", category: "MESSAGE", priority: "NORMAL", isRead: true, isArchived: false, userId: "par-001", branchId: "br-apex-01", branchName: "Apex Global Campus", actionUrl: "/messages", actionLabel: "View Message", icon: "MessageSquare", channels: ["IN_APP"], deliveredChannels: ["IN_APP"], createdAt: "2026-08-28T17:15:00Z", readAt: "2026-08-29T08:00:00Z" },
  { id: "noti-007", title: "Attendance Alert", message: "Your child Aarav Mehta was absent on August 29, 2026.", category: "ATTENDANCE", priority: "HIGH", isRead: false, isArchived: false, userId: "par-001", branchId: "br-apex-01", branchName: "Apex Global Campus", icon: "UserX", channels: ["IN_APP", "SMS"], deliveredChannels: ["IN_APP", "SMS"], createdAt: "2026-08-29T09:00:00Z" },
  { id: "noti-008", title: "System Maintenance", message: "The school portal will undergo maintenance on September 3 from 11 PM to 2 AM IST.", category: "SYSTEM", priority: "LOW", isRead: true, isArchived: false, userId: "all", branchId: "all", branchName: "All Campuses", icon: "Settings", channels: ["IN_APP"], deliveredChannels: ["IN_APP"], createdAt: "2026-09-01T10:00:00Z", readAt: "2026-09-01T10:05:00Z" },
  { id: "noti-009", title: "PTM Reminder", message: "Parent-Teacher Meeting is scheduled for September 8. Book your slot now.", category: "EVENT", priority: "HIGH", isRead: false, isArchived: false, userId: "all", branchId: "br-apex-01", branchName: "Apex Global Campus", actionUrl: "/events", actionLabel: "Book Slot", icon: "Calendar", channels: ["IN_APP", "EMAIL"], deliveredChannels: ["IN_APP", "EMAIL"], createdAt: "2026-09-02T08:00:00Z" },
  { id: "noti-010", title: "New Event Created", message: "Science Exhibition — Call for Projects has been scheduled for October 20.", category: "EVENT", priority: "NORMAL", isRead: false, isArchived: false, userId: "all", branchId: "br-apex-01", branchName: "Apex Global Campus", actionUrl: "/events", actionLabel: "View Event", icon: "Beaker", channels: ["IN_APP"], deliveredChannels: ["IN_APP"], createdAt: "2026-08-20T11:05:00Z" },
];

export const initialNotificationPreferences: NotificationPreference[] = [
  { id: "np-001", userId: "current", category: "ACADEMIC", inApp: true, email: true, sms: false, whatsapp: false },
  { id: "np-002", userId: "current", category: "FINANCE", inApp: true, email: true, sms: true, whatsapp: false },
  { id: "np-003", userId: "current", category: "TRANSPORT", inApp: true, email: false, sms: true, whatsapp: true },
  { id: "np-004", userId: "current", category: "EVENT", inApp: true, email: true, sms: false, whatsapp: false },
  { id: "np-005", userId: "current", category: "ATTENDANCE", inApp: true, email: true, sms: true, whatsapp: false },
  { id: "np-006", userId: "current", category: "SYSTEM", inApp: true, email: false, sms: false, whatsapp: false },
  { id: "np-007", userId: "current", category: "MESSAGE", inApp: true, email: true, sms: false, whatsapp: false },
];
