import { Teacher } from "@/types";

export const initialTeachers: Teacher[] = [
  {
    id: "tch-01",
    employeeId: "TCH-0101",
    firstName: "Sarah",
    lastName: "Lin",
    fullName: "Dr. Sarah Lin",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    email: "s.lin@apex.edu",
    phone: "+1 (555) 234-5101",
    gender: "Female",
    dateOfBirth: "1984-06-14",
    qualification: "Ph.D. in Pure Mathematics, M.Ed. Stanford",
    joiningDate: "2018-08-01",
    branchId: "br-apex-01",
    branchName: "Apex Global Campus",
    department: "Mathematics & Computing",
    designation: "Head of Department & AP Calculus Lead",
    status: "ACTIVE",
    subjectsTaught: ["AP Calculus BC", "Linear Algebra", "Grade 10 Honors Math"],
    assignedClasses: [
      { classId: "cls-g10", className: "Grade 10", sectionId: "sec-g10-a", sectionName: "Section A", subjectName: "Honors Mathematics", weeklyPeriods: 6 },
      { classId: "cls-g12", className: "Grade 12", sectionId: "sec-g12-a", sectionName: "Section A", subjectName: "AP Calculus BC", weeklyPeriods: 6 },
    ],
    attendanceRate: 98.5,
    leaveSummary: { totalAllowed: 24, used: 3, balance: 21, casualLeaves: 2, medicalLeaves: 1 },
    salarySummary: { baseSalary: 6800, allowances: 1200, grossSalary: 8000, paymentStatus: "PAID", lastDisbursedDate: "2026-08-31" },
    bio: "Passionate mathematics educator with 14+ years coaching international Olympiad teams.",
    experienceYears: 14,
    createdAt: "2020-01-15T00:00:00.000Z",
    updatedAt: "2026-08-30T00:00:00.000Z",
  },
  {
    id: "tch-02",
    employeeId: "TCH-0102",
    firstName: "Marcus",
    lastName: "Brody",
    fullName: "Prof. Marcus Brody",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80",
    email: "m.brody@apex.edu",
    phone: "+1 (555) 234-5102",
    gender: "Male",
    dateOfBirth: "1979-11-20",
    qualification: "M.Sc. Physics (MIT), B.Ed.",
    joiningDate: "2016-07-15",
    branchId: "br-apex-01",
    branchName: "Apex Global Campus",
    department: "Science & Technology",
    designation: "Senior Physics Faculty & STEM Mentor",
    status: "ACTIVE",
    subjectsTaught: ["AP Physics C", "Quantum Mechanics Intro", "General Physics"],
    assignedClasses: [
      { classId: "cls-g11", className: "Grade 11", sectionId: "sec-g11-a", sectionName: "Section A", subjectName: "AP Physics 1", weeklyPeriods: 5 },
      { classId: "cls-g12", className: "Grade 12", sectionId: "sec-g12-a", sectionName: "Section A", subjectName: "AP Physics C", weeklyPeriods: 6 },
    ],
    attendanceRate: 99.1,
    leaveSummary: { totalAllowed: 24, used: 2, balance: 22, casualLeaves: 1, medicalLeaves: 1 },
    salarySummary: { baseSalary: 7200, allowances: 1400, grossSalary: 8600, paymentStatus: "PAID", lastDisbursedDate: "2026-08-31" },
    bio: "Former researcher at Lawrence Berkeley National Lab; teaches conceptual and mathematical physics.",
    experienceYears: 18,
    createdAt: "2020-01-15T00:00:00.000Z",
    updatedAt: "2026-08-30T00:00:00.000Z",
  },
  {
    id: "tch-03",
    employeeId: "TCH-0201",
    firstName: "Elena",
    lastName: "Rostova",
    fullName: "Elena Rostova, M.S.",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    email: "e.rostova@westside.edu",
    phone: "+1 (555) 345-6101",
    gender: "Female",
    dateOfBirth: "1989-03-08",
    qualification: "M.S. Computer Science (Carnegie Mellon)",
    joiningDate: "2019-09-01",
    branchId: "br-west-02",
    branchName: "Westside STEM & Innovation Academy",
    department: "Computer Science & AI",
    designation: "Lead Robotics & AI Instructor",
    status: "ACTIVE",
    subjectsTaught: ["AP Computer Science A", "Robotics & Microcontrollers", "Data Structures"],
    assignedClasses: [
      { classId: "cls-g9", className: "Grade 9", sectionId: "sec-g9-a", sectionName: "Section A", subjectName: "Python & Algorithmic Thinking", weeklyPeriods: 5 },
      { classId: "cls-g11", className: "Grade 11", sectionId: "sec-g11-b", sectionName: "Section B", subjectName: "AP Computer Science A", weeklyPeriods: 6 },
    ],
    attendanceRate: 97.4,
    leaveSummary: { totalAllowed: 24, used: 4, balance: 20, casualLeaves: 3, medicalLeaves: 1 },
    salarySummary: { baseSalary: 6600, allowances: 1100, grossSalary: 7700, paymentStatus: "PAID", lastDisbursedDate: "2026-08-31" },
    bio: "FIRST Robotics coach and competitive programming mentor.",
    experienceYears: 9,
    createdAt: "2021-04-10T00:00:00.000Z",
    updatedAt: "2026-08-30T00:00:00.000Z",
  },
  {
    id: "tch-04",
    employeeId: "TCH-0301",
    firstName: "Annette",
    lastName: "Dupont",
    fullName: "Annette Dupont, M.Ed.",
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
    email: "a.dupont@northpoint.edu",
    phone: "+1 (555) 456-7101",
    gender: "Female",
    dateOfBirth: "1986-09-12",
    qualification: "AMI International Montessori Diploma, M.Ed. Early Childhood",
    joiningDate: "2018-09-01",
    branchId: "br-north-03",
    branchName: "Northpoint Montessori & Prep",
    department: "Early Childhood (Toddler & Primary)",
    designation: "Montessori Lead Educator",
    status: "ACTIVE",
    subjectsTaught: ["Sensorial Explorations", "Early Literacy", "Practical Life"],
    assignedClasses: [
      { classId: "cls-mont", className: "Montessori Primary", sectionId: "sec-mont-a", sectionName: "Sunflowers Studio", subjectName: "Montessori Integrated Curriculum", weeklyPeriods: 15 },
    ],
    attendanceRate: 96.8,
    leaveSummary: { totalAllowed: 24, used: 5, balance: 19, casualLeaves: 3, medicalLeaves: 2 },
    salarySummary: { baseSalary: 5500, allowances: 900, grossSalary: 6400, paymentStatus: "PAID", lastDisbursedDate: "2026-08-31" },
    bio: "Specialist in child-directed sensory learning and bilingual early immersion.",
    experienceYears: 12,
    createdAt: "2021-09-01T00:00:00.000Z",
    updatedAt: "2026-08-30T00:00:00.000Z",
  },
  {
    id: "tch-05",
    employeeId: "TCH-0401",
    firstName: "Nigel",
    lastName: "Ross",
    fullName: "Dr. Nigel Ross",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    email: "n.ross@greenvalley.org",
    phone: "+1 (555) 567-8101",
    gender: "Male",
    dateOfBirth: "1980-04-22",
    qualification: "Ph.D. in Comparative Literature (Oxford)",
    joiningDate: "2017-08-15",
    branchId: "br-green-04",
    branchName: "Green Valley International School",
    department: "International Baccalaureate (IB)",
    designation: "IB Diploma Coordinator & Literature Chair",
    status: "ACTIVE",
    subjectsTaught: ["IB English Literature HL", "Theory of Knowledge (TOK)"],
    assignedClasses: [
      { classId: "cls-g11", className: "Grade 11", sectionId: "sec-g11-ib", sectionName: "IB Diploma Year 1", subjectName: "IB Literature HL", weeklyPeriods: 6 },
      { classId: "cls-g12", className: "Grade 12", sectionId: "sec-g12-ib", sectionName: "IB Diploma Year 2", subjectName: "Theory of Knowledge", weeklyPeriods: 4 },
    ],
    attendanceRate: 98.0,
    leaveSummary: { totalAllowed: 24, used: 2, balance: 22, casualLeaves: 2, medicalLeaves: 0 },
    salarySummary: { baseSalary: 7100, allowances: 1300, grossSalary: 8400, paymentStatus: "PAID", lastDisbursedDate: "2026-08-31" },
    bio: "IB examiner with 16 years teaching across UK, Switzerland and USA schools.",
    experienceYears: 16,
    createdAt: "2020-05-18T00:00:00.000Z",
    updatedAt: "2026-08-30T00:00:00.000Z",
  },
  {
    id: "tch-06",
    employeeId: "TCH-0601",
    firstName: "Camilla",
    lastName: "Rossi",
    fullName: "Camilla Rossi, M.F.A.",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    email: "c.rossi@riverdale-arts.edu",
    phone: "+1 (555) 789-0101",
    gender: "Female",
    dateOfBirth: "1988-10-05",
    qualification: "M.F.A. Fine Arts & Digital Media (RISD)",
    joiningDate: "2020-01-10",
    branchId: "br-river-06",
    branchName: "Riverdale Arts & Sports Academy",
    department: "Visual Arts & Digital Design",
    designation: "Visual Arts Department Head",
    status: "ACTIVE",
    subjectsTaught: ["Studio Art", "Digital Illustration & UI Design", "Sculpture"],
    assignedClasses: [
      { classId: "cls-g10", className: "Grade 10", sectionId: "sec-g10-arts", sectionName: "Section Creative", subjectName: "Studio Art Portfolio", weeklyPeriods: 6 },
    ],
    attendanceRate: 97.9,
    leaveSummary: { totalAllowed: 24, used: 3, balance: 21, casualLeaves: 2, medicalLeaves: 1 },
    salarySummary: { baseSalary: 6200, allowances: 1000, grossSalary: 7200, paymentStatus: "PAID", lastDisbursedDate: "2026-08-31" },
    bio: "Practicing digital artist and gallery curator guiding students to Rhode Island and Pratt art portfolios.",
    experienceYears: 10,
    createdAt: "2022-02-14T00:00:00.000Z",
    updatedAt: "2026-08-30T00:00:00.000Z",
  },
];
