import type { TestCase, TestSuite, TestPlan, TestRun } from "@/types";

export const initialTestSuites: TestSuite[] = [
  { id: "ts-001", name: "Student Management", description: "Test cases for student CRUD, enrollment, and profile management", module: "Students", testCaseCount: 18, passedCount: 14, failedCount: 2, blockedCount: 1, passRate: 77.8, status: "ACTIVE", createdBy: "Priya Kapoor", createdAt: "2026-06-01T10:00:00Z", updatedAt: "2026-08-20T14:00:00Z" },
  { id: "ts-002", name: "Attendance Module", description: "Attendance marking, biometric integration, reports", module: "Attendance", testCaseCount: 15, passedCount: 13, failedCount: 1, blockedCount: 0, passRate: 86.7, status: "ACTIVE", createdBy: "Priya Kapoor", createdAt: "2026-06-05T10:00:00Z", updatedAt: "2026-08-18T11:00:00Z" },
  { id: "ts-003", name: "Fee Management", description: "Fee collection, invoices, receipts, late fees", module: "Fees", testCaseCount: 22, passedCount: 18, failedCount: 3, blockedCount: 0, passRate: 81.8, status: "ACTIVE", createdBy: "Rahul Mehra", createdAt: "2026-06-10T10:00:00Z", updatedAt: "2026-08-22T16:00:00Z" },
  { id: "ts-004", name: "Transport & Fleet", description: "Bus tracking, routes, driver assignments", module: "Transport", testCaseCount: 12, passedCount: 10, failedCount: 1, blockedCount: 1, passRate: 83.3, status: "ACTIVE", createdBy: "Anjali Sharma", createdAt: "2026-06-15T10:00:00Z", updatedAt: "2026-08-19T09:00:00Z" },
  { id: "ts-005", name: "Examination Module", description: "Exam scheduling, marks entry, report cards, rankings", module: "Exams", testCaseCount: 20, passedCount: 17, failedCount: 2, blockedCount: 0, passRate: 85.0, status: "ACTIVE", createdBy: "Vikram Singh", createdAt: "2026-07-01T10:00:00Z", updatedAt: "2026-08-25T12:00:00Z" },
  { id: "ts-006", name: "Payroll & Salary", description: "Salary structures, payslip generation, deductions", module: "Payroll", testCaseCount: 16, passedCount: 14, failedCount: 1, blockedCount: 0, passRate: 87.5, status: "ACTIVE", createdBy: "Sunita Reddy", createdAt: "2026-07-10T10:00:00Z", updatedAt: "2026-08-23T15:00:00Z" },
  { id: "ts-007", name: "Authentication & Roles", description: "Login, logout, role-based access, permissions", module: "Auth", testCaseCount: 10, passedCount: 10, failedCount: 0, blockedCount: 0, passRate: 100.0, status: "ACTIVE", createdBy: "Rajiv Kumar", createdAt: "2026-05-15T10:00:00Z", updatedAt: "2026-08-10T08:00:00Z" },
  { id: "ts-008", name: "Notification System", description: "Push notifications, SMS, email alerts, announcements", module: "Communication", testCaseCount: 14, passedCount: 11, failedCount: 2, blockedCount: 1, passRate: 78.6, status: "ACTIVE", createdBy: "Priya Kapoor", createdAt: "2026-07-20T10:00:00Z", updatedAt: "2026-08-26T10:00:00Z" },
];

export const initialTestPlans: TestPlan[] = [
  { id: "tp-001", name: "v2.5 Regression Suite", description: "Full regression testing for v2.5 release", modules: ["Students", "Attendance", "Fees", "Transport", "Exams", "Payroll"], totalCases: 65, executedCases: 58, passedCases: 48, failedCases: 6, blockedCases: 2, passRate: 73.8, status: "IN_PROGRESS", environment: "Staging", startDate: "2026-08-10", endDate: "2026-08-30", createdBy: "Priya Kapoor", createdAt: "2026-08-08T10:00:00Z", updatedAt: "2026-08-28T14:00:00Z" },
  { id: "tp-002", name: "Auth & Security Audit", description: "Security-focused testing for authentication module", modules: ["Auth"], totalCases: 10, executedCases: 10, passedCases: 10, failedCases: 0, blockedCases: 0, passRate: 100.0, status: "COMPLETED", environment: "Staging", startDate: "2026-08-01", endDate: "2026-08-05", createdBy: "Rajiv Kumar", createdAt: "2026-07-28T10:00:00Z", updatedAt: "2026-08-05T10:00:00Z" },
  { id: "tp-003", name: "Communication Module Testing", description: "Testing notifications, messages, announcements", modules: ["Communication"], totalCases: 14, executedCases: 12, passedCases: 9, failedCases: 2, blockedCases: 1, passRate: 75.0, status: "IN_PROGRESS", environment: "Staging", startDate: "2026-08-20", endDate: "2026-09-05", createdBy: "Priya Kapoor", createdAt: "2026-08-18T10:00:00Z", updatedAt: "2026-08-26T10:00:00Z" },
  { id: "tp-004", name: "v2.5 Pre-Release Smoke Test", description: "Quick smoke test before production release", modules: ["Students", "Fees", "Attendance"], totalCases: 30, executedCases: 0, passedCases: 0, failedCases: 0, blockedCases: 0, passRate: 0, status: "DRAFT", environment: "Production", startDate: "2026-09-01", createdBy: "Rahul Mehra", createdAt: "2026-08-25T10:00:00Z", updatedAt: "2026-08-25T10:00:00Z" },
];

export const initialTestRuns: TestRun[] = [
  { id: "tr-001", planId: "tp-001", planName: "v2.5 Regression Suite", runNumber: 1, environment: "Staging", status: "COMPLETED", totalCases: 65, passed: 48, failed: 6, blocked: 2, skipped: 9, executedBy: "Priya Kapoor", startedAt: "2026-08-12T09:00:00Z", completedAt: "2026-08-18T17:00:00Z", notes: "First pass of regression suite" },
  { id: "tr-002", planId: "tp-001", planName: "v2.5 Regression Suite", runNumber: 2, environment: "Staging", status: "IN_PROGRESS", totalCases: 65, passed: 22, failed: 1, blocked: 0, skipped: 42, executedBy: "Rahul Mehra", startedAt: "2026-08-25T10:00:00Z", notes: "Retest after bug fixes" },
  { id: "tr-003", planId: "tp-002", planName: "Auth & Security Audit", runNumber: 1, environment: "Staging", status: "COMPLETED", totalCases: 10, passed: 10, failed: 0, blocked: 0, skipped: 0, executedBy: "Rajiv Kumar", startedAt: "2026-08-01T09:00:00Z", completedAt: "2026-08-04T16:00:00Z", notes: "All auth tests passed" },
  { id: "tr-004", planId: "tp-003", planName: "Communication Module Testing", runNumber: 1, environment: "Staging", status: "IN_PROGRESS", totalCases: 14, passed: 9, failed: 2, blocked: 1, skipped: 2, executedBy: "Anjali Sharma", startedAt: "2026-08-21T09:00:00Z", notes: "SMS delivery issues found" },
];

export const initialTestCases: TestCase[] = [
  // Student Management
  { id: "tc-001", title: "Create new student profile", module: "Students", description: "Verify that a new student can be created with all required fields", preconditions: "User must be logged in as admin or admission officer", steps: ["Navigate to Students page", "Click 'Add Student'", "Fill in name, class, parent details", "Click 'Save'"], expectedResult: "Student profile is created and appears in the list", status: "PASSED", priority: "CRITICAL", severity: "BLOCKER", assignee: "Rahul Mehra", assigneeRole: "QA Engineer", environment: "Staging", suiteId: "ts-001", suiteName: "Student Management", lastRunDate: "2026-08-20", lastRunBy: "Rahul Mehra", tags: ["smoke", "regression"], createdAt: "2026-06-02T10:00:00Z", updatedAt: "2026-08-20T10:00:00Z" },
  { id: "tc-002", title: "Edit student profile", module: "Students", description: "Verify that student details can be updated", preconditions: "Student must exist in the system", steps: ["Navigate to student detail page", "Click 'Edit'", "Update phone number", "Click 'Save'"], expectedResult: "Student details are updated", status: "PASSED", priority: "HIGH", severity: "MAJOR", assignee: "Rahul Mehra", assigneeRole: "QA Engineer", environment: "Staging", suiteId: "ts-001", suiteName: "Student Management", lastRunDate: "2026-08-20", lastRunBy: "Rahul Mehra", tags: ["regression"], createdAt: "2026-06-02T10:00:00Z", updatedAt: "2026-08-20T10:00:00Z" },
  { id: "tc-003", title: "Filter students by class", module: "Students", description: "Verify filtering works correctly", preconditions: "Multiple students exist in different classes", steps: ["Navigate to Students page", "Select a class from filter", "Verify filtered results"], expectedResult: "Only students from selected class are displayed", status: "PASSED", priority: "MEDIUM", severity: "MINOR", assignee: "Anjali Sharma", assigneeRole: "QA Tester", environment: "Staging", suiteId: "ts-001", suiteName: "Student Management", lastRunDate: "2026-08-19", lastRunBy: "Anjali Sharma", tags: ["regression"], createdAt: "2026-06-02T10:00:00Z", updatedAt: "2026-08-19T10:00:00Z" },
  { id: "tc-004", title: "Search student by name or ID", module: "Students", description: "Verify search functionality returns correct results", preconditions: "Students exist in the system", steps: ["Navigate to Students page", "Type partial name in search box", "Verify results match search query"], expectedResult: "Matching students are displayed", status: "PASSED", priority: "MEDIUM", severity: "MINOR", assignee: "Rahul Mehra", assigneeRole: "QA Engineer", environment: "Staging", suiteId: "ts-001", suiteName: "Student Management", lastRunDate: "2026-08-20", lastRunBy: "Rahul Mehra", tags: ["regression"], createdAt: "2026-06-05T10:00:00Z", updatedAt: "2026-08-20T10:00:00Z" },
  { id: "tc-005", title: "Delete student with no fee dues", module: "Students", description: "Verify student without outstanding fees can be deleted", preconditions: "Student exists with no pending fees", steps: ["Navigate to student detail", "Click 'Delete'", "Confirm deletion"], expectedResult: "Student is removed from the list", status: "FAILED", priority: "HIGH", severity: "MAJOR", assignee: "Rahul Mehra", assigneeRole: "QA Engineer", environment: "Staging", suiteId: "ts-001", suiteName: "Student Management", lastRunDate: "2026-08-20", lastRunBy: "Rahul Mehra", tags: ["regression"], createdAt: "2026-06-05T10:00:00Z", updatedAt: "2026-08-20T10:00:00Z" },
  { id: "tc-006", title: "Delete student with fee dues", module: "Students", description: "Verify student with pending fees cannot be deleted", preconditions: "Student exists with pending fees", steps: ["Navigate to student detail", "Click 'Delete'"], expectedResult: "Error message shown, student not deleted", status: "PASSED", priority: "HIGH", severity: "MAJOR", assignee: "Rahul Mehra", assigneeRole: "QA Engineer", environment: "Staging", suiteId: "ts-001", suiteName: "Student Management", lastRunDate: "2026-08-20", lastRunBy: "Rahul Mehra", tags: ["regression", "validation"], createdAt: "2026-06-05T10:00:00Z", updatedAt: "2026-08-20T10:00:00Z" },
  { id: "tc-007", title: "Guardian access restricted to own child", module: "Students", description: "Verify guardians can only view their own children's data", preconditions: "Guardian account exists with linked children", steps: ["Login as guardian", "Navigate to student profiles", "Verify only linked children are visible"], expectedResult: "Only linked student profiles are accessible", status: "PASSED", priority: "CRITICAL", severity: "BLOCKER", assignee: "Rajiv Kumar", assigneeRole: "QA Lead", environment: "Staging", suiteId: "ts-001", suiteName: "Student Management", lastRunDate: "2026-08-10", lastRunBy: "Rajiv Kumar", tags: ["security", "access-control"], createdAt: "2026-06-10T10:00:00Z", updatedAt: "2026-08-10T10:00:00Z" },
  // Attendance
  { id: "tc-008", title: "Mark daily attendance for a section", module: "Attendance", description: "Verify attendance can be marked for a class section", preconditions: "Class section exists with enrolled students", steps: ["Navigate to Attendance page", "Select date and section", "Mark students as Present/Absent/Late", "Save attendance"], expectedResult: "Attendance is recorded and saved", status: "PASSED", priority: "CRITICAL", severity: "BLOCKER", assignee: "Anjali Sharma", assigneeRole: "QA Tester", environment: "Staging", suiteId: "ts-002", suiteName: "Attendance Module", lastRunDate: "2026-08-18", lastRunBy: "Anjali Sharma", tags: ["smoke"], createdAt: "2026-06-06T10:00:00Z", updatedAt: "2026-08-18T10:00:00Z" },
  { id: "tc-009", title: "View attendance report", module: "Attendance", description: "Verify attendance summary is accurate", preconditions: "Attendance has been marked for multiple days", steps: ["Navigate to Attendance Report", "Select date range and class", "Verify percentages"], expectedResult: "Report shows correct attendance percentages", status: "PASSED", priority: "HIGH", severity: "MAJOR", assignee: "Anjali Sharma", assigneeRole: "QA Tester", environment: "Staging", suiteId: "ts-002", suiteName: "Attendance Module", lastRunDate: "2026-08-18", lastRunBy: "Anjali Sharma", tags: ["regression"], createdAt: "2026-06-06T10:00:00Z", updatedAt: "2026-08-18T10:00:00Z" },
  { id: "tc-010", title: "Guardian cannot mark attendance", module: "Attendance", description: "Verify role-based access for attendance marking", preconditions: "Guardian account is active", steps: ["Login as guardian", "Navigate to attendance page", "Attempt to mark attendance"], expectedResult: "Marking controls are disabled or hidden", status: "PASSED", priority: "HIGH", severity: "MAJOR", assignee: "Rajiv Kumar", assigneeRole: "QA Lead", environment: "Staging", suiteId: "ts-002", suiteName: "Attendance Module", lastRunDate: "2026-08-10", lastRunBy: "Rajiv Kumar", tags: ["security", "access-control"], createdAt: "2026-06-10T10:00:00Z", updatedAt: "2026-08-10T10:00:00Z" },
  // Fees
  { id: "tc-011", title: "Collect fee payment", module: "Fees", description: "Verify fee can be collected and receipt generated", preconditions: "Student has pending fee invoice", steps: ["Navigate to Fees page", "Select student", "Choose invoice", "Enter payment amount and method", "Submit"], expectedResult: "Payment recorded, receipt generated, status updated", status: "PASSED", priority: "CRITICAL", severity: "BLOCKER", assignee: "Rahul Mehra", assigneeRole: "QA Engineer", environment: "Staging", suiteId: "ts-003", suiteName: "Fee Management", lastRunDate: "2026-08-22", lastRunBy: "Rahul Mehra", tags: ["smoke", "critical-path"], createdAt: "2026-06-11T10:00:00Z", updatedAt: "2026-08-22T10:00:00Z" },
  { id: "tc-012", title: "Calculate late fees", module: "Fees", description: "Verify late fees are auto-calculated for overdue payments", preconditions: "Invoice has a due date in the past", steps: ["View overdue invoice", "Check late fee amount"], expectedResult: "Late fee is correctly calculated based on days overdue", status: "FAILED", priority: "HIGH", severity: "MAJOR", assignee: "Rahul Mehra", assigneeRole: "QA Engineer", environment: "Staging", suiteId: "ts-003", suiteName: "Fee Management", lastRunDate: "2026-08-22", lastRunBy: "Rahul Mehra", tags: ["regression", "validation"], createdAt: "2026-06-11T10:00:00Z", updatedAt: "2026-08-22T10:00:00Z" },
  { id: "tc-013", title: "Generate fee receipt PDF", module: "Fees", description: "Verify receipt can be downloaded as PDF", preconditions: "Payment has been made", steps: ["Navigate to receipt", "Click 'Download PDF'"], expectedResult: "PDF downloads with correct details", status: "BLOCKED", priority: "MEDIUM", severity: "MINOR", assignee: "Anjali Sharma", assigneeRole: "QA Tester", environment: "Staging", suiteId: "ts-003", suiteName: "Fee Management", lastRunDate: "2026-08-20", lastRunBy: "Anjali Sharma", tags: ["regression"], createdAt: "2026-06-15T10:00:00Z", updatedAt: "2026-08-20T10:00:00Z" },
  // Transport
  { id: "tc-014", title: "Assign student to bus route", module: "Transport", description: "Verify student can be assigned to a transport route", preconditions: "Bus route exists with available seats", steps: ["Navigate to Transport", "Select route", "Assign student", "Save"], expectedResult: "Student is assigned and seat count updated", status: "PASSED", priority: "HIGH", severity: "MAJOR", assignee: "Vikram Singh", assigneeRole: "QA Engineer", environment: "Staging", suiteId: "ts-004", suiteName: "Transport & Fleet", lastRunDate: "2026-08-19", lastRunBy: "Vikram Singh", tags: ["regression"], createdAt: "2026-06-16T10:00:00Z", updatedAt: "2026-08-19T10:00:00Z" },
  { id: "tc-015", title: "Prevent overfilling bus capacity", module: "Transport", description: "Verify bus cannot exceed its seat capacity", preconditions: "Bus is at full capacity", steps: ["Navigate to route with full bus", "Attempt to assign another student"], expectedResult: "Error shown, assignment blocked", status: "PASSED", priority: "HIGH", severity: "MAJOR", assignee: "Vikram Singh", assigneeRole: "QA Engineer", environment: "Staging", suiteId: "ts-004", suiteName: "Transport & Fleet", lastRunDate: "2026-08-19", lastRunBy: "Vikram Singh", tags: ["validation"], createdAt: "2026-06-16T10:00:00Z", updatedAt: "2026-08-19T10:00:00Z" },
  // Exams
  { id: "tc-016", title: "Enter exam marks", module: "Exams", description: "Verify marks can be entered for exam subjects", preconditions: "Exam is scheduled and students enrolled", steps: ["Navigate to Exams", "Select exam", "Enter marks for each student", "Save"], expectedResult: "Marks saved, totals calculated", status: "PASSED", priority: "CRITICAL", severity: "BLOCKER", assignee: "Vikram Singh", assigneeRole: "QA Engineer", environment: "Staging", suiteId: "ts-005", suiteName: "Examination Module", lastRunDate: "2026-08-25", lastRunBy: "Vikram Singh", tags: ["smoke"], createdAt: "2026-07-02T10:00:00Z", updatedAt: "2026-08-25T10:00:00Z" },
  { id: "tc-017", title: "Generate report card", module: "Exams", description: "Verify report card is generated with correct data", preconditions: "Marks have been entered for all subjects", steps: ["Navigate to student profile", "Click 'Generate Report Card'"], expectedResult: "Report card shows correct grades, rank, and remarks", status: "FAILED", priority: "HIGH", severity: "MAJOR", assignee: "Vikram Singh", assigneeRole: "QA Engineer", environment: "Staging", suiteId: "ts-005", suiteName: "Examination Module", lastRunDate: "2026-08-25", lastRunBy: "Vikram Singh", tags: ["regression"], createdAt: "2026-07-02T10:00:00Z", updatedAt: "2026-08-25T10:00:00Z" },
  // Payroll
  { id: "tc-018", title: "Generate monthly payslip", module: "Payroll", description: "Verify payslip is generated with correct calculations", preconditions: "Salary structure is defined for employee", steps: ["Navigate to Payroll", "Select month", "Run payroll generation", "Review payslip"], expectedResult: "Payslip shows correct gross, deductions, net", status: "PASSED", priority: "CRITICAL", severity: "BLOCKER", assignee: "Sunita Reddy", assigneeRole: "QA Engineer", environment: "Staging", suiteId: "ts-006", suiteName: "Payroll & Salary", lastRunDate: "2026-08-23", lastRunBy: "Sunita Reddy", tags: ["smoke"], createdAt: "2026-07-11T10:00:00Z", updatedAt: "2026-08-23T10:00:00Z" },
  { id: "tc-019", title: "Verify deduction calculations", module: "Payroll", description: "Verify PF, ESI, tax deductions are correct", preconditions: "Employee has PF and ESI configured", steps: ["Generate payslip", "Check deduction amounts"], expectedResult: "Deductions match configured percentages", status: "PASSED", priority: "HIGH", severity: "MAJOR", assignee: "Sunita Reddy", assigneeRole: "QA Engineer", environment: "Staging", suiteId: "ts-006", suiteName: "Payroll & Salary", lastRunDate: "2026-08-23", lastRunBy: "Sunita Reddy", tags: ["regression", "validation"], createdAt: "2026-07-11T10:00:00Z", updatedAt: "2026-08-23T10:00:00Z" },
  // Auth
  { id: "tc-020", title: "Login with valid credentials", module: "Auth", description: "Verify successful login with correct email and password", preconditions: "User account exists", steps: ["Navigate to login page", "Enter email and password", "Click Login"], expectedResult: "User is redirected to dashboard", status: "PASSED", priority: "CRITICAL", severity: "BLOCKER", assignee: "Rajiv Kumar", assigneeRole: "QA Lead", environment: "Staging", suiteId: "ts-007", suiteName: "Authentication & Roles", lastRunDate: "2026-08-10", lastRunBy: "Rajiv Kumar", tags: ["smoke", "critical-path"], createdAt: "2026-05-16T10:00:00Z", updatedAt: "2026-08-10T10:00:00Z" },
  { id: "tc-021", title: "Login with invalid credentials", module: "Auth", description: "Verify error message for wrong password", preconditions: "User account exists", steps: ["Navigate to login page", "Enter correct email but wrong password", "Click Login"], expectedResult: "Error message: Invalid email or password", status: "PASSED", priority: "CRITICAL", severity: "MAJOR", assignee: "Rajiv Kumar", assigneeRole: "QA Lead", environment: "Staging", suiteId: "ts-007", suiteName: "Authentication & Roles", lastRunDate: "2026-08-10", lastRunBy: "Rajiv Kumar", tags: ["security"], createdAt: "2026-05-16T10:00:00Z", updatedAt: "2026-08-10T10:00:00Z" },
  { id: "tc-022", title: "Session timeout after inactivity", module: "Auth", description: "Verify session expires after configured timeout", preconditions: "User is logged in", steps: ["Login as user", "Wait for session timeout period", "Attempt to navigate"], expectedResult: "User is redirected to login page", status: "PASSED", priority: "MEDIUM", severity: "MINOR", assignee: "Rajiv Kumar", assigneeRole: "QA Lead", environment: "Staging", suiteId: "ts-007", suiteName: "Authentication & Roles", lastRunDate: "2026-08-10", lastRunBy: "Rajiv Kumar", tags: ["security"], createdAt: "2026-05-20T10:00:00Z", updatedAt: "2026-08-10T10:00:00Z" },
  // Communication
  { id: "tc-023", title: "Send announcement to all staff", module: "Communication", description: "Verify announcement is broadcast to all staff", preconditions: "User is admin or principal", steps: ["Navigate to Announcements", "Create new announcement", "Select target: All Staff", "Publish"], expectedResult: "Announcement appears in staff notifications", status: "PASSED", priority: "HIGH", severity: "MAJOR", assignee: "Priya Kapoor", assigneeRole: "QA Lead", environment: "Staging", suiteId: "ts-008", suiteName: "Notification System", lastRunDate: "2026-08-26", lastRunBy: "Priya Kapoor", tags: ["regression"], createdAt: "2026-07-21T10:00:00Z", updatedAt: "2026-08-26T10:00:00Z" },
  { id: "tc-024", title: "Push notification for exam schedule", module: "Communication", description: "Verify push notification is sent when exam is scheduled", preconditions: "Exam is scheduled for upcoming date", steps: ["Schedule exam for tomorrow", "Check student devices for notification"], expectedResult: "Push notification received with exam details", status: "FAILED", priority: "HIGH", severity: "MAJOR", assignee: "Priya Kapoor", assigneeRole: "QA Lead", environment: "Staging", suiteId: "ts-008", suiteName: "Notification System", lastRunDate: "2026-08-26", lastRunBy: "Priya Kapoor", tags: ["regression", "push-notification"], createdAt: "2026-07-21T10:00:00Z", updatedAt: "2026-08-26T10:00:00Z" },
  { id: "tc-025", title: "SMS delivery for fee reminders", module: "Communication", description: "Verify SMS is sent for pending fee reminders", preconditions: "Students with overdue fees exist", steps: ["Trigger fee reminder SMS", "Check delivery status"], expectedResult: "SMS delivered to parent phone numbers", status: "BLOCKED", priority: "MEDIUM", severity: "MINOR", assignee: "Priya Kapoor", assigneeRole: "QA Lead", environment: "Staging", suiteId: "ts-008", suiteName: "Notification System", lastRunDate: "2026-08-24", lastRunBy: "Priya Kapoor", tags: ["sms", "integration"], createdAt: "2026-07-25T10:00:00Z", updatedAt: "2026-08-24T10:00:00Z" },
  { id: "tc-026", title: "Homework notification to parents", module: "Communication", description: "Verify parents receive homework notification", preconditions: "Homework is assigned to class", steps: ["Teacher assigns homework", "Check parent notification"], expectedResult: "Parent receives notification with homework details", status: "PASSED", priority: "HIGH", severity: "MAJOR", assignee: "Priya Kapoor", assigneeRole: "QA Lead", environment: "Staging", suiteId: "ts-008", suiteName: "Notification System", lastRunDate: "2026-08-25", lastRunBy: "Priya Kapoor", tags: ["notification"], createdAt: "2026-08-01T10:00:00Z", updatedAt: "2026-08-25T10:00:00Z" },
  { id: "tc-027", title: "Bulk message to selected parents", module: "Communication", description: "Verify bulk messaging works for selected parents", preconditions: "Multiple parents exist", steps: ["Navigate to Messages", "Select multiple parents", "Compose message", "Send"], expectedResult: "Message delivered to all selected parents", status: "PASSED", priority: "MEDIUM", severity: "MINOR", assignee: "Anjali Sharma", assigneeRole: "QA Tester", environment: "Staging", suiteId: "ts-008", suiteName: "Notification System", lastRunDate: "2026-08-25", lastRunBy: "Anjali Sharma", tags: ["messaging"], createdAt: "2026-08-01T10:00:00Z", updatedAt: "2026-08-25T10:00:00Z" },
  { id: "tc-028", title: "TimeTable display per class", module: "Timetable", description: "Verify timetable displays correctly for each class", preconditions: "Timetable is configured for class", steps: ["Navigate to Timetable", "Select class and section"], expectedResult: "Weekly timetable grid shows all periods and subjects", status: "PASSED", priority: "HIGH", severity: "MAJOR", assignee: "Anjali Sharma", assigneeRole: "QA Tester", environment: "Staging", suiteId: "ts-001", suiteName: "Student Management", lastRunDate: "2026-08-19", lastRunBy: "Anjali Sharma", tags: ["regression"], createdAt: "2026-06-20T10:00:00Z", updatedAt: "2026-08-19T10:00:00Z" },
  { id: "tc-029", title: "Global search returns results", module: "Navigation", description: "Verify global search finds students, teachers, and fees", preconditions: "Data exists across modules", steps: ["Click search icon", "Type a student name", "Verify results"], expectedResult: "Search results show matching records from multiple modules", status: "PASSED", priority: "MEDIUM", severity: "MINOR", assignee: "Rajiv Kumar", assigneeRole: "QA Lead", environment: "Staging", suiteId: "ts-007", suiteName: "Authentication & Roles", lastRunDate: "2026-08-10", lastRunBy: "Rajiv Kumar", tags: ["usability"], createdAt: "2026-05-25T10:00:00Z", updatedAt: "2026-08-10T10:00:00Z" },
  { id: "tc-030", title: "Dashboard loads within 3 seconds", module: "Performance", description: "Verify dashboard renders within acceptable time", preconditions: "User is logged in", steps: ["Login", "Time dashboard load"], expectedResult: "Dashboard fully renders in under 3 seconds", status: "PASSED", priority: "MEDIUM", severity: "MINOR", assignee: "Rajiv Kumar", assigneeRole: "QA Lead", environment: "Staging", lastRunDate: "2026-08-10", lastRunBy: "Rajiv Kumar", tags: ["performance"], createdAt: "2026-05-20T10:00:00Z", updatedAt: "2026-08-10T10:00:00Z" },
];
